project:
  type: book
  output-dir: _book

# Book formatting types and options
format:
  html:
    theme: 
      - cosmo
      - r4epi_styles.scss
  pdf:
    documentclass: scrreprt
    
# Bibliography and citation options
bibliography: references.bib
csl: ama.csl

# Set editor to default to source view instead of visual view
editor: source

# To make sure that R, Python, and Julia code is only executed locally, 
# configure your project to use Quarto’s freeze feature by adding this to your 
# _quarto/.yml. (https://quarto.org/docs/publishing/netlify.html)
execute:
  freeze: auto

# Book structure and options
book:
  # Basic metadata
  title: "R 4 Epidemiology"
  date: today
  favicon: r4epi_favicon.png
  site-url: https://github.com/brad-cannell/r4epi
  repo-url: https://github.com/brad-cannell/r4epi
  repo-actions: [edit, issue]
  page-footer: 
    left: |
      R for Epidemiology
    right: |
      This book was built with <a href="https://Quarto/.org/">Quarto/</a>.
  
  # Book options
  search: true
  downloads: [pdf] # https://quarto/.org/docs/books/book-output.html#sidebar-tools
  sharing: [twitter, facebook, linkedin]
  page-navigation: true # Haven't played with this much yet. https://quarto/.org/docs/books/book-structure.html#page-navigation
  
  # Google Analytics
  google-analytics: "G-0RREBTQ0D9"
  cookie-consent: true

  # Chapter sturcture
  # https://quarto/.org/docs/books/book-structure.html
  chapters:
    # Index is the landing page for the HTML version of the book.
    - index.qmd
    - chapters/introduction.qmd
    - chapters/contributing/contributing.qmd
    - chapters/about_the_authors/about_the_authors.qmd
    
    # Parts can be qmd files (if you want explanitory text) or characater strings
    # if you only want a part title. The separate qmd document method does not 
    # look good in pdf format.
    - part: "Getting Started"
      chapters: 
        - chapters/installing_r_and_rstudio/installing_r_and_rstudio.qmd
        - chapters/what_is_r/what_is_r.qmd
        - chapters/navigating_rstudio/navigating_rstudio.qmd
        - chapters/speaking_r/speaking_r.qmd
        - chapters/lets_get_programming/lets_get_programming.qmd
        - chapters/asking_questions/asking_questions.qmd
      
    - part: "Coding Tools and Best Practices"
      chapters:
        - chapters/r_scripts/r_scripts.qmd
        - chapters/quarto_files/quarto_files.qmd
        - chapters/r_projects/projects.qmd
        - chapters/best_practices/best_practices.qmd
        - chapters/using_pipes/using_pipes.qmd
        
    - part: "Data Transfer"
      chapters: 
      - chapters/data_transfer/data_transfer.qmd
      - chapters/file_paths/file_paths.qmd
      - chapters/importing_plain_text/importing_plain_text.qmd
      - chapters/importing_binary_files/importing_binary_files.qmd
      - chapters/rstudio_import_tool/rstudio_import_tool.qmd
      - chapters/exporting_data_to_disk/exporting_data_to_disk.qmd
      
    - part: "Descriptive Analysis"
      chapters: 
      - chapters/intro_descriptive_analysis/intro_descriptive_analysis.qmd
      - chapters/categorical_variables/categorical_variables.qmd
      - chapters/central_tendency/central_tendency.qmd
      - chapters/dispersion/dispersion.qmd
      - chapters/cont_out_cont_pred/cont_out_cont_pred.qmd
      - chapters/cont_out_cat_pred/cont_out_cat_pred.qmd
      - chapters/cat_out_cat_pred/cat_out_cat_pred.qmd

    - part: "Data Management"
      chapters: 
        - chapters/intro_data_management/introduction.qmd
        - chapters/creating_and_modifying_columns/creating_and_modifying_columns.qmd
        - chapters/subsetting_data_frames/subsetting_data_frames.qmd
        - chapters/working_with_dates/working_with_dates.qmd
        - chapters/working_with_character_strings/working_with_character_strings.qmd
        - chapters/conditional_operations/conditional_operations.qmd
        - chapters/multiple_data_frames/multiple_data_frames.qmd
        - chapters/restructuring_data_frames/restructuring_data_frames.qmd
      
    - part: "Repeated Operations"
      chapters:
      - chapters/intro_repeated_operations/intro_repeated_operations.qmd
      - chapters/writing_functions/writing_functions.qmd
      - chapters/dplyr_column_wise/dplyr_column_wise.qmd
      - chapters/writing_for_loops/writing_for_loops.qmd
      - chapters/using_purrr/using_purrr.qmd
         
    - part: "Collaboration"
      chapters: 
      - chapters/intro_git_github/intro_git_github.qmd
      - chapters/using_git_github/using_git_github.qmd
    
    - part: "Presenting Results"
      chapters: 
        - chapters/creating_word_tables/creating_word_tables.qmd
        
    - part: "References"
      chapters:
        - references.qmd
  
  # We can also add appendices and track them separately from other book parts.  
  appendices:
    - chapters/appendices/glossary.qmd
