--- 
title: "R for Epidemiology"
author: "Brad Cannell"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: brad-cannell/r4epi
url: 'https://brad-cannell.github.io/r4epi/'
description: "This is the textbook for Brad Cannell's Introduction to R Programming for Epidemiologic Research course."
---

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```

# Welcome {-}

Welcome to R for Epidemiology! 

I'm going to start the book by writing down some basic goals that underlie the construction and content of this book. I'm writing this for you, the reader, but also to hold myself accountable as I write. 
 
The goals of this book are:    

1. Make this writing as accessible and practically useful as possible without stripping out all of the complexity that makes doing epidemiology in real life a challenge. In other words, I'm going to try to give you all the tools you need to _do_ epidemiology in "real world" (as opposed to ideal) conditions without providing a whole bunch of extraneous (often theoretical) stuff that detracts from _doing_. Having said that, I will strive to add links to the other (often theoretical) stuff for readers who are interested.

2. Where possible, we will start each concept with the end result and then deconstruct how we arrived at that result. I find that it is easier for me to understand new concepts when learning them as a component of a final product.

3. Where possible, we will learn concepts with data instead of (or alongside) mathematical formulas and text descriptions. I find that it is easier for me to understand new concepts by seeing them in action.


<!--
Epidemiology is the study of the distribution of…. Good enough for our purposes.

Introduction: What are we doing here? The big picture. Grab some headlines from the news (Corona virus, Ebola virus, HIV, Chronic diseases, 
-->
