# Introduction to Causality

```{=html}
<!-- 
Hidden comments placeholder
---------------------------

To preview:
bookdown::preview_chapter("chapters/10_part_intro_epi/04_measures_of_association.Rmd")

Copy and paste:
👆**Here's what we did above:**

-->
```

::: under-construction
`r fontawesome::fa("hammer", fill = "#000000", height="1em")` This chapter is under heavy development and may still undergo significant changes.
:::

<!-- Add a banner -->

<!-- I moved this content over from the measures of association chapter. -->

> “[An <span class="u-orange-text">association</span> is a] <span class="u-orange-text">statistical dependence</span> between two or more events, characteristics, or other variables. An association is present if the <span class="u-orange-text">probability of occurrence</span> of an event or characteristic, or the quantity of a variable, varies with the occurrence of one or more other events, the presence of one or more other characteristics, or the quantity of one or more <span class="u-orange-text">other variables</span>." @Porta2008-ij

There's a lot in that definition, so let's break it down a little bit more. First of all, we can reasonably substitute the word "outcome" in for the part of the definition that reads "an event or characteristic, or the quantity of a variable." Second, we can reasonably substitute the word "exposures" for the part of the definition that reads "events, the presence of one or more other characteristics, or the quantity of one or more other variables." Doing so would change the second sentence of the definition above to: 

> An association is present if the probability of occurrence of an <span class="u-orange-text">outcome</span> varies with the occurrence of one or more other <span class="u-orange-text">exposures</span>.

This is more concise, but we still need to unpack some terms in that definition. For starters, what is an exposure and what is an outcome?

## Exposures and outcomes

In epidemiology, the terms **exposure** and **outcome** are used all of the time. Both terms can refer to pathogens, environmental conditions, behaviors, traits, social conditions, diseases or health conditions, and/or treatments or interventions. Table \@ref(tab:measures-of-association-exposures-and-outcomes-tab) below contains some examples.

```{r measures-of-association-exposures-and-outcomes-tab, echo=FALSE}
pathogen_ex <- "Tapeworm, Malaria, Ringworm, Streptococcus, and HPV"
environmental_ex <- "Dust particles, Lead, Pesticides, and Raditation"
behavior_ex <- "Smoking, Physical Activity, Sleep, and Sexual behaviors"
trait_ex  <- "Genotype and Sex assigned at birth"
social_ex <- "Discrimination, Neighborhood characteristics, and Culture"
disease_ex <- "Diabetes, Heart disease, and Cancers"
treatment_ex <- "Medications, Smoking cessation programs, and Laws and policies"

exposures_and_outcomes_examples <- tribble(
  ~Term,                         ~Examples,
  "Pathogens",                   pathogen_ex,
  "Environmental condtions",     behavior_ex,
  "Behaviors",                   trait_ex,
  "Social conditions",           social_ex,
  "Diseases or condtions",       disease_ex,
  "Treatments or interventions", treatment_ex
)

knitr::kable(
  exposures_and_outcomes_examples,
  caption = "Examples of exposures and outcomes."
)
```

So, what distinguishes an exposure from an outcome? Generally speaking, _we_ do. When we are exploring the relationship between two variables (i.e., events, characteristics, diseases, etc.), it is customary to call the first variable an _exposure_ if we believe it is the cause of the second variable, and to call the second variable an _outcome_ if we believe it is caused by the first variable. We haven't formally defined causes and effects yet, and we won't until the part of the book about [causality][Introduction to Causality], but our intuitive/colloquial understanding of cause and effect should be sufficient for now. With that in mind, virtually any of the examples from table \@ref(tab:measures-of-association-exposures-and-outcomes-tab) could reasonably be thought of as an exposure _or_ an outcome depending on the question we are trying to answer, and our beliefs about how causes and effects work in the world around us. For example, if we believe that unprotected sex is a cause of HPV infection, then we may want to measure the association between unprotected sex (an exposure) and HPV infection (an outcome). However, we could also believe that HPV infection is a cause of cervical cancer. In that case, we may want to measure the association between HPV infection (an exposure) and the existence of cervical cancer (an outcome). Notice that HPV infection is not inherently an exposure or an outcome. Rather, _we_ labeled it as an exposure or an outcome based on the question we were asking and our beliefs about its relationship to the variable we were comparing it to.  

The paragraph above may have left you with the impression that measuring associations is the same thing as measuring causes and effects. **That is not the case!** In fact, many readers may already be familiar with the popular saying "association does not equal causation" or "correlation does not equal causation." These sayings are correct. There is virtually an infinite number of possible examples of statistical associations that have nothing to do with cause and effect relationships. So, why did we start talking about causes and effects now? We started talking about causes and effects now because 