# R projects

In previous chapters of this book, you learned how to use R scripts and R markdown files to create, modify, save, and share your R code and results. In many real-world projects, you will end up creating multiple R scripts and/or R markdown files. You may even have other files (e.g., images or data) that you want to store alongside your R code files. Over time, keeping up with all of these files can become cumbersome. One tool for helping you organize and manage collections of files is to organize them with R project files. 

Because nothing we will do in this book really requires creating projects, I'm not going to discuss them further at this point. It would probably just end up confusing some of you unnecessarily. However, I wanted to mention that R project files exist in case you ever end up needing them someday for your real-world data analysis projects. I recommend that interested readers start with Grolemund and Wickham's [chapter on projects in R for Data Science](https://r4ds.had.co.nz/workflow-projects.html). @Grolemund2017-qp
