<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>18 Creating tables with R and Microsoft Word | R for Epidemiology</title>
  <meta name="description" content="This is the textbook for Brad Cannell’s Introduction to R Programming for Epidemiologic Research course." />
  <meta name="generator" content="bookdown 0.18 and GitBook 2.6.7" />

  <meta property="og:title" content="18 Creating tables with R and Microsoft Word | R for Epidemiology" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://brad-cannell.github.io/r4epi/" />
  
  <meta property="og:description" content="This is the textbook for Brad Cannell’s Introduction to R Programming for Epidemiologic Research course." />
  <meta name="github-repo" content="brad-cannell/r4epi" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="18 Creating tables with R and Microsoft Word | R for Epidemiology" />
  
  <meta name="twitter:description" content="This is the textbook for Brad Cannell’s Introduction to R Programming for Epidemiologic Research course." />
  

<meta name="author" content="Brad Cannell" />


<meta name="date" content="2020-06-10" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="describing-the-relationship-between-a-categorical-outcome-and-a-categorical-predictor.html"/>
<link rel="next" href="appendix-a-glossary.html"/>
<script src="libs/header-attrs-2.1/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R for Epidemiology</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="chapter" data-level="" data-path="about-the-author.html"><a href="about-the-author.html"><i class="fa fa-check"></i>About the Author</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="part"><span><b>I Getting Started</b></span></li>
<li class="chapter" data-level="1" data-path="installing-r-and-rstudio.html"><a href="installing-r-and-rstudio.html"><i class="fa fa-check"></i><b>1</b> Installing R and RStudio</a>
<ul>
<li class="chapter" data-level="1.1" data-path="installing-r-and-rstudio.html"><a href="installing-r-and-rstudio.html#download-and-install-on-a-mac"><i class="fa fa-check"></i><b>1.1</b> Download and install on a Mac</a></li>
<li class="chapter" data-level="1.2" data-path="installing-r-and-rstudio.html"><a href="installing-r-and-rstudio.html#download-and-install-on-a-pc"><i class="fa fa-check"></i><b>1.2</b> Download and install on a PC</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="what-is-r.html"><a href="what-is-r.html"><i class="fa fa-check"></i><b>2</b> What is R?</a>
<ul>
<li class="chapter" data-level="2.1" data-path="what-is-r.html"><a href="what-is-r.html#what-is-data"><i class="fa fa-check"></i><b>2.1</b> What is data?</a></li>
<li class="chapter" data-level="2.2" data-path="what-is-r.html"><a href="what-is-r.html#what-is-r-1"><i class="fa fa-check"></i><b>2.2</b> What is R?</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="what-is-r.html"><a href="what-is-r.html#accessing-data"><i class="fa fa-check"></i><b>2.2.1</b> Accessing data</a></li>
<li class="chapter" data-level="2.2.2" data-path="what-is-r.html"><a href="what-is-r.html#managing-data"><i class="fa fa-check"></i><b>2.2.2</b> Managing data</a></li>
<li class="chapter" data-level="2.2.3" data-path="what-is-r.html"><a href="what-is-r.html#analyzing-data"><i class="fa fa-check"></i><b>2.2.3</b> Analyzing data</a></li>
<li class="chapter" data-level="2.2.4" data-path="what-is-r.html"><a href="what-is-r.html#presenting-data"><i class="fa fa-check"></i><b>2.2.4</b> Presenting data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="navigating-the-rstudio-interface.html"><a href="navigating-the-rstudio-interface.html"><i class="fa fa-check"></i><b>3</b> Navigating the RStudio interface</a>
<ul>
<li class="chapter" data-level="3.1" data-path="navigating-the-rstudio-interface.html"><a href="navigating-the-rstudio-interface.html#the-console"><i class="fa fa-check"></i><b>3.1</b> The console</a></li>
<li class="chapter" data-level="3.2" data-path="navigating-the-rstudio-interface.html"><a href="navigating-the-rstudio-interface.html#the-environment-pane"><i class="fa fa-check"></i><b>3.2</b> The environment pane</a></li>
<li class="chapter" data-level="3.3" data-path="navigating-the-rstudio-interface.html"><a href="navigating-the-rstudio-interface.html#the-files-pane"><i class="fa fa-check"></i><b>3.3</b> The files pane</a></li>
<li class="chapter" data-level="3.4" data-path="navigating-the-rstudio-interface.html"><a href="navigating-the-rstudio-interface.html#the-source-pane"><i class="fa fa-check"></i><b>3.4</b> The source pane</a></li>
<li class="chapter" data-level="3.5" data-path="navigating-the-rstudio-interface.html"><a href="navigating-the-rstudio-interface.html#rstudio-preferences"><i class="fa fa-check"></i><b>3.5</b> RStudio preferences</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="speaking-rs-language.html"><a href="speaking-rs-language.html"><i class="fa fa-check"></i><b>4</b> Speaking R’s language</a>
<ul>
<li class="chapter" data-level="4.1" data-path="speaking-rs-language.html"><a href="speaking-rs-language.html#r-is-a-language"><i class="fa fa-check"></i><b>4.1</b> R is a <em>language</em></a></li>
<li class="chapter" data-level="4.2" data-path="speaking-rs-language.html"><a href="speaking-rs-language.html#the-r-interpreter"><i class="fa fa-check"></i><b>4.2</b> The R interpreter</a></li>
<li class="chapter" data-level="4.3" data-path="speaking-rs-language.html"><a href="speaking-rs-language.html#errors"><i class="fa fa-check"></i><b>4.3</b> Errors</a></li>
<li class="chapter" data-level="4.4" data-path="speaking-rs-language.html"><a href="speaking-rs-language.html#functions"><i class="fa fa-check"></i><b>4.4</b> Functions</a></li>
<li class="chapter" data-level="4.5" data-path="speaking-rs-language.html"><a href="speaking-rs-language.html#objects"><i class="fa fa-check"></i><b>4.5</b> Objects</a></li>
<li class="chapter" data-level="4.6" data-path="speaking-rs-language.html"><a href="speaking-rs-language.html#comments"><i class="fa fa-check"></i><b>4.6</b> Comments</a></li>
<li class="chapter" data-level="4.7" data-path="speaking-rs-language.html"><a href="speaking-rs-language.html#packages"><i class="fa fa-check"></i><b>4.7</b> Packages</a></li>
<li class="chapter" data-level="4.8" data-path="speaking-rs-language.html"><a href="speaking-rs-language.html#programming-style"><i class="fa fa-check"></i><b>4.8</b> Programming style</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="lets-get-programming.html"><a href="lets-get-programming.html"><i class="fa fa-check"></i><b>5</b> Let’s get programming</a>
<ul>
<li class="chapter" data-level="5.1" data-path="lets-get-programming.html"><a href="lets-get-programming.html#simulating-data"><i class="fa fa-check"></i><b>5.1</b> Simulating data</a></li>
<li class="chapter" data-level="5.2" data-path="lets-get-programming.html"><a href="lets-get-programming.html#vectors"><i class="fa fa-check"></i><b>5.2</b> Vectors</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="lets-get-programming.html"><a href="lets-get-programming.html#vector-types"><i class="fa fa-check"></i><b>5.2.1</b> Vector types</a></li>
<li class="chapter" data-level="5.2.2" data-path="lets-get-programming.html"><a href="lets-get-programming.html#double-vectors"><i class="fa fa-check"></i><b>5.2.2</b> Double vectors</a></li>
<li class="chapter" data-level="5.2.3" data-path="lets-get-programming.html"><a href="lets-get-programming.html#integer-vectors"><i class="fa fa-check"></i><b>5.2.3</b> Integer vectors</a></li>
<li class="chapter" data-level="5.2.4" data-path="lets-get-programming.html"><a href="lets-get-programming.html#logical-vectors"><i class="fa fa-check"></i><b>5.2.4</b> Logical vectors</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="lets-get-programming.html"><a href="lets-get-programming.html#data-frames"><i class="fa fa-check"></i><b>5.3</b> Data frames</a></li>
<li class="chapter" data-level="5.4" data-path="lets-get-programming.html"><a href="lets-get-programming.html#missing-data"><i class="fa fa-check"></i><b>5.4</b> Missing data</a></li>
<li class="chapter" data-level="5.5" data-path="lets-get-programming.html"><a href="lets-get-programming.html#our-first-analysis"><i class="fa fa-check"></i><b>5.5</b> Our first analysis</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="lets-get-programming.html"><a href="lets-get-programming.html#manual-calculation-of-the-mean"><i class="fa fa-check"></i><b>5.5.1</b> Manual calculation of the mean</a></li>
<li class="chapter" data-level="5.5.2" data-path="lets-get-programming.html"><a href="lets-get-programming.html#dollar-sign-notation"><i class="fa fa-check"></i><b>5.5.2</b> Dollar sign notation</a></li>
<li class="chapter" data-level="5.5.3" data-path="lets-get-programming.html"><a href="lets-get-programming.html#bracket-notation"><i class="fa fa-check"></i><b>5.5.3</b> Bracket notation</a></li>
<li class="chapter" data-level="5.5.4" data-path="lets-get-programming.html"><a href="lets-get-programming.html#the-sum-function"><i class="fa fa-check"></i><b>5.5.4</b> The sum function</a></li>
<li class="chapter" data-level="5.5.5" data-path="lets-get-programming.html"><a href="lets-get-programming.html#nesting-functions"><i class="fa fa-check"></i><b>5.5.5</b> Nesting functions</a></li>
<li class="chapter" data-level="5.5.6" data-path="lets-get-programming.html"><a href="lets-get-programming.html#the-length-function"><i class="fa fa-check"></i><b>5.5.6</b> The length function</a></li>
<li class="chapter" data-level="5.5.7" data-path="lets-get-programming.html"><a href="lets-get-programming.html#the-mean-function"><i class="fa fa-check"></i><b>5.5.7</b> The mean function</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="lets-get-programming.html"><a href="lets-get-programming.html#some-common-errors"><i class="fa fa-check"></i><b>5.6</b> Some common errors</a></li>
<li class="chapter" data-level="5.7" data-path="lets-get-programming.html"><a href="lets-get-programming.html#summary"><i class="fa fa-check"></i><b>5.7</b> Summary</a></li>
</ul></li>
<li class="part"><span><b>II Coding Tools and Best Practices</b></span></li>
<li class="chapter" data-level="6" data-path="r-scripts.html"><a href="r-scripts.html"><i class="fa fa-check"></i><b>6</b> R scripts</a>
<ul>
<li class="chapter" data-level="6.1" data-path="r-scripts.html"><a href="r-scripts.html#creating-r-scripts"><i class="fa fa-check"></i><b>6.1</b> Creating R scripts</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="r-markdown.html"><a href="r-markdown.html"><i class="fa fa-check"></i><b>7</b> R markdown</a>
<ul>
<li class="chapter" data-level="7.1" data-path="r-markdown.html"><a href="r-markdown.html#what-is-r-markdown"><i class="fa fa-check"></i><b>7.1</b> What is R markdown?</a></li>
<li class="chapter" data-level="7.2" data-path="r-markdown.html"><a href="r-markdown.html#why-use-r-markdown"><i class="fa fa-check"></i><b>7.2</b> Why use R markdown?</a></li>
<li class="chapter" data-level="7.3" data-path="r-markdown.html"><a href="r-markdown.html#create-an-r-markdown-file"><i class="fa fa-check"></i><b>7.3</b> Create an R markdown file</a></li>
<li class="chapter" data-level="7.4" data-path="r-markdown.html"><a href="r-markdown.html#yaml-headers"><i class="fa fa-check"></i><b>7.4</b> YAML headers</a></li>
<li class="chapter" data-level="7.5" data-path="r-markdown.html"><a href="r-markdown.html#r-code-chunks"><i class="fa fa-check"></i><b>7.5</b> R code chunks</a></li>
<li class="chapter" data-level="7.6" data-path="r-markdown.html"><a href="r-markdown.html#markdown"><i class="fa fa-check"></i><b>7.6</b> Markdown</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="r-projects.html"><a href="r-projects.html"><i class="fa fa-check"></i><b>8</b> R projects</a></li>
<li class="chapter" data-level="9" data-path="coding-best-practices.html"><a href="coding-best-practices.html"><i class="fa fa-check"></i><b>9</b> Coding best practices</a>
<ul>
<li class="chapter" data-level="9.1" data-path="coding-best-practices.html"><a href="coding-best-practices.html#general-principles"><i class="fa fa-check"></i><b>9.1</b> General principles</a></li>
<li class="chapter" data-level="9.2" data-path="coding-best-practices.html"><a href="coding-best-practices.html#code-comments"><i class="fa fa-check"></i><b>9.2</b> Code comments</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="coding-best-practices.html"><a href="coding-best-practices.html#defining-key-variables"><i class="fa fa-check"></i><b>9.2.1</b> Defining key variables</a></li>
<li class="chapter" data-level="9.2.2" data-path="coding-best-practices.html"><a href="coding-best-practices.html#what-this-code-is-trying-to-accomplish"><i class="fa fa-check"></i><b>9.2.2</b> What this code is trying to accomplish</a></li>
<li class="chapter" data-level="9.2.3" data-path="coding-best-practices.html"><a href="coding-best-practices.html#why-i-chose-this-particular-strategy"><i class="fa fa-check"></i><b>9.2.3</b> Why I chose this particular strategy</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="coding-best-practices.html"><a href="coding-best-practices.html#style-guidelines"><i class="fa fa-check"></i><b>9.3</b> Style guidelines</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="coding-best-practices.html"><a href="coding-best-practices.html#object-variable-names"><i class="fa fa-check"></i><b>9.3.1</b> Object (variable) names</a></li>
<li class="chapter" data-level="9.3.2" data-path="coding-best-practices.html"><a href="coding-best-practices.html#use-names-that-are-informative"><i class="fa fa-check"></i><b>9.3.2</b> Use names that are informative</a></li>
<li class="chapter" data-level="9.3.3" data-path="coding-best-practices.html"><a href="coding-best-practices.html#file-names"><i class="fa fa-check"></i><b>9.3.3</b> File Names</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="using-pipes.html"><a href="using-pipes.html"><i class="fa fa-check"></i><b>10</b> Using pipes</a>
<ul>
<li class="chapter" data-level="10.1" data-path="using-pipes.html"><a href="using-pipes.html#what-are-pipes"><i class="fa fa-check"></i><b>10.1</b> What are pipes?</a></li>
<li class="chapter" data-level="10.2" data-path="using-pipes.html"><a href="using-pipes.html#how-do-pipes-work"><i class="fa fa-check"></i><b>10.2</b> How do pipes work?</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="using-pipes.html"><a href="using-pipes.html#keyboard-shortcut"><i class="fa fa-check"></i><b>10.2.1</b> Keyboard shortcut</a></li>
<li class="chapter" data-level="10.2.2" data-path="using-pipes.html"><a href="using-pipes.html#pipe-style"><i class="fa fa-check"></i><b>10.2.2</b> Pipe style</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="using-pipes.html"><a href="using-pipes.html#final-thought-on-pipes"><i class="fa fa-check"></i><b>10.3</b> Final thought on pipes</a></li>
</ul></li>
<li class="part"><span><b>III Descriptive Analysis</b></span></li>
<li class="chapter" data-level="11" data-path="introduction-to-descriptive-analysis.html"><a href="introduction-to-descriptive-analysis.html"><i class="fa fa-check"></i><b>11</b> Introduction to descriptive analysis</a>
<ul>
<li class="chapter" data-level="11.1" data-path="introduction-to-descriptive-analysis.html"><a href="introduction-to-descriptive-analysis.html#what-is-descriptive-analysis-and-why-would-we-do-it"><i class="fa fa-check"></i><b>11.1</b> What is descriptive analysis and why would we do it?</a></li>
<li class="chapter" data-level="11.2" data-path="introduction-to-descriptive-analysis.html"><a href="introduction-to-descriptive-analysis.html#what-kind-of-descriptive-analysis-should-we-perform"><i class="fa fa-check"></i><b>11.2</b> What kind of descriptive analysis should we perform?</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="numerical-descriptions-of-categorical-variables.html"><a href="numerical-descriptions-of-categorical-variables.html"><i class="fa fa-check"></i><b>12</b> Numerical descriptions of categorical variables</a>
<ul>
<li class="chapter" data-level="12.1" data-path="numerical-descriptions-of-categorical-variables.html"><a href="numerical-descriptions-of-categorical-variables.html#height-and-weight-data"><i class="fa fa-check"></i><b>12.1</b> Height and Weight Data</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="numerical-descriptions-of-categorical-variables.html"><a href="numerical-descriptions-of-categorical-variables.html#view-the-data"><i class="fa fa-check"></i><b>12.1.1</b> View the data</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="numerical-descriptions-of-categorical-variables.html"><a href="numerical-descriptions-of-categorical-variables.html#calculating-frequencies"><i class="fa fa-check"></i><b>12.2</b> Calculating frequencies</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="numerical-descriptions-of-categorical-variables.html"><a href="numerical-descriptions-of-categorical-variables.html#the-base-r-table-function"><i class="fa fa-check"></i><b>12.2.1</b> The base R table function</a></li>
<li class="chapter" data-level="12.2.2" data-path="numerical-descriptions-of-categorical-variables.html"><a href="numerical-descriptions-of-categorical-variables.html#the-gmodels-crosstable-function"><i class="fa fa-check"></i><b>12.2.2</b> The gmodels CrossTable function</a></li>
<li class="chapter" data-level="12.2.3" data-path="numerical-descriptions-of-categorical-variables.html"><a href="numerical-descriptions-of-categorical-variables.html#the-tidyverse-way"><i class="fa fa-check"></i><b>12.2.3</b> The tidyverse way</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="numerical-descriptions-of-categorical-variables.html"><a href="numerical-descriptions-of-categorical-variables.html#calculating-percentages"><i class="fa fa-check"></i><b>12.3</b> Calculating percentages</a></li>
<li class="chapter" data-level="12.4" data-path="numerical-descriptions-of-categorical-variables.html"><a href="numerical-descriptions-of-categorical-variables.html#missing-data-1"><i class="fa fa-check"></i><b>12.4</b> Missing data</a></li>
<li class="chapter" data-level="12.5" data-path="numerical-descriptions-of-categorical-variables.html"><a href="numerical-descriptions-of-categorical-variables.html#formatting-results"><i class="fa fa-check"></i><b>12.5</b> Formatting results</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="measures-of-central-tendency.html"><a href="measures-of-central-tendency.html"><i class="fa fa-check"></i><b>13</b> Measures of central tendency</a>
<ul>
<li class="chapter" data-level="13.1" data-path="measures-of-central-tendency.html"><a href="measures-of-central-tendency.html#calculate-the-mean"><i class="fa fa-check"></i><b>13.1</b> Calculate the mean</a></li>
<li class="chapter" data-level="13.2" data-path="measures-of-central-tendency.html"><a href="measures-of-central-tendency.html#calculate-the-median"><i class="fa fa-check"></i><b>13.2</b> Calculate the median</a></li>
<li class="chapter" data-level="13.3" data-path="measures-of-central-tendency.html"><a href="measures-of-central-tendency.html#calculate-the-mode"><i class="fa fa-check"></i><b>13.3</b> Calculate the mode</a></li>
<li class="chapter" data-level="13.4" data-path="measures-of-central-tendency.html"><a href="measures-of-central-tendency.html#compare-mean-median-and-mode"><i class="fa fa-check"></i><b>13.4</b> Compare mean, median, and mode</a></li>
<li class="chapter" data-level="13.5" data-path="measures-of-central-tendency.html"><a href="measures-of-central-tendency.html#data-checking"><i class="fa fa-check"></i><b>13.5</b> Data checking</a></li>
<li class="chapter" data-level="13.6" data-path="measures-of-central-tendency.html"><a href="measures-of-central-tendency.html#properties-of-mean-median-and-mode"><i class="fa fa-check"></i><b>13.6</b> Properties of mean, median, and mode</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="measures-of-dispersion.html"><a href="measures-of-dispersion.html"><i class="fa fa-check"></i><b>14</b> Measures of dispersion</a>
<ul>
<li class="chapter" data-level="14.1" data-path="measures-of-dispersion.html"><a href="measures-of-dispersion.html#comparing-distributions"><i class="fa fa-check"></i><b>14.1</b> Comparing distributions</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="describing-the-relationship-between-a-continuous-outcome-and-a-continuous-predictor.html"><a href="describing-the-relationship-between-a-continuous-outcome-and-a-continuous-predictor.html"><i class="fa fa-check"></i><b>15</b> Describing the relationship between a continuous outcome and a continuous predictor</a>
<ul>
<li class="chapter" data-level="15.1" data-path="describing-the-relationship-between-a-continuous-outcome-and-a-continuous-predictor.html"><a href="describing-the-relationship-between-a-continuous-outcome-and-a-continuous-predictor.html#pearson-correlation-coefficient"><i class="fa fa-check"></i><b>15.1</b> Pearson Correlation Coefficient</a>
<ul>
<li class="chapter" data-level="15.1.1" data-path="describing-the-relationship-between-a-continuous-outcome-and-a-continuous-predictor.html"><a href="describing-the-relationship-between-a-continuous-outcome-and-a-continuous-predictor.html#calculating-r"><i class="fa fa-check"></i><b>15.1.1</b> Calculating r</a></li>
<li class="chapter" data-level="15.1.2" data-path="describing-the-relationship-between-a-continuous-outcome-and-a-continuous-predictor.html"><a href="describing-the-relationship-between-a-continuous-outcome-and-a-continuous-predictor.html#correlation-intuition"><i class="fa fa-check"></i><b>15.1.2</b> Correlation intuition</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="describing-the-relationship-between-a-continuous-outcome-and-a-categorical-predictor.html"><a href="describing-the-relationship-between-a-continuous-outcome-and-a-categorical-predictor.html"><i class="fa fa-check"></i><b>16</b> Describing the relationship between a continuous outcome and a categorical predictor</a>
<ul>
<li class="chapter" data-level="16.1" data-path="describing-the-relationship-between-a-continuous-outcome-and-a-categorical-predictor.html"><a href="describing-the-relationship-between-a-continuous-outcome-and-a-categorical-predictor.html#single-predictor-and-single-outcome"><i class="fa fa-check"></i><b>16.1</b> Single predictor and single outcome</a></li>
<li class="chapter" data-level="16.2" data-path="describing-the-relationship-between-a-continuous-outcome-and-a-categorical-predictor.html"><a href="describing-the-relationship-between-a-continuous-outcome-and-a-categorical-predictor.html#multiple-predictors"><i class="fa fa-check"></i><b>16.2</b> Multiple predictors</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="describing-the-relationship-between-a-categorical-outcome-and-a-categorical-predictor.html"><a href="describing-the-relationship-between-a-categorical-outcome-and-a-categorical-predictor.html"><i class="fa fa-check"></i><b>17</b> Describing the relationship between a categorical outcome and a categorical predictor</a>
<ul>
<li class="chapter" data-level="17.1" data-path="describing-the-relationship-between-a-categorical-outcome-and-a-categorical-predictor.html"><a href="describing-the-relationship-between-a-categorical-outcome-and-a-categorical-predictor.html#comparing-two-variables"><i class="fa fa-check"></i><b>17.1</b> Comparing two variables</a></li>
</ul></li>
<li class="part"><span><b>IV Presenting Results</b></span></li>
<li class="chapter" data-level="18" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html"><i class="fa fa-check"></i><b>18</b> Creating tables with R and Microsoft Word</a>
<ul>
<li class="chapter" data-level="18.1" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#table-1"><i class="fa fa-check"></i><b>18.1</b> Table 1</a></li>
<li class="chapter" data-level="18.2" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#opioid-drug-use"><i class="fa fa-check"></i><b>18.2</b> Opioid drug use</a></li>
<li class="chapter" data-level="18.3" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#table-columns"><i class="fa fa-check"></i><b>18.3</b> Table columns</a></li>
<li class="chapter" data-level="18.4" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#table-rows"><i class="fa fa-check"></i><b>18.4</b> Table rows</a></li>
<li class="chapter" data-level="18.5" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#make-the-table-skeleton"><i class="fa fa-check"></i><b>18.5</b> Make the table skeleton</a></li>
<li class="chapter" data-level="18.6" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#fill-in-column-headers"><i class="fa fa-check"></i><b>18.6</b> Fill in column headers</a>
<ul>
<li class="chapter" data-level="18.6.1" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#group-sample-sizes"><i class="fa fa-check"></i><b>18.6.1</b> Group sample sizes</a></li>
<li class="chapter" data-level="18.6.2" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#formatting-column-headers"><i class="fa fa-check"></i><b>18.6.2</b> Formatting column headers</a></li>
</ul></li>
<li class="chapter" data-level="18.7" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#fill-in-row-headers"><i class="fa fa-check"></i><b>18.7</b> Fill in row headers</a>
<ul>
<li class="chapter" data-level="18.7.1" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#label-statistics"><i class="fa fa-check"></i><b>18.7.1</b> Label statistics</a></li>
<li class="chapter" data-level="18.7.2" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#formatting-row-headers"><i class="fa fa-check"></i><b>18.7.2</b> Formatting row headers</a></li>
</ul></li>
<li class="chapter" data-level="18.8" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#fill-in-data-values"><i class="fa fa-check"></i><b>18.8</b> Fill in data values</a>
<ul>
<li class="chapter" data-level="18.8.1" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#manually-type-values"><i class="fa fa-check"></i><b>18.8.1</b> Manually type values</a></li>
<li class="chapter" data-level="18.8.2" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#copy-and-paste-values"><i class="fa fa-check"></i><b>18.8.2</b> Copy and paste values</a></li>
<li class="chapter" data-level="18.8.3" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#knit-a-word-document"><i class="fa fa-check"></i><b>18.8.3</b> Knit a Word document</a></li>
<li class="chapter" data-level="18.8.4" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#flextable-and-officer"><i class="fa fa-check"></i><b>18.8.4</b> flextable and officer</a></li>
<li class="chapter" data-level="18.8.5" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#significant-digits"><i class="fa fa-check"></i><b>18.8.5</b> Significant digits</a></li>
<li class="chapter" data-level="18.8.6" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#formatting-data-values"><i class="fa fa-check"></i><b>18.8.6</b> Formatting data values</a></li>
</ul></li>
<li class="chapter" data-level="18.9" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#fill-in-title"><i class="fa fa-check"></i><b>18.9</b> Fill in title</a></li>
<li class="chapter" data-level="18.10" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#fill-in-footnotes"><i class="fa fa-check"></i><b>18.10</b> Fill in footnotes</a>
<ul>
<li class="chapter" data-level="18.10.1" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#formatting-footnotes"><i class="fa fa-check"></i><b>18.10.1</b> Formatting footnotes</a></li>
</ul></li>
<li class="chapter" data-level="18.11" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#final-formatting"><i class="fa fa-check"></i><b>18.11</b> Final formatting</a>
<ul>
<li class="chapter" data-level="18.11.1" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#adjust-column-widths"><i class="fa fa-check"></i><b>18.11.1</b> Adjust column widths</a></li>
<li class="chapter" data-level="18.11.2" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#merge-cells"><i class="fa fa-check"></i><b>18.11.2</b> Merge cells</a></li>
<li class="chapter" data-level="18.11.3" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#remove-cell-borders"><i class="fa fa-check"></i><b>18.11.3</b> Remove cell borders</a></li>
</ul></li>
<li class="chapter" data-level="18.12" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#summary-1"><i class="fa fa-check"></i><b>18.12</b> Summary</a></li>
</ul></li>
<li class="part"><span><b>V Appendix</b></span></li>
<li class="chapter" data-level="" data-path="appendix-a-glossary.html"><a href="appendix-a-glossary.html"><i class="fa fa-check"></i>Appendix A: Glossary</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R for Epidemiology</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="creating-tables-with-r-and-microsoft-word" class="section level1" number="18">
<h1><span class="header-section-number">18</span> Creating tables with R and Microsoft Word</h1>
<p>At this point, you should all know that it is generally a bad idea to submit raw R output as part of a report, presentation, or publication. You should also understand when it is most appropriate to use tables, as opposed to charts and graphs, to present your results. If not, please stop here and read Chapter 7 of <em>Successful Scientific Writing</em>, which discusses the “why” behind much of what I will show you “how” to do in this chapter. <span class="citation"><a href="#ref-Matthews2014-ah" role="doc-biblioref">6</a></span></p>
<p><em>R for Epidemiology</em> is predominantly a book about using R to manage, visualize, and analyze data in ways that are common in the field epidemiology. However, in most modern work/research environments it is difficult to escape the requirement to share your results in a Microsoft Word document. And often, because we are dealing with data, those results include tables of some sort. However, not all tables communicate your results equally well. In this chapter, I will walk you through the process of starting with some results you calculated in R and ending with a nicely formatted table in Microsoft Word. Specifically, we are going to create a Table 1.</p>
<div id="table-1" class="section level2" number="18.1">
<h2><span class="header-section-number">18.1</span> Table 1</h2>
<p>In epidemiology, medicine, and other disciplines, “Table 1” has a special meaning. Yes, it’s the first table shown to the reader of your article, report, or presentation, but the special meaning goes beyond that. In many disciplines, including epidemiology, when you speak to a colleague about their “Table 1” it is understood that you are speaking about a table that describes (statistically) the relevant characteristics of the sample being studied. Often, but not always, the sample being studied is made up of people, and the relevant descriptive characteristics about those people include sociodemographic and/or general health information. Therefore, it is important that you don’t label any of your tables as “Table 1” arbitrarily. Unless you have a <em>really</em> good reason to do otherwise, your Table 1 should always be a descriptive overview of your sample.</p>
<p>Here is a list of other traits that should consider when creating your Table 1:</p>
<ul>
<li><p>All other formatting best practices that apply to scientific tables in general. This includes formatting requirements specific to wherever you are submitting your table (e.g., formatting requirements in the American Journal of Public Health).</p></li>
<li><p>Table 1 is often, but not always, stratified into subgroups (i.e., descriptive results are presented separately for each subgroup of the study sample in a way that lends itself to each between-group comparisons).</p></li>
<li><p>When Table 1 is stratified into subgroups, the variable that contains the subgroups is typically the primary exposure/predictor of interest in your study.</p></li>
</ul>
</div>
<div id="opioid-drug-use" class="section level2" number="18.2">
<h2><span class="header-section-number">18.2</span> Opioid drug use</h2>
<p>As a motivating example, let’s say that we are working at the North Texas Regional Health Department and have been asked to create a report about drug use in our region. Our stakeholders are particularly interested in opioid drug use. To create this report, we will analyze data from a sample of 9,985 adults who were asked about their use of drugs. One of the first analyses that we did was a descripitive comparison of the sociodemographic characteristics of 3 subgroups of people in our data. Will will use these analyses to create our Table 1.</p>
<p class="note">
🗒<strong>Side Note:</strong> This data includes over 9,000 rows, so I don’t show the code for creating a data frame from this data. In fact, I directly imported this data into R from a comma separated values (.csv) file. We haven’t yet learned how to import csv files, but you can view/download the data by <a href="https://www.dropbox.com/s/6tw2qvq4ybgtwc2/drugs.csv?dl=0">clicking here</a> if you’d like to check it out anyway.
</p>
<pre><code>##     var              cat    n n_total   percent        se   t_crit      lcl
## 1 use_f        Non-users 8315    9985 83.274912 0.3734986 1.960202 82.52992
## 2 use_f  Use other drugs 1532    9985 15.343015 0.3606903 1.960202 14.64925
## 3 use_f Use opioid drugs  138    9985  1.382073 0.1168399 1.960202  1.17080
##         ucl
## 1 83.994296
## 2 16.063453
## 3  1.630841</code></pre>
<pre><code>##   var use    n     mean       sd   t_crit        sem      lcl      ucl
## 1 age   0 8315 36.80173 9.997545 1.960249 0.10963828 36.58681 37.01665
## 2 age   1 1532 21.98362 2.979511 1.961515 0.07612296 21.83431 22.13294
## 3 age   2  138 17.34740 3.081049 1.977431 0.26227634 16.82877 17.86603</code></pre>
<pre><code>##   row_var row_cat  col_var col_cat    n n_row n_total percent_total   se_total
## 1     use       0 female_f      No 3077  8315    9985    30.8162243 0.46210382
## 2     use       0 female_f     Yes 5238  8315    9985    52.4586880 0.49979512
## 3     use       1 female_f      No  796  1532    9985     7.9719579 0.27107552
## 4     use       1 female_f     Yes  736  1532    9985     7.3710566 0.26150858
## 5     use       2 female_f      No   91   138    9985     0.9113671 0.09510564
## 6     use       2 female_f     Yes   47   138    9985     0.4707061 0.06850118
##   t_crit_total  lcl_total  ucl_total percent_row    se_row t_crit_row  lcl_row
## 1     1.960202 29.9178650 31.7293461    37.00541 0.5295162   1.960202 35.97359
## 2     1.960202 51.4781679 53.4373162    62.99459 0.5295162   1.960202 61.95076
## 3     1.960202  7.4565108  8.5197562    51.95822 1.2768770   1.960202 49.45247
## 4     1.960202  6.8745702  7.9003577    48.04178 1.2768770   1.960202 45.54583
## 5     1.960202  0.7426382  1.1179996    65.94203 4.0488366   1.960202 57.62323
## 6     1.960202  0.3538217  0.6259604    34.05797 4.0488366   1.960202 26.61786
##    ucl_row
## 1 38.04924
## 2 64.02641
## 3 54.45417
## 4 50.54753
## 5 73.38214
## 6 42.37677</code></pre>
<pre><code>##    row_var row_cat col_var               col_cat    n n_row n_total
## 1      use       0   edu_f Less than high school 3908  8315    9985
## 2      use       0   edu_f           High school 2494  8315    9985
## 3      use       0   edu_f          Some college  915  8315    9985
## 4      use       0   edu_f      College graduate  998  8315    9985
## 5      use       1   edu_f Less than high school  322  1532    9985
## 6      use       1   edu_f           High school  567  1532    9985
## 7      use       1   edu_f          Some college  321  1532    9985
## 8      use       1   edu_f      College graduate  322  1532    9985
## 9      use       2   edu_f Less than high school   36   138    9985
## 10     use       2   edu_f           High school   36   138    9985
## 11     use       2   edu_f          Some college   40   138    9985
## 12     use       2   edu_f      College graduate   26   138    9985
##    percent_total   se_total t_crit_total  lcl_total  ucl_total percent_row
## 1     39.1387081 0.48845160     1.960202 38.1855341 40.1002400    46.99940
## 2     24.9774662 0.43322925     1.960202 24.1379137 25.8362747    29.99399
## 3      9.1637456 0.28874458     1.960202  8.6132458  9.7456775    11.00421
## 4      9.9949925 0.30017346     1.960202  9.4217947 10.5989817    12.00241
## 5      3.2248373 0.17680053     1.960202  2.8957068  3.5899942    21.01828
## 6      5.6785178 0.23161705     1.960202  5.2411937  6.1499638    37.01044
## 7      3.2148222 0.17653492     1.960202  2.8862151  3.5794637    20.95300
## 8      3.2248373 0.17680053     1.960202  2.8957068  3.5899942    21.01828
## 9      0.3605408 0.05998472     1.960202  0.2601621  0.4994549    26.08696
## 10     0.3605408 0.05998472     1.960202  0.2601621  0.4994549    26.08696
## 11     0.4006009 0.06321673     1.960202  0.2939655  0.5457064    28.98551
## 12     0.2603906 0.05100282     1.960202  0.1773397  0.3821865    18.84058
##       se_row t_crit_row  lcl_row  ucl_row
## 1  0.5473707   1.960202 45.92799 48.07358
## 2  0.5025506   1.960202 29.01822 30.98824
## 3  0.3432094   1.960202 10.34925 11.69521
## 4  0.3564220   1.960202 11.32112 12.71881
## 5  1.0412961   1.960202 19.04975 23.13209
## 6  1.2339820   1.960202 34.62587 39.46012
## 7  1.0401075   1.960202 18.98696 23.06466
## 8  1.0412961   1.960202 19.04975 23.13209
## 9  3.7515606   1.960202 19.42163 34.07250
## 10 3.7515606   1.960202 19.42163 34.07250
## 11 3.8761776   1.960202 22.00774 37.12261
## 12 3.3408449   1.960202 13.13952 26.26721</code></pre>
<p>Above, we have the results of several different descriptive analyses we did in R. Remember that we never want to present raw R output. Perhaps you’ve already thought to yourself, “wow, these results are really overwhelming. I’m not sure what I’m even looking at.” Well, that’s exactly how many of the people in your audience will feel as well. In its current form, this information is really hard for us to process. We want to take some of the information from the output above and use it to create a Table 1 in Word that is much easier to read.</p>
<p>Specifically, we want our final Table 1 to look like this:</p>
<p><img src="img/04_part_presenting_results/03_creating_word_tables/table1.png" /><!-- --></p>
<p>You may also <a href="https://www.dropbox.com/s/bu8r81jhzr2r3cj/final_table_01.docx?dl=0">click here to view/download the Word file that contains the Table 1</a>.</p>
<p>Now that you’ve seen the end result, let’s learn how to make this Table 1 together, step-by-step. Go ahead and open Microsoft Word now if you want to follow along.</p>
</div>
<div id="table-columns" class="section level2" number="18.3">
<h2><span class="header-section-number">18.3</span> Table columns</h2>
<p>The first thing I typically do is figure out how many columns and rows my table will need. This is generally pretty straightforward; although, there are exceptions. For a basic Table 1 like the one we are creating above we need the following columns:</p>
<p>One column for our row headers (i.e., the names and categories of the variables we are presenting in our analysis).</p>
<p><img src="img/04_part_presenting_results/03_creating_word_tables/row_header.png" /><!-- --></p>
<p>One column for each subgroup that we will be describing in our table. In this case, there are 3 subgroups so we will need 3 additional columns.</p>
<p><img src="img/04_part_presenting_results/03_creating_word_tables/subgroups.png" /><!-- --></p>
<p>So, we will need 4 total columns.</p>
<p class="note">
🗒<strong>Side Note:</strong> If you are going to describe the entire sample overall without stratifying it into subgroups then you would simply have 2 columns. One for the row headers and one for the values.
</p>
</div>
<div id="table-rows" class="section level2" number="18.4">
<h2><span class="header-section-number">18.4</span> Table rows</h2>
<p>Next, we need to figure out how many rows our table will need. This is also pretty straightforward. Generally, we will need the following rows:</p>
<p>One row for the title. Some people write their table titles outside (above or below) the actual table. I like to include the title directly in the top row of the table. That way, it moves with the table if the table gets moved around.</p>
<p><img src="img/04_part_presenting_results/03_creating_word_tables/title.png" /><!-- --></p>
<p>One row for the column headers. The column headers generally include a label like “Characteristic” for the row headers column and a descriptive label for each subgroup we are describing in our table.</p>
<p><img src="img/04_part_presenting_results/03_creating_word_tables/column_header.png" /><!-- --></p>
<p>One row for each variable we will analyze in our analysis. In this example, we have three – age, sex, and education. <strong>NOTE</strong> that we do <em>NOT</em> need a separate row for each category of each variable.</p>
<p><img src="img/04_part_presenting_results/03_creating_word_tables/variables.png" /><!-- --></p>
<p>One row for the footer.</p>
<p><img src="img/04_part_presenting_results/03_creating_word_tables/footer.png" /><!-- --></p>
<p>So, we will need 6 total rows.</p>
</div>
<div id="make-the-table-skeleton" class="section level2" number="18.5">
<h2><span class="header-section-number">18.5</span> Make the table skeleton</h2>
<p>Now that we know we need to create a table with 4 columns and 6 rows, lets go ahead and do that in Microsoft Word. We do so by clicking the <code>Insert</code> tab in the ribbon above our document. Then, we click the <code>Table</code> button and select the number of columns and rows we want.</p>
<p><img src="img/04_part_presenting_results/03_creating_word_tables/make_table.gif" /><!-- --></p>
</div>
<div id="fill-in-column-headers" class="section level2" number="18.6">
<h2><span class="header-section-number">18.6</span> Fill in column headers</h2>
<p>Now we have our table skeleton. The next thing I would typically do is fill in the column headers. Remember that our column headers look like this:</p>
<p><img src="img/04_part_presenting_results/03_creating_word_tables/column_header.png" /><!-- --></p>
<p>Here are a couple of suggestions for filling in your column headers:</p>
<ul>
<li><p>Put your column headers in the second row of the empty table shell. The title will eventually go into the first row. I don’t add the title right away because it is typically long and will distort the table’s dimensions. Later, we will see how to horizontally merge table cells to remove this distortion, but we don’t want to do that now. Right now, we want to leave all the cells unmerged so that we can easily resize our columns.</p></li>
<li><p>The first column header is generally a label for our row headers. Because the rows are typically characteristics of our sample, I almost always use the word “characteristic” here. If you come up with a better word, please feel free to use it.</p></li>
<li><p>The rest of the column headers are generally devoted to the subgroups we are describing.</p>
<ul>
<li><p>The subgroups should be ordered in a way that is meaningful. For example, by level of severity or chronological order. Typically, ordering in alphabetical order isn’t that meaningful.</p></li>
<li><p>The subgroup labels should be informative and meaningful, but also succinct. This can sometimes be a challenge.</p></li>
<li><p>I have seen terms like “Value”, “All”, and “Full Sample” used when Table 1 was describing the entire sample overall rather than describing the sample by subgroups.</p></li>
</ul></li>
</ul>
<div id="group-sample-sizes" class="section level3" number="18.6.1">
<h3><span class="header-section-number">18.6.1</span> Group sample sizes</h3>
<p>You should always include the group sample size in the column header. They should typically be in the format “(n = sample size)” and typed in the same cell as the label, but below the label (i.e., hit the return key). The group sample sizes can often provide important context to the statistics listed below in the table, and clue the reader into missing data issues.</p>
<p><img src="img/04_part_presenting_results/03_creating_word_tables/sample_size.png" /><!-- --></p>
</div>
<div id="formatting-column-headers" class="section level3" number="18.6.2">
<h3><span class="header-section-number">18.6.2</span> Formatting column headers</h3>
<p>I generally bold my column headers, horizontally center them, and vertically align them to the bottom of the row.</p>
<p>At this point, your table should look like this in Microsoft Word:</p>
<p><img src="img/04_part_presenting_results/03_creating_word_tables/make_column_headers.png" /><!-- --></p>
</div>
</div>
<div id="fill-in-row-headers" class="section level2" number="18.7">
<h2><span class="header-section-number">18.7</span> Fill in row headers</h2>
<p>The next thing I would typically do is fill in the row headers. Remember, that our row headers look like this:</p>
<p><img src="img/04_part_presenting_results/03_creating_word_tables/row_header.png" /><!-- --></p>
<p>Here are a couple of suggestions for filling in your row headers:</p>
<ul>
<li><p>The variables should be organized in a way that is meaningful. In our example, we have only 3 sociodemographic variables. However, if we also had some variables about health status and some variables related to criminal history, then we would almost certainly want the variables that fit into each of these categories to be vertically arranged next to each other.</p></li>
<li><p>Like the column headers, the row headers should be informative and meaningful, but also succinct. Again, this can sometimes be a challenge. In our example, we use “Age”, “Sex”, and “Education”. Something like “Highest level of formal education completed” would have also been informative and meaningful, but not succinct. Something like “Question 6” is succinct, but isn’t informative or meaningful at all.</p></li>
</ul>
<div id="label-statistics" class="section level3" number="18.7.1">
<h3><span class="header-section-number">18.7.1</span> Label statistics</h3>
<p>You should always tell the reader what kind statistics they are looking at – don’t assume that they know. For example, the highlighted number in figure <a href="creating-tables-with-r-and-microsoft-word.html#fig:what-stats">18.1</a> are 36.8 and 10. What is 36.8? The mean, the median? The percentage of people who had a non-missing value for age? What is 10? The sample size? The standard error of the mean? An odds ratio? You know that 36.8 is a mean and 10 is the standard deviation because I identified what they were in row header. <a href="creating-tables-with-r-and-microsoft-word.html#fig:identify-stats">18.2</a> When you label the statistics in the row headers as we’ve done in our example, they should take the format you see in figure <a href="creating-tables-with-r-and-microsoft-word.html#fig:identify-stats">18.2</a>. That is, the variable name, followed by a comma, followed by the statistics used in that row. Also notice the use of parentheses. We used parentheses around the letters “sd” (for standard deviation) because the numbers inside the parentheses in that row are standard deviations. So, the label used to identify the statistics should give the reader a blueprint for interpreting the statistics that matches the format of the statistics themselves.</p>
<div class="figure"><span id="fig:what-stats"></span>
<img src="img/04_part_presenting_results/03_creating_word_tables/what_stats.png" alt="What are these numbers."  />
<p class="caption">
Figure 18.1: What are these numbers.
</p>
</div>
<div class="figure"><span id="fig:identify-stats"></span>
<img src="img/04_part_presenting_results/03_creating_word_tables/identify_stats.png" alt="Identifying statistics in the row header."  />
<p class="caption">
Figure 18.2: Identifying statistics in the row header.
</p>
</div>
<p>The statistics can, and sometimes are, labeled in the column header instead of the row header. This can sometimes be a great idea. However, it can also be a source of confusion. For example, in the figure below, the column headers include labels (i.e., n (%)) for the statistics below. However, <em>not all the statistics below are counts (n) and percentages</em>!</p>
<p><img src="img/04_part_presenting_results/03_creating_word_tables/bad_stat_labels.png" /><!-- --></p>
<p>Even though the Age variable has it’s own separate statistics label in the row header, this is still generally a really bad idea! Therefore, I highly recommend only labeling your statistics in the column header when those labels are accurate for <em>every</em> value in the column. For example:</p>
<p><img src="img/04_part_presenting_results/03_creating_word_tables/good_stat_labels.png" /><!-- --></p>
</div>
<div id="formatting-row-headers" class="section level3" number="18.7.2">
<h3><span class="header-section-number">18.7.2</span> Formatting row headers</h3>
<ul>
<li><p>Whenever possible, make sure that variable name and statistic identifier fit on one line (i.e., they don’t carryover into the line below).</p></li>
<li><p>Always type the category labels for categorical variables in the same cell as the variable name. However, each category should have it’s own line (i.e., hit the return key).</p></li>
<li><p>Whenever possible, make sure that each category label fits on one line (i.e., it doesn’t carryover into the line below).</p></li>
<li><p>Indent each category label two spaces to the left of the variable name.</p></li>
<li><p>Hit the return key once after the last category for each categorical variable. This creates a blank line that adds vertical separation between row headers and makes them easier to read.</p></li>
</ul>
<p>At this point, your table should look like this in Microsoft Word:</p>
<p><img src="img/04_part_presenting_results/03_creating_word_tables/make_row_headers.png" /><!-- --></p>
</div>
</div>
<div id="fill-in-data-values" class="section level2" number="18.8">
<h2><span class="header-section-number">18.8</span> Fill in data values</h2>
<p>So, we have some statistics visible to us on the screen in RStudio. Somehow, we have to get those numbers over to our table in Microsoft Word. There are many different ways we can do this. I’m going to compare a few of those ways here.</p>
<div id="manually-type-values" class="section level3" number="18.8.1">
<h3><span class="header-section-number">18.8.1</span> Manually type values</h3>
<p>One option is to manually type the numbers into your word document.</p>
<p>👍 If you are in a hurry, or if you just need to update a small handful of statistics in your table, then this option is super straightforward. However, there are at least two big problems with this method.</p>
<p>👎 First, it is <em>extremely</em> error prone. Most people are very likely to type a wrong number or misplace a decimal here and there when they manually type statistics into their Word tables.</p>
<p>👎 Second, it isn’t very scalable. What if you need to make very large tables with lots and lots of numbers? What if you update your data set and need to change every number in your Word table? This is not fun to do manually.</p>
</div>
<div id="copy-and-paste-values" class="section level3" number="18.8.2">
<h3><span class="header-section-number">18.8.2</span> Copy and paste values</h3>
<p>Anther option is to copy and paste values from RStudio into Word. This option is similar to above, but instead of <em>typing</em> each value into your Word table, you highlight and copy the value in RStudio and <em>paste</em> it into Word.</p>
<p>👍 If you are in a hurry, or if you just need to update a small handful of statistics in your table, then this option is also pretty straightforward. However, there are still issues associated with this method.</p>
<p>👎 First, it is still somewhat error prone. It’s true that the numbers and decimal placements should always be correct when you copy and paste; however, you may be surprised by how often many people accidently paste the values into the wrong place or in the wrong order.</p>
<p>👎 Second, I’ve noticed that there are often weird formatting things that happen when I copy from RStudio and paste into Word. They are usually pretty easy to fix, but this is still a small bit of extra hassle.</p>
<p>👎 Third, it isn’t very scalable. Again, if we need to make very large tables with lots and lots of numbers or update our data set and need to change every number in your Word table, this method is time-consuming and tedious.</p>
</div>
<div id="knit-a-word-document" class="section level3" number="18.8.3">
<h3><span class="header-section-number">18.8.3</span> Knit a Word document</h3>
<p>So far, we have only used the HTML Notebook output type for our R markdown files. However, it’s actually very easy have <a href="https://rmarkdown.rstudio.com/lesson-9.html">RStudio create a Word document from you R markdown files</a>. We don’t have all the R knowledge we need to fully implement this method yet, so I don’t want to confuse you by going into the details here. But, I do want to mention that it is possible.</p>
<p>👍 The main advantages of this method are that it is much less error prone and much more scalable than manually typing or copying and pasting values.</p>
<p>👎 The main disadvantages are that it requires more work on the front end and still requires you to open Microsoft Word a do a good deal of formatting of the table(s).</p>
</div>
<div id="flextable-and-officer" class="section level3" number="18.8.4">
<h3><span class="header-section-number">18.8.4</span> flextable and officer</h3>
<p>A final option I’ll mention is to create your table with the <a href="https://davidgohel.github.io/flextable/index.html">flextable</a> and <a href="https://davidgohel.github.io/officer/">officer</a> packages. This is my favorite option, but it is also definitely the most complicated. Again, I’m not going to go into the details here because they would likely just be confusing for most readers.</p>
<p>👍 This method essentially overcomes all of the previous methods’ limitations. It is the least error prone, it is extremely scalable, and it allows us to do basically all the formatting in R. With a push of a button we have a complete, perfectly formatted table output to a Word document. If we update our data, we just push the button again and we have a new perfectly formatted table.</p>
<p>👎 The primary downside is that this method requires you to invest some time in learning these packages, and requires the greatest amount of writing code up front. If you just need to create a single small table that you will never update, this method is probably not worth the effort. However, if you absolutely need to make sure that your table has no errors, or if you will need to update your table on a regular basis, then this method is definitely worth learning.</p>
</div>
<div id="significant-digits" class="section level3" number="18.8.5">
<h3><span class="header-section-number">18.8.5</span> Significant digits</h3>
<p>No matter which of the methods above you choose, you will almost never want to give your reader the level of precision that R will give you. For example, the first row of the R results below indicates that 83.274912% of our sample reported that they don’t use drugs.</p>
<pre><code>##     var              cat    n n_total   percent        se   t_crit      lcl
## 1 use_f        Non-users 8315    9985 83.274912 0.3734986 1.960202 82.52992
## 2 use_f  Use other drugs 1532    9985 15.343015 0.3606903 1.960202 14.64925
## 3 use_f Use opioid drugs  138    9985  1.382073 0.1168399 1.960202  1.17080
##         ucl
## 1 83.994296
## 2 16.063453
## 3  1.630841</code></pre>
<p>Notice the level of precision there. R gives us the percentage out to 6 decimal places. If you fill your table with numbers like this, it will be much harder for your readers to digest your table and make comparisons between groups. It’s just the way our brains work. So, the logical next question is, “how many decimal places should I report?” Unfortunately, this is another one of those times that I have to give you an answer that may be a little unsatisfying. It is true that there are rules for <a href="https://en.wikipedia.org/wiki/Significant_figures">significant figures (significant digits)</a>; however, the rules are not always helpful to students in my experience. Therefore, I’m going to share with you a few things I try to consider when deciding how many digits to present.</p>
<ul>
<li><p>I don’t recall <em>ever</em> presenting a level of precision greater than 3 decimal places in the research I’ve been involved with. If you are working in physics or genetics and measuring really tiny things it may be totally valid to report 6, 8, or 10 digits to the right of the decimal. But, in epidemiology – a population science – this is rarely, if ever, useful.</p></li>
<li><p>What is the overall message I am trying to communicate? That is the point of the table, right? I’m trying to clearly and honestly communicate information to my reader. In general, the simpler the numbers are to read and compare, the clearer the communication. So, I tend to error on the side of simplifying as much as possible. For example, in the R results below, we could say that 83.274912% of our sample reported that they don’t use drugs, 15.343015% reported that they use drugs other than opioids, and 1.382073% reported that they use opioid drugs. Is saying it that way really more useful than saying that “83% of our sample reported that they don’t use drugs, 15% reported that they use drugs other than opioids, and 1% reported that they use opioid drugs”? Are we missing any actionable information by rounding our percentages to the nearest integer here? Are our overall conclusions about drug use any different? No, probably not. And, the rounded percentages are much easier to read, compare, and remember.</p></li>
<li><p>Be consistent – especially within a single table. I have experienced some rare occasions where it made sense to round one variable to 1 decimal place and another variable to 3 decimals places in the same table. But, circumstances like this are definitely the exception. Generally speaking, if you round one variable to 1 decimal place then you want to round them all to one decimal place.</p></li>
</ul>
<p>Like all other calculations we’ve done in this book, I suggest you let R do the heavy lifting when it comes to rounding. In other words, have R round the values for you <em>before</em> you move them to Word. R is much less likely to make a rounding error than your are! You may recall that we learned how to round in the <a href="numerical-descriptions-of-categorical-variables.html#formatting-results">chapter on numerical descriptions of categorical variables</a>.</p>
</div>
<div id="formatting-data-values" class="section level3" number="18.8.6">
<h3><span class="header-section-number">18.8.6</span> Formatting data values</h3>
<p>Now that we have our appropriately rounded values in our table, we just need to do a little formatting before we move on.</p>
<p>First, make sure to fix any fonts, font sizes, and/or background colors that may have been changed if you copied and pasted the values from RStudio into Word.</p>
<p>Second, make sure the values line up horizontally with the correct variable names and category labels.</p>
<p>Third, I tend to horizontally center all my values in their columns.</p>
<p>At this point, your table should look like this in Microsoft Word:</p>
<p><img src="img/04_part_presenting_results/03_creating_word_tables/make_data_values.png" /><!-- --></p>
</div>
</div>
<div id="fill-in-title" class="section level2" number="18.9">
<h2><span class="header-section-number">18.9</span> Fill in title</h2>
<p>At this point in the process, I will typically go ahead and add the title to the first cell of my Word table. The title should always start with “Table #.” In our case, it will start with “Table 1.” In general, I use bold text for this part of the title. What comes next will change a little bit from table to table but is extremely important and worth putting some thought into.</p>
<p>Remember, all tables and figures need to be able to <em>stand on their own</em>. What does that mean? It means that if I pick up your report and flip straight to the table, I should be able to understand what it’s about and how to read it without reading any of the other text in your report. The title is a critical part of making a table stand on its own. In general, your title should tell the reader what the table contains (e.g., sociodemographic characteristics) and who the table is about (e.g., results of the Texas Opioid Study). I will usually also add the size of the sample of people included in the table (e.g., n = 9985) and the year the data was collected (e.g., 2020).</p>
<p>In different circumstances, more or less information may be needed. However, always ask yourself, “can this table stand on its own? Can most readers understand what’s going on in this table even if they didn’t read the full report?”</p>
<p>At this point, your table should look like this in Microsoft Word:</p>
<p><img src="img/04_part_presenting_results/03_creating_word_tables/make_title.png" /><!-- --></p>
<p>Don’t worry about your title being all bunched up in the corner. We will fix it soon.</p>
</div>
<div id="fill-in-footnotes" class="section level2" number="18.10">
<h2><span class="header-section-number">18.10</span> Fill in footnotes</h2>
<p>Footnotes are another tool we can use to help our table stand on its own. The footnotes give readers additional information that they may need to read and understand our table. Again, there are few hard and fast rules regarding what footnotes you should include, but I can give you some general categories of things to think about.</p>
<p>First, use footnotes to explain any abbreviations in your table that aren’t standard and broadly understood. These abbreviations are typically related to statistics used in the table (e.g., RR = risk ratio) and/or units of measure (e.g., mmHg = millimeters of mercury). Admittedly, there is some subjectivity associated with “standard and broadly understood.” In our example, I did not provide a footnote for “n”, “sd”, or “%” because most researchers would agree that these abbreviations are standard and broadly understood, but I typically do provide footnotes for statistics like “OR” (odds ration) and “RR” (relative risk or risk ratio).</p>
<p>Additionally, I mentioned above that it is desirable, but sometimes challenging, to get your variable names and category labels to fit on a single line. Footnotes can sometimes help with this. In our example, instead of writing “Age in years, mean (sd)” as a row header I wrote “Age, mean (sd)” and added a footnote that tells the reader that age is measured in years. This may not be the best possible example, but hopefully you get the idea.</p>
<div id="formatting-footnotes" class="section level3" number="18.10.1">
<h3><span class="header-section-number">18.10.1</span> Formatting footnotes</h3>
<p>When using footnotes, you need to somehow let the reader know which element in the table each footnote goes with. Sometimes, there will be guidelines that require you to use certain symbols (e.g., *, †, and ‡), but I typically use numbers to match table elements to footnotes when I can. In the example below, there is a superscript “1” immediately after the word “Age” that lets the reader know that footnote number 1 is adding additional information to this part of the table.</p>
<p><img src="img/04_part_presenting_results/03_creating_word_tables/number_footnotes.png" /><!-- --></p>
<p>If you do use numbers to match table elements to footnotes, make sure you do so in the order people read [English], which is left to right and top to bottom. For example, the following would be inappropriate because the number 2 comes before the number 1 when reading from top to bottom:</p>
<p><img src="img/04_part_presenting_results/03_creating_word_tables/bad_footnote_1.png" /><!-- --></p>
<p>As another example, the following would be inappropriate because the number 2 comes before the number 1 when reading from left to right:</p>
<p><img src="img/04_part_presenting_results/03_creating_word_tables/bad_footnote_2.png" /><!-- --></p>
<p>Additionally, when using numbers to match table elements to footnotes, it’s a good idea to superscript the numbers in the table. This makes it clear that the number is being used to identify a footnote rather than being part of the text or abbreviation. Formatting a number as a superscript is easy in Microsoft Word. Just highlight the number you want to format and click the superscript button like so:</p>
<p><img src="img/04_part_presenting_results/03_creating_word_tables/make_footnotes.gif" /><!-- --></p>
<p>At this point, your table should look like this in Microsoft Word:</p>
<p><img src="img/04_part_presenting_results/03_creating_word_tables/make_footnotes.png" /><!-- --></p>
</div>
</div>
<div id="final-formatting" class="section level2" number="18.11">
<h2><span class="header-section-number">18.11</span> Final formatting</h2>
<p>We have all of our data and explanatory text in our table. The last few remaining steps are just about formatting our table to make it as easy to read and digest as possible.</p>
<div id="adjust-column-widths" class="section level3" number="18.11.1">
<h3><span class="header-section-number">18.11.1</span> Adjust column widths</h3>
<p>As I’ve already mentioned more than once, we don’t want our text carryover onto multiple lines whenever we can help it. In my experience, this occurs most often in the row headings. Therefore, I will often need to adjust (widen) the first column of my table. You can do that by clicking on the black border that separates the columns and moving your mouse left or right.</p>
<p><img src="img/04_part_presenting_results/03_creating_word_tables/adjust_columns.gif" /><!-- --></p>
<p>After you adjust the width of your first column, the widths of the remaining columns will likely be uneven. To distribute the remaining space in the table evenly among the remaining columns, first select the columns by clicking immediately above the first column you want to select and dragging your cursor across the remaining columns. Then, click the <code>layout</code> tab in ribbon above your document and the <code>Distribute Columns</code> button.</p>
<p><img src="img/04_part_presenting_results/03_creating_word_tables/even_columns.gif" /><!-- --></p>
<p>In our particular example, there was no need to adjust column widths because all of our text fit into the default widths.</p>
</div>
<div id="merge-cells" class="section level3" number="18.11.2">
<h3><span class="header-section-number">18.11.2</span> Merge cells</h3>
<p>Now, we can finally merge some cells so that our title and footnote spread the entire width of the table. We waited until now to merge cells because if we had done so earlier it would have made the previous step (i.e., adjust column widths) more difficult.</p>
<p>To spread our title out across the entire width of the table, we just need to will select all the cells in the first row, then right click and select <code>merge cells</code>.</p>
<p><img src="img/04_part_presenting_results/03_creating_word_tables/merge_title.gif" /><!-- --></p>
<p>After merging the footnote cells in exactly the same way, your table should look like this:</p>
<p><img src="img/04_part_presenting_results/03_creating_word_tables/make_merged.png" /><!-- --></p>
</div>
<div id="remove-cell-borders" class="section level3" number="18.11.3">
<h3><span class="header-section-number">18.11.3</span> Remove cell borders</h3>
<p>The final step is to clean up our borders. In my experience, students like to do all kinds of creative things with cell borders. However, when it comes to borders, keeping it simple is usually the best approach. Therefore, we will start by removing <em>all</em> borders in the table. We do so by clicking the little cross with arrowheads that pops up diagonal to the top-left corner of the table when you move your mouse over it. Clicking this button will highlight your entire table. Then, we will click the downward facing arrow next to the <code>borders</code> button in the ribbon above your document. Then, we will click the <code>No Border</code> option.</p>
<p><img src="img/04_part_presenting_results/03_creating_word_tables/remove_borders.gif" /><!-- --></p>
<p>Our final step will be to add a single horizontal border under the title, as single horizontal border under the column header row, and a single horizontal border above the footnotes. We will add the borders by highlighting the correct rows and selecting the correct options for the same <code>borders</code> dropdown menu we used above.</p>
<p><img src="img/04_part_presenting_results/03_creating_word_tables/make_borders.gif" /><!-- --></p>
<p>Notice that there are <em>no vertical lines (borders) anywhere on our table</em>. That should almost always be the case for your tables too.</p>
</div>
</div>
<div id="summary-1" class="section level2" number="18.12">
<h2><span class="header-section-number">18.12</span> Summary</h2>
<p>Just like with guidelines we’ve discussed about R coding style; you don’t have to create tables in exactly the same way that I do. But, you should have a good reason for all the decisions you make leading up to the finished table, and you should apply those decisions consistently across all your tables within a given project or report. Having said that, in the absence of needing to adhere to specific guidelines that conflict with the table we’ve created above, this is the general template I would ask someone working on my team to use when creating a table for a report or presentation.</p>

</div>
</div>




</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-Matthews2014-ah">
<p>6. Matthews JR, Matthews RW. <em>Successful Scientific Writing: A Step-by-Step Guide for the Biological and Medical Sciences</em>. Cambridge University Press; 2014.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="describing-the-relationship-between-a-categorical-outcome-and-a-categorical-predictor.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="appendix-a-glossary.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
