<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>43 Measures of Occurrence | R for Epidemiology</title>
  <meta name="description" content="This is the textbook for Brad Cannell’s Introduction to R Programming for Epidemiologic Research course." />
  <meta name="generator" content="bookdown 0.27 and GitBook 2.6.7" />

  <meta property="og:title" content="43 Measures of Occurrence | R for Epidemiology" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="https://brad-cannell.github.io/r4epi/r4epi_icon.png" />
  <meta property="og:description" content="This is the textbook for Brad Cannell’s Introduction to R Programming for Epidemiologic Research course." />
  <meta name="github-repo" content="brad-cannell/r4epi" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="43 Measures of Occurrence | R for Epidemiology" />
  
  <meta name="twitter:description" content="This is the textbook for Brad Cannell’s Introduction to R Programming for Epidemiologic Research course." />
  <meta name="twitter:image" content="https://brad-cannell.github.io/r4epi/r4epi_icon.png" />

<meta name="author" content="Brad Cannell" />


<meta name="date" content="2023-09-15" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="populations.html"/>
<link rel="next" href="appendix-a-glossary.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.23/datatables.js"></script>
<link href="libs/dt-core-1.11.3/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.11.3/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.11.3/js/jquery.dataTables.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-0RREBTQ0D9"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-0RREBTQ0D9');
</script>
<!-- R4Epi Favicons -->
<!-- https://bookdown.org/yihui/rmarkdown-cookbook/favicon.html -->
<!-- Also using Favicon Generator (https://realfavicongenerator.net) -->
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R for Epidemiology</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i>Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#goals"><i class="fa fa-check"></i>Goals</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#text-conventions-used-in-this-book"><i class="fa fa-check"></i>Text conventions used in this book</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#other-reading"><i class="fa fa-check"></i>Other reading</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#contributing-to-r4epi"><i class="fa fa-check"></i>Contributing to R4Epi</a>
<ul>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#typos"><i class="fa fa-check"></i>Typos</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#issues"><i class="fa fa-check"></i>Issues</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html"><i class="fa fa-check"></i>About the Authors</a>
<ul>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html#brad-cannell"><i class="fa fa-check"></i>Brad Cannell</a></li>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html#melvin-livingston"><i class="fa fa-check"></i>Melvin Livingston</a></li>
</ul></li>
<li class="part"><span><b>I Getting Started</b></span></li>
<li class="chapter" data-level="1" data-path="installing-r-and-rstudio.html"><a href="installing-r-and-rstudio.html"><i class="fa fa-check"></i><b>1</b> Installing R and RStudio</a>
<ul>
<li class="chapter" data-level="1.1" data-path="installing-r-and-rstudio.html"><a href="installing-r-and-rstudio.html#download-and-install-on-a-mac"><i class="fa fa-check"></i><b>1.1</b> Download and install on a Mac</a></li>
<li class="chapter" data-level="1.2" data-path="installing-r-and-rstudio.html"><a href="installing-r-and-rstudio.html#download-and-install-on-a-pc"><i class="fa fa-check"></i><b>1.2</b> Download and install on a PC</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="what-is-r.html"><a href="what-is-r.html"><i class="fa fa-check"></i><b>2</b> What is R?</a>
<ul>
<li class="chapter" data-level="2.1" data-path="what-is-r.html"><a href="what-is-r.html#what-is-data"><i class="fa fa-check"></i><b>2.1</b> What is data?</a></li>
<li class="chapter" data-level="2.2" data-path="what-is-r.html"><a href="what-is-r.html#what-is-r-1"><i class="fa fa-check"></i><b>2.2</b> What is R?</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="what-is-r.html"><a href="what-is-r.html#transferring-data"><i class="fa fa-check"></i><b>2.2.1</b> Transferring data</a></li>
<li class="chapter" data-level="2.2.2" data-path="what-is-r.html"><a href="what-is-r.html#managing-data"><i class="fa fa-check"></i><b>2.2.2</b> Managing data</a></li>
<li class="chapter" data-level="2.2.3" data-path="what-is-r.html"><a href="what-is-r.html#analyzing-data"><i class="fa fa-check"></i><b>2.2.3</b> Analyzing data</a></li>
<li class="chapter" data-level="2.2.4" data-path="what-is-r.html"><a href="what-is-r.html#presenting-data"><i class="fa fa-check"></i><b>2.2.4</b> Presenting data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="navigating-the-rstudio-interface.html"><a href="navigating-the-rstudio-interface.html"><i class="fa fa-check"></i><b>3</b> Navigating the RStudio Interface</a>
<ul>
<li class="chapter" data-level="3.1" data-path="navigating-the-rstudio-interface.html"><a href="navigating-the-rstudio-interface.html#the-console"><i class="fa fa-check"></i><b>3.1</b> The console</a></li>
<li class="chapter" data-level="3.2" data-path="navigating-the-rstudio-interface.html"><a href="navigating-the-rstudio-interface.html#the-environment-pane"><i class="fa fa-check"></i><b>3.2</b> The environment pane</a></li>
<li class="chapter" data-level="3.3" data-path="navigating-the-rstudio-interface.html"><a href="navigating-the-rstudio-interface.html#the-files-pane"><i class="fa fa-check"></i><b>3.3</b> The files pane</a></li>
<li class="chapter" data-level="3.4" data-path="navigating-the-rstudio-interface.html"><a href="navigating-the-rstudio-interface.html#the-source-pane"><i class="fa fa-check"></i><b>3.4</b> The source pane</a></li>
<li class="chapter" data-level="3.5" data-path="navigating-the-rstudio-interface.html"><a href="navigating-the-rstudio-interface.html#rstudio-preferences"><i class="fa fa-check"></i><b>3.5</b> RStudio preferences</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="speaking-rs-language.html"><a href="speaking-rs-language.html"><i class="fa fa-check"></i><b>4</b> Speaking R’s Language</a>
<ul>
<li class="chapter" data-level="4.1" data-path="speaking-rs-language.html"><a href="speaking-rs-language.html#r-is-a-language"><i class="fa fa-check"></i><b>4.1</b> R is a <em>language</em></a></li>
<li class="chapter" data-level="4.2" data-path="speaking-rs-language.html"><a href="speaking-rs-language.html#the-r-interpreter"><i class="fa fa-check"></i><b>4.2</b> The R interpreter</a></li>
<li class="chapter" data-level="4.3" data-path="speaking-rs-language.html"><a href="speaking-rs-language.html#errors"><i class="fa fa-check"></i><b>4.3</b> Errors</a></li>
<li class="chapter" data-level="4.4" data-path="speaking-rs-language.html"><a href="speaking-rs-language.html#functions"><i class="fa fa-check"></i><b>4.4</b> Functions</a></li>
<li class="chapter" data-level="4.5" data-path="speaking-rs-language.html"><a href="speaking-rs-language.html#objects"><i class="fa fa-check"></i><b>4.5</b> Objects</a></li>
<li class="chapter" data-level="4.6" data-path="speaking-rs-language.html"><a href="speaking-rs-language.html#comments"><i class="fa fa-check"></i><b>4.6</b> Comments</a></li>
<li class="chapter" data-level="4.7" data-path="speaking-rs-language.html"><a href="speaking-rs-language.html#packages"><i class="fa fa-check"></i><b>4.7</b> Packages</a></li>
<li class="chapter" data-level="4.8" data-path="speaking-rs-language.html"><a href="speaking-rs-language.html#programming-style"><i class="fa fa-check"></i><b>4.8</b> Programming style</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="lets-get-programming.html"><a href="lets-get-programming.html"><i class="fa fa-check"></i><b>5</b> Let’s Get Programming</a>
<ul>
<li class="chapter" data-level="5.1" data-path="lets-get-programming.html"><a href="lets-get-programming.html#simulating-data"><i class="fa fa-check"></i><b>5.1</b> Simulating data</a></li>
<li class="chapter" data-level="5.2" data-path="lets-get-programming.html"><a href="lets-get-programming.html#vectors"><i class="fa fa-check"></i><b>5.2</b> Vectors</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="lets-get-programming.html"><a href="lets-get-programming.html#vector-types"><i class="fa fa-check"></i><b>5.2.1</b> Vector types</a></li>
<li class="chapter" data-level="5.2.2" data-path="lets-get-programming.html"><a href="lets-get-programming.html#double-vectors"><i class="fa fa-check"></i><b>5.2.2</b> Double vectors</a></li>
<li class="chapter" data-level="5.2.3" data-path="lets-get-programming.html"><a href="lets-get-programming.html#integer-vectors"><i class="fa fa-check"></i><b>5.2.3</b> Integer vectors</a></li>
<li class="chapter" data-level="5.2.4" data-path="lets-get-programming.html"><a href="lets-get-programming.html#logical-vectors"><i class="fa fa-check"></i><b>5.2.4</b> Logical vectors</a></li>
<li class="chapter" data-level="5.2.5" data-path="lets-get-programming.html"><a href="lets-get-programming.html#factor-vectors"><i class="fa fa-check"></i><b>5.2.5</b> Factor vectors</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="lets-get-programming.html"><a href="lets-get-programming.html#data-frames"><i class="fa fa-check"></i><b>5.3</b> Data frames</a></li>
<li class="chapter" data-level="5.4" data-path="lets-get-programming.html"><a href="lets-get-programming.html#tibbles"><i class="fa fa-check"></i><b>5.4</b> Tibbles</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="lets-get-programming.html"><a href="lets-get-programming.html#the-as_tibble-function"><i class="fa fa-check"></i><b>5.4.1</b> The as_tibble function</a></li>
<li class="chapter" data-level="5.4.2" data-path="lets-get-programming.html"><a href="lets-get-programming.html#the-tibble-function"><i class="fa fa-check"></i><b>5.4.2</b> The tibble function</a></li>
<li class="chapter" data-level="5.4.3" data-path="lets-get-programming.html"><a href="lets-get-programming.html#the-tribble-function"><i class="fa fa-check"></i><b>5.4.3</b> The tribble function</a></li>
<li class="chapter" data-level="5.4.4" data-path="lets-get-programming.html"><a href="lets-get-programming.html#why-use-tibbles"><i class="fa fa-check"></i><b>5.4.4</b> Why use tibbles</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="lets-get-programming.html"><a href="lets-get-programming.html#missing-data"><i class="fa fa-check"></i><b>5.5</b> Missing data</a></li>
<li class="chapter" data-level="5.6" data-path="lets-get-programming.html"><a href="lets-get-programming.html#our-first-analysis"><i class="fa fa-check"></i><b>5.6</b> Our first analysis</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="lets-get-programming.html"><a href="lets-get-programming.html#manual-calculation-of-the-mean"><i class="fa fa-check"></i><b>5.6.1</b> Manual calculation of the mean</a></li>
<li class="chapter" data-level="5.6.2" data-path="lets-get-programming.html"><a href="lets-get-programming.html#dollar-sign-notation"><i class="fa fa-check"></i><b>5.6.2</b> Dollar sign notation</a></li>
<li class="chapter" data-level="5.6.3" data-path="lets-get-programming.html"><a href="lets-get-programming.html#bracket-notation"><i class="fa fa-check"></i><b>5.6.3</b> Bracket notation</a></li>
<li class="chapter" data-level="5.6.4" data-path="lets-get-programming.html"><a href="lets-get-programming.html#the-sum-function"><i class="fa fa-check"></i><b>5.6.4</b> The sum function</a></li>
<li class="chapter" data-level="5.6.5" data-path="lets-get-programming.html"><a href="lets-get-programming.html#nesting-functions"><i class="fa fa-check"></i><b>5.6.5</b> Nesting functions</a></li>
<li class="chapter" data-level="5.6.6" data-path="lets-get-programming.html"><a href="lets-get-programming.html#the-length-function"><i class="fa fa-check"></i><b>5.6.6</b> The length function</a></li>
<li class="chapter" data-level="5.6.7" data-path="lets-get-programming.html"><a href="lets-get-programming.html#the-mean-function"><i class="fa fa-check"></i><b>5.6.7</b> The mean function</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="lets-get-programming.html"><a href="lets-get-programming.html#some-common-errors"><i class="fa fa-check"></i><b>5.7</b> Some common errors</a></li>
<li class="chapter" data-level="5.8" data-path="lets-get-programming.html"><a href="lets-get-programming.html#summary"><i class="fa fa-check"></i><b>5.8</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="asking-questions.html"><a href="asking-questions.html"><i class="fa fa-check"></i><b>6</b> Asking Questions</a>
<ul>
<li class="chapter" data-level="6.1" data-path="asking-questions.html"><a href="asking-questions.html#when-should-we-seek-help"><i class="fa fa-check"></i><b>6.1</b> When should we seek help?</a></li>
<li class="chapter" data-level="6.2" data-path="asking-questions.html"><a href="asking-questions.html#where-should-we-seek-help"><i class="fa fa-check"></i><b>6.2</b> Where should we seek help?</a></li>
<li class="chapter" data-level="6.3" data-path="asking-questions.html"><a href="asking-questions.html#how-should-we-seek-help"><i class="fa fa-check"></i><b>6.3</b> How should we seek help?</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="asking-questions.html"><a href="asking-questions.html#creating-a-post-on-stack-overflow"><i class="fa fa-check"></i><b>6.3.1</b> Creating a post on Stack Overflow</a></li>
<li class="chapter" data-level="6.3.2" data-path="asking-questions.html"><a href="asking-questions.html#creating-better-posts-and-asking-better-questions"><i class="fa fa-check"></i><b>6.3.2</b> Creating better posts and asking better questions</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="asking-questions.html"><a href="asking-questions.html#helping-others"><i class="fa fa-check"></i><b>6.4</b> Helping others</a></li>
<li class="chapter" data-level="6.5" data-path="asking-questions.html"><a href="asking-questions.html#summary-1"><i class="fa fa-check"></i><b>6.5</b> Summary</a></li>
</ul></li>
<li class="part"><span><b>II Coding Tools and Best Practices</b></span></li>
<li class="chapter" data-level="7" data-path="r-scripts.html"><a href="r-scripts.html"><i class="fa fa-check"></i><b>7</b> R Scripts</a>
<ul>
<li class="chapter" data-level="7.1" data-path="r-scripts.html"><a href="r-scripts.html#creating-r-scripts"><i class="fa fa-check"></i><b>7.1</b> Creating R scripts</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="quarto-files.html"><a href="quarto-files.html"><i class="fa fa-check"></i><b>8</b> Quarto Files</a>
<ul>
<li class="chapter" data-level="8.1" data-path="quarto-files.html"><a href="quarto-files.html#what-is-quarto"><i class="fa fa-check"></i><b>8.1</b> What is Quarto?</a></li>
<li class="chapter" data-level="8.2" data-path="quarto-files.html"><a href="quarto-files.html#why-use-quarto"><i class="fa fa-check"></i><b>8.2</b> Why use Quarto?</a></li>
<li class="chapter" data-level="8.3" data-path="quarto-files.html"><a href="quarto-files.html#create-a-quarto-file"><i class="fa fa-check"></i><b>8.3</b> Create a Quarto file</a></li>
<li class="chapter" data-level="8.4" data-path="quarto-files.html"><a href="quarto-files.html#yaml-headers"><i class="fa fa-check"></i><b>8.4</b> YAML headers</a></li>
<li class="chapter" data-level="8.5" data-path="quarto-files.html"><a href="quarto-files.html#r-code-chunks"><i class="fa fa-check"></i><b>8.5</b> R code chunks</a></li>
<li class="chapter" data-level="8.6" data-path="quarto-files.html"><a href="quarto-files.html#markdown"><i class="fa fa-check"></i><b>8.6</b> Markdown</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="quarto-files.html"><a href="quarto-files.html#markdown-headings"><i class="fa fa-check"></i><b>8.6.1</b> Markdown headings</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="quarto-files.html"><a href="quarto-files.html#summary-2"><i class="fa fa-check"></i><b>8.7</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="r-projects.html"><a href="r-projects.html"><i class="fa fa-check"></i><b>9</b> R Projects</a></li>
<li class="chapter" data-level="10" data-path="coding-best-practices.html"><a href="coding-best-practices.html"><i class="fa fa-check"></i><b>10</b> Coding Best Practices</a>
<ul>
<li class="chapter" data-level="10.1" data-path="coding-best-practices.html"><a href="coding-best-practices.html#general-principles"><i class="fa fa-check"></i><b>10.1</b> General principles</a></li>
<li class="chapter" data-level="10.2" data-path="coding-best-practices.html"><a href="coding-best-practices.html#code-comments"><i class="fa fa-check"></i><b>10.2</b> Code comments</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="coding-best-practices.html"><a href="coding-best-practices.html#defining-key-variables"><i class="fa fa-check"></i><b>10.2.1</b> Defining key variables</a></li>
<li class="chapter" data-level="10.2.2" data-path="coding-best-practices.html"><a href="coding-best-practices.html#what-this-code-is-trying-to-accomplish"><i class="fa fa-check"></i><b>10.2.2</b> What this code is trying to accomplish</a></li>
<li class="chapter" data-level="10.2.3" data-path="coding-best-practices.html"><a href="coding-best-practices.html#why-i-chose-this-particular-strategy"><i class="fa fa-check"></i><b>10.2.3</b> Why I chose this particular strategy</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="coding-best-practices.html"><a href="coding-best-practices.html#style-guidelines"><i class="fa fa-check"></i><b>10.3</b> Style guidelines</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="coding-best-practices.html"><a href="coding-best-practices.html#comments-1"><i class="fa fa-check"></i><b>10.3.1</b> Comments</a></li>
<li class="chapter" data-level="10.3.2" data-path="coding-best-practices.html"><a href="coding-best-practices.html#object-variable-names"><i class="fa fa-check"></i><b>10.3.2</b> Object (variable) names</a></li>
<li class="chapter" data-level="10.3.3" data-path="coding-best-practices.html"><a href="coding-best-practices.html#use-names-that-are-informative"><i class="fa fa-check"></i><b>10.3.3</b> Use names that are informative</a></li>
<li class="chapter" data-level="10.3.4" data-path="coding-best-practices.html"><a href="coding-best-practices.html#file-names"><i class="fa fa-check"></i><b>10.3.4</b> File Names</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="using-pipes.html"><a href="using-pipes.html"><i class="fa fa-check"></i><b>11</b> Using Pipes</a>
<ul>
<li class="chapter" data-level="11.1" data-path="using-pipes.html"><a href="using-pipes.html#what-are-pipes"><i class="fa fa-check"></i><b>11.1</b> What are pipes?</a></li>
<li class="chapter" data-level="11.2" data-path="using-pipes.html"><a href="using-pipes.html#how-do-pipes-work"><i class="fa fa-check"></i><b>11.2</b> How do pipes work?</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="using-pipes.html"><a href="using-pipes.html#keyboard-shortcut"><i class="fa fa-check"></i><b>11.2.1</b> Keyboard shortcut</a></li>
<li class="chapter" data-level="11.2.2" data-path="using-pipes.html"><a href="using-pipes.html#pipe-style"><i class="fa fa-check"></i><b>11.2.2</b> Pipe style</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="using-pipes.html"><a href="using-pipes.html#final-thought-on-pipes"><i class="fa fa-check"></i><b>11.3</b> Final thought on pipes</a></li>
</ul></li>
<li class="part"><span><b>III Data Transfer</b></span></li>
<li class="chapter" data-level="12" data-path="introduction-to-data-transfer.html"><a href="introduction-to-data-transfer.html"><i class="fa fa-check"></i><b>12</b> Introduction to Data Transfer</a></li>
<li class="chapter" data-level="13" data-path="file-paths.html"><a href="file-paths.html"><i class="fa fa-check"></i><b>13</b> File Paths</a>
<ul>
<li class="chapter" data-level="13.1" data-path="file-paths.html"><a href="file-paths.html#finding-file-paths"><i class="fa fa-check"></i><b>13.1</b> Finding file paths</a></li>
<li class="chapter" data-level="13.2" data-path="file-paths.html"><a href="file-paths.html#relative-file-paths"><i class="fa fa-check"></i><b>13.2</b> Relative file paths</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="importing-plain-text-files.html"><a href="importing-plain-text-files.html"><i class="fa fa-check"></i><b>14</b> Importing Plain Text Files</a>
<ul>
<li class="chapter" data-level="14.1" data-path="importing-plain-text-files.html"><a href="importing-plain-text-files.html#packages-for-importing-data"><i class="fa fa-check"></i><b>14.1</b> Packages for importing data</a></li>
<li class="chapter" data-level="14.2" data-path="importing-plain-text-files.html"><a href="importing-plain-text-files.html#importing-space-delimited-files"><i class="fa fa-check"></i><b>14.2</b> Importing space delimited files</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="importing-plain-text-files.html"><a href="importing-plain-text-files.html#specifying-missing-data-values"><i class="fa fa-check"></i><b>14.2.1</b> Specifying missing data values</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="importing-plain-text-files.html"><a href="importing-plain-text-files.html#importing-tab-delimited-files"><i class="fa fa-check"></i><b>14.3</b> Importing tab delimited files</a></li>
<li class="chapter" data-level="14.4" data-path="importing-plain-text-files.html"><a href="importing-plain-text-files.html#importing-fixed-width-format-files"><i class="fa fa-check"></i><b>14.4</b> Importing fixed width format files</a>
<ul>
<li class="chapter" data-level="14.4.1" data-path="importing-plain-text-files.html"><a href="importing-plain-text-files.html#vector-of-column-widths"><i class="fa fa-check"></i><b>14.4.1</b> Vector of column widths</a></li>
<li class="chapter" data-level="14.4.2" data-path="importing-plain-text-files.html"><a href="importing-plain-text-files.html#paired-vector-of-start-and-end-positions"><i class="fa fa-check"></i><b>14.4.2</b> Paired vector of start and end positions</a></li>
<li class="chapter" data-level="14.4.3" data-path="importing-plain-text-files.html"><a href="importing-plain-text-files.html#using-named-arguments"><i class="fa fa-check"></i><b>14.4.3</b> Using named arguments</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="importing-plain-text-files.html"><a href="importing-plain-text-files.html#importing-comma-separated-values-files"><i class="fa fa-check"></i><b>14.5</b> Importing comma separated values files</a></li>
<li class="chapter" data-level="14.6" data-path="importing-plain-text-files.html"><a href="importing-plain-text-files.html#additional-arguments"><i class="fa fa-check"></i><b>14.6</b> Additional arguments</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="importing-binary-files.html"><a href="importing-binary-files.html"><i class="fa fa-check"></i><b>15</b> Importing Binary Files</a>
<ul>
<li class="chapter" data-level="15.1" data-path="importing-binary-files.html"><a href="importing-binary-files.html#packages-for-importing-data-1"><i class="fa fa-check"></i><b>15.1</b> Packages for importing data</a></li>
<li class="chapter" data-level="15.2" data-path="importing-binary-files.html"><a href="importing-binary-files.html#importing-microsoft-excel-spreadsheets"><i class="fa fa-check"></i><b>15.2</b> Importing Microsoft Excel spreadsheets</a></li>
<li class="chapter" data-level="15.3" data-path="importing-binary-files.html"><a href="importing-binary-files.html#importing-data-from-other-statistical-analysis-software"><i class="fa fa-check"></i><b>15.3</b> Importing data from other statistical analysis software</a></li>
<li class="chapter" data-level="15.4" data-path="importing-binary-files.html"><a href="importing-binary-files.html#importing-sas-data-sets"><i class="fa fa-check"></i><b>15.4</b> Importing SAS data sets</a></li>
<li class="chapter" data-level="15.5" data-path="importing-binary-files.html"><a href="importing-binary-files.html#importing-stata-data-sets"><i class="fa fa-check"></i><b>15.5</b> Importing Stata data sets</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="rstudios-data-import-tool.html"><a href="rstudios-data-import-tool.html"><i class="fa fa-check"></i><b>16</b> RStudio’s Data Import Tool</a></li>
<li class="chapter" data-level="17" data-path="exporting-data.html"><a href="exporting-data.html"><i class="fa fa-check"></i><b>17</b> Exporting Data</a>
<ul>
<li class="chapter" data-level="17.1" data-path="exporting-data.html"><a href="exporting-data.html#plain-text-files"><i class="fa fa-check"></i><b>17.1</b> Plain text files</a></li>
<li class="chapter" data-level="17.2" data-path="exporting-data.html"><a href="exporting-data.html#r-binary-files"><i class="fa fa-check"></i><b>17.2</b> R binary files</a></li>
</ul></li>
<li class="part"><span><b>IV Descriptive Analysis</b></span></li>
<li class="chapter" data-level="18" data-path="introduction-to-descriptive-analysis.html"><a href="introduction-to-descriptive-analysis.html"><i class="fa fa-check"></i><b>18</b> Introduction to Descriptive Analysis</a>
<ul>
<li class="chapter" data-level="18.1" data-path="introduction-to-descriptive-analysis.html"><a href="introduction-to-descriptive-analysis.html#what-is-descriptive-analysis-and-why-would-we-do-it"><i class="fa fa-check"></i><b>18.1</b> What is descriptive analysis and why would we do it?</a></li>
<li class="chapter" data-level="18.2" data-path="introduction-to-descriptive-analysis.html"><a href="introduction-to-descriptive-analysis.html#what-kind-of-descriptive-analysis-should-we-perform"><i class="fa fa-check"></i><b>18.2</b> What kind of descriptive analysis should we perform?</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="numerical-descriptions-of-categorical-variables.html"><a href="numerical-descriptions-of-categorical-variables.html"><i class="fa fa-check"></i><b>19</b> Numerical Descriptions of Categorical Variables</a>
<ul>
<li class="chapter" data-level="19.1" data-path="numerical-descriptions-of-categorical-variables.html"><a href="numerical-descriptions-of-categorical-variables.html#factors"><i class="fa fa-check"></i><b>19.1</b> Factors</a>
<ul>
<li class="chapter" data-level="19.1.1" data-path="numerical-descriptions-of-categorical-variables.html"><a href="numerical-descriptions-of-categorical-variables.html#coerce-a-numeric-variable"><i class="fa fa-check"></i><b>19.1.1</b> Coerce a numeric variable</a></li>
<li class="chapter" data-level="19.1.2" data-path="numerical-descriptions-of-categorical-variables.html"><a href="numerical-descriptions-of-categorical-variables.html#coerce-a-character-variable"><i class="fa fa-check"></i><b>19.1.2</b> Coerce a character variable</a></li>
</ul></li>
<li class="chapter" data-level="19.2" data-path="numerical-descriptions-of-categorical-variables.html"><a href="numerical-descriptions-of-categorical-variables.html#height-and-weight-data"><i class="fa fa-check"></i><b>19.2</b> Height and Weight Data</a>
<ul>
<li class="chapter" data-level="19.2.1" data-path="numerical-descriptions-of-categorical-variables.html"><a href="numerical-descriptions-of-categorical-variables.html#view-the-data"><i class="fa fa-check"></i><b>19.2.1</b> View the data</a></li>
</ul></li>
<li class="chapter" data-level="19.3" data-path="numerical-descriptions-of-categorical-variables.html"><a href="numerical-descriptions-of-categorical-variables.html#calculating-frequencies"><i class="fa fa-check"></i><b>19.3</b> Calculating frequencies</a>
<ul>
<li class="chapter" data-level="19.3.1" data-path="numerical-descriptions-of-categorical-variables.html"><a href="numerical-descriptions-of-categorical-variables.html#the-base-r-table-function"><i class="fa fa-check"></i><b>19.3.1</b> The base R table function</a></li>
<li class="chapter" data-level="19.3.2" data-path="numerical-descriptions-of-categorical-variables.html"><a href="numerical-descriptions-of-categorical-variables.html#the-gmodels-crosstable-function"><i class="fa fa-check"></i><b>19.3.2</b> The gmodels CrossTable function</a></li>
<li class="chapter" data-level="19.3.3" data-path="numerical-descriptions-of-categorical-variables.html"><a href="numerical-descriptions-of-categorical-variables.html#the-tidyverse-way"><i class="fa fa-check"></i><b>19.3.3</b> The tidyverse way</a></li>
</ul></li>
<li class="chapter" data-level="19.4" data-path="numerical-descriptions-of-categorical-variables.html"><a href="numerical-descriptions-of-categorical-variables.html#calculating-percentages"><i class="fa fa-check"></i><b>19.4</b> Calculating percentages</a></li>
<li class="chapter" data-level="19.5" data-path="numerical-descriptions-of-categorical-variables.html"><a href="numerical-descriptions-of-categorical-variables.html#cat-missing-data"><i class="fa fa-check"></i><b>19.5</b> Missing data</a></li>
<li class="chapter" data-level="19.6" data-path="numerical-descriptions-of-categorical-variables.html"><a href="numerical-descriptions-of-categorical-variables.html#formatting-results"><i class="fa fa-check"></i><b>19.6</b> Formatting results</a></li>
<li class="chapter" data-level="19.7" data-path="numerical-descriptions-of-categorical-variables.html"><a href="numerical-descriptions-of-categorical-variables.html#using-freqtables"><i class="fa fa-check"></i><b>19.7</b> Using freqtables</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="measures-of-central-tendency.html"><a href="measures-of-central-tendency.html"><i class="fa fa-check"></i><b>20</b> Measures of Central Tendency</a>
<ul>
<li class="chapter" data-level="20.1" data-path="measures-of-central-tendency.html"><a href="measures-of-central-tendency.html#calculate-the-mean"><i class="fa fa-check"></i><b>20.1</b> Calculate the mean</a></li>
<li class="chapter" data-level="20.2" data-path="measures-of-central-tendency.html"><a href="measures-of-central-tendency.html#calculate-the-median"><i class="fa fa-check"></i><b>20.2</b> Calculate the median</a></li>
<li class="chapter" data-level="20.3" data-path="measures-of-central-tendency.html"><a href="measures-of-central-tendency.html#calculate-the-mode"><i class="fa fa-check"></i><b>20.3</b> Calculate the mode</a></li>
<li class="chapter" data-level="20.4" data-path="measures-of-central-tendency.html"><a href="measures-of-central-tendency.html#compare-mean-median-and-mode"><i class="fa fa-check"></i><b>20.4</b> Compare mean, median, and mode</a></li>
<li class="chapter" data-level="20.5" data-path="measures-of-central-tendency.html"><a href="measures-of-central-tendency.html#data-checking"><i class="fa fa-check"></i><b>20.5</b> Data checking</a></li>
<li class="chapter" data-level="20.6" data-path="measures-of-central-tendency.html"><a href="measures-of-central-tendency.html#properties-of-mean-median-and-mode"><i class="fa fa-check"></i><b>20.6</b> Properties of mean, median, and mode</a></li>
<li class="chapter" data-level="20.7" data-path="measures-of-central-tendency.html"><a href="measures-of-central-tendency.html#na-rm"><i class="fa fa-check"></i><b>20.7</b> Missing data</a></li>
<li class="chapter" data-level="20.8" data-path="measures-of-central-tendency.html"><a href="measures-of-central-tendency.html#using-meantables"><i class="fa fa-check"></i><b>20.8</b> Using meantables</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="measures-of-dispersion.html"><a href="measures-of-dispersion.html"><i class="fa fa-check"></i><b>21</b> Measures of Dispersion</a>
<ul>
<li class="chapter" data-level="21.1" data-path="measures-of-dispersion.html"><a href="measures-of-dispersion.html#comparing-distributions"><i class="fa fa-check"></i><b>21.1</b> Comparing distributions</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="describing-the-relationship-between-a-continuous-outcome-and-a-continuous-predictor.html"><a href="describing-the-relationship-between-a-continuous-outcome-and-a-continuous-predictor.html"><i class="fa fa-check"></i><b>22</b> Describing the Relationship Between a Continuous Outcome and a Continuous Predictor</a>
<ul>
<li class="chapter" data-level="22.1" data-path="describing-the-relationship-between-a-continuous-outcome-and-a-continuous-predictor.html"><a href="describing-the-relationship-between-a-continuous-outcome-and-a-continuous-predictor.html#pearson-correlation-coefficient"><i class="fa fa-check"></i><b>22.1</b> Pearson Correlation Coefficient</a>
<ul>
<li class="chapter" data-level="22.1.1" data-path="describing-the-relationship-between-a-continuous-outcome-and-a-continuous-predictor.html"><a href="describing-the-relationship-between-a-continuous-outcome-and-a-continuous-predictor.html#calculating-r"><i class="fa fa-check"></i><b>22.1.1</b> Calculating r</a></li>
<li class="chapter" data-level="22.1.2" data-path="describing-the-relationship-between-a-continuous-outcome-and-a-continuous-predictor.html"><a href="describing-the-relationship-between-a-continuous-outcome-and-a-continuous-predictor.html#correlation-intuition"><i class="fa fa-check"></i><b>22.1.2</b> Correlation intuition</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="23" data-path="describing-the-relationship-between-a-continuous-outcome-and-a-categorical-predictor.html"><a href="describing-the-relationship-between-a-continuous-outcome-and-a-categorical-predictor.html"><i class="fa fa-check"></i><b>23</b> Describing the Relationship Between a Continuous Outcome and a Categorical Predictor</a>
<ul>
<li class="chapter" data-level="23.1" data-path="describing-the-relationship-between-a-continuous-outcome-and-a-categorical-predictor.html"><a href="describing-the-relationship-between-a-continuous-outcome-and-a-categorical-predictor.html#single-predictor-and-single-outcome"><i class="fa fa-check"></i><b>23.1</b> Single predictor and single outcome</a></li>
<li class="chapter" data-level="23.2" data-path="describing-the-relationship-between-a-continuous-outcome-and-a-categorical-predictor.html"><a href="describing-the-relationship-between-a-continuous-outcome-and-a-categorical-predictor.html#multiple-predictors"><i class="fa fa-check"></i><b>23.2</b> Multiple predictors</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="describing-the-relationship-between-a-categorical-outcome-and-a-categorical-predictor.html"><a href="describing-the-relationship-between-a-categorical-outcome-and-a-categorical-predictor.html"><i class="fa fa-check"></i><b>24</b> Describing the Relationship Between a Categorical Outcome and a Categorical Predictor</a>
<ul>
<li class="chapter" data-level="24.1" data-path="describing-the-relationship-between-a-categorical-outcome-and-a-categorical-predictor.html"><a href="describing-the-relationship-between-a-categorical-outcome-and-a-categorical-predictor.html#comparing-two-variables"><i class="fa fa-check"></i><b>24.1</b> Comparing two variables</a></li>
</ul></li>
<li class="part"><span><b>V Data Management</b></span></li>
<li class="chapter" data-level="25" data-path="introduction-to-data-management.html"><a href="introduction-to-data-management.html"><i class="fa fa-check"></i><b>25</b> Introduction to Data Management</a>
<ul>
<li class="chapter" data-level="25.1" data-path="introduction-to-data-management.html"><a href="introduction-to-data-management.html#multiple-paradigms-for-data-management-in-r"><i class="fa fa-check"></i><b>25.1</b> Multiple paradigms for data management in R</a></li>
<li class="chapter" data-level="25.2" data-path="introduction-to-data-management.html"><a href="introduction-to-data-management.html#the-dplyr-package"><i class="fa fa-check"></i><b>25.2</b> The dplyr package</a>
<ul>
<li class="chapter" data-level="25.2.1" data-path="introduction-to-data-management.html"><a href="introduction-to-data-management.html#the-dplyr-verbs"><i class="fa fa-check"></i><b>25.2.1</b> The dplyr verbs</a></li>
<li class="chapter" data-level="25.2.2" data-path="introduction-to-data-management.html"><a href="introduction-to-data-management.html#the-.data-argument"><i class="fa fa-check"></i><b>25.2.2</b> The .data argument</a></li>
<li class="chapter" data-level="25.2.3" data-path="introduction-to-data-management.html"><a href="introduction-to-data-management.html#the-argument"><i class="fa fa-check"></i><b>25.2.3</b> The … argument</a></li>
<li class="chapter" data-level="25.2.4" data-path="introduction-to-data-management.html"><a href="introduction-to-data-management.html#non-standard-evaluation"><i class="fa fa-check"></i><b>25.2.4</b> Non-standard evaluation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="26" data-path="creating-and-modifying-columns.html"><a href="creating-and-modifying-columns.html"><i class="fa fa-check"></i><b>26</b> Creating and Modifying Columns</a>
<ul>
<li class="chapter" data-level="26.1" data-path="creating-and-modifying-columns.html"><a href="creating-and-modifying-columns.html#creating-data-frames"><i class="fa fa-check"></i><b>26.1</b> Creating data frames</a></li>
<li class="chapter" data-level="26.2" data-path="creating-and-modifying-columns.html"><a href="creating-and-modifying-columns.html#dollar-sign-notation-1"><i class="fa fa-check"></i><b>26.2</b> Dollar sign notation</a></li>
<li class="chapter" data-level="26.3" data-path="creating-and-modifying-columns.html"><a href="creating-and-modifying-columns.html#bracket-notation-1"><i class="fa fa-check"></i><b>26.3</b> Bracket notation</a></li>
<li class="chapter" data-level="26.4" data-path="creating-and-modifying-columns.html"><a href="creating-and-modifying-columns.html#modify-individual-values"><i class="fa fa-check"></i><b>26.4</b> Modify individual values</a></li>
<li class="chapter" data-level="26.5" data-path="creating-and-modifying-columns.html"><a href="creating-and-modifying-columns.html#the-mutate-function"><i class="fa fa-check"></i><b>26.5</b> The mutate() function</a>
<ul>
<li class="chapter" data-level="26.5.1" data-path="creating-and-modifying-columns.html"><a href="creating-and-modifying-columns.html#adding-or-modifying-a-single-column"><i class="fa fa-check"></i><b>26.5.1</b> Adding or modifying a single column</a></li>
<li class="chapter" data-level="26.5.2" data-path="creating-and-modifying-columns.html"><a href="creating-and-modifying-columns.html#recycling-rules"><i class="fa fa-check"></i><b>26.5.2</b> Recycling rules</a></li>
<li class="chapter" data-level="26.5.3" data-path="creating-and-modifying-columns.html"><a href="creating-and-modifying-columns.html#using-existing-variables-in-name-value-pairs"><i class="fa fa-check"></i><b>26.5.3</b> Using existing variables in name-value pairs</a></li>
<li class="chapter" data-level="26.5.4" data-path="creating-and-modifying-columns.html"><a href="creating-and-modifying-columns.html#adding-or-modifying-multiple-columns"><i class="fa fa-check"></i><b>26.5.4</b> Adding or modifying multiple columns</a></li>
<li class="chapter" data-level="26.5.5" data-path="creating-and-modifying-columns.html"><a href="creating-and-modifying-columns.html#rowwise-mutations"><i class="fa fa-check"></i><b>26.5.5</b> Rowwise mutations</a></li>
<li class="chapter" data-level="26.5.6" data-path="creating-and-modifying-columns.html"><a href="creating-and-modifying-columns.html#group_by-mutations"><i class="fa fa-check"></i><b>26.5.6</b> Group_by mutations</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="27" data-path="subsetting-data-frames.html"><a href="subsetting-data-frames.html"><i class="fa fa-check"></i><b>27</b> Subsetting Data Frames</a>
<ul>
<li class="chapter" data-level="27.1" data-path="subsetting-data-frames.html"><a href="subsetting-data-frames.html#the-select-function"><i class="fa fa-check"></i><b>27.1</b> The select() function</a></li>
<li class="chapter" data-level="27.2" data-path="subsetting-data-frames.html"><a href="subsetting-data-frames.html#the-rename-function"><i class="fa fa-check"></i><b>27.2</b> The rename() function</a></li>
<li class="chapter" data-level="27.3" data-path="subsetting-data-frames.html"><a href="subsetting-data-frames.html#the-filter-function"><i class="fa fa-check"></i><b>27.3</b> The filter() function</a>
<ul>
<li class="chapter" data-level="27.3.1" data-path="subsetting-data-frames.html"><a href="subsetting-data-frames.html#subgroup-analysis"><i class="fa fa-check"></i><b>27.3.1</b> Subgroup analysis</a></li>
<li class="chapter" data-level="27.3.2" data-path="subsetting-data-frames.html"><a href="subsetting-data-frames.html#complete-case-analysis"><i class="fa fa-check"></i><b>27.3.2</b> Complete case analysis</a></li>
</ul></li>
<li class="chapter" data-level="27.4" data-path="subsetting-data-frames.html"><a href="subsetting-data-frames.html#deduplication"><i class="fa fa-check"></i><b>27.4</b> Deduplication</a>
<ul>
<li class="chapter" data-level="27.4.1" data-path="subsetting-data-frames.html"><a href="subsetting-data-frames.html#the-distinct-function"><i class="fa fa-check"></i><b>27.4.1</b> The distinct() function</a></li>
<li class="chapter" data-level="27.4.2" data-path="subsetting-data-frames.html"><a href="subsetting-data-frames.html#complete-duplicate-row-add-tag"><i class="fa fa-check"></i><b>27.4.2</b> Complete duplicate row add tag</a></li>
<li class="chapter" data-level="27.4.3" data-path="subsetting-data-frames.html"><a href="subsetting-data-frames.html#partial-duplicate-rows"><i class="fa fa-check"></i><b>27.4.3</b> Partial duplicate rows</a></li>
<li class="chapter" data-level="27.4.4" data-path="subsetting-data-frames.html"><a href="subsetting-data-frames.html#partial-duplicate-rows---add-tag"><i class="fa fa-check"></i><b>27.4.4</b> Partial duplicate rows - add tag</a></li>
<li class="chapter" data-level="27.4.5" data-path="subsetting-data-frames.html"><a href="subsetting-data-frames.html#count-the-number-of-duplicates"><i class="fa fa-check"></i><b>27.4.5</b> Count the number of duplicates</a></li>
<li class="chapter" data-level="27.4.6" data-path="subsetting-data-frames.html"><a href="subsetting-data-frames.html#what-to-do-about-duplicates"><i class="fa fa-check"></i><b>27.4.6</b> What to do about duplicates</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="28" data-path="working-with-dates.html"><a href="working-with-dates.html"><i class="fa fa-check"></i><b>28</b> Working with Dates</a>
<ul>
<li class="chapter" data-level="28.1" data-path="working-with-dates.html"><a href="working-with-dates.html#date-vector-types"><i class="fa fa-check"></i><b>28.1</b> Date vector types</a></li>
<li class="chapter" data-level="28.2" data-path="working-with-dates.html"><a href="working-with-dates.html#dates-under-the-hood"><i class="fa fa-check"></i><b>28.2</b> Dates under the hood</a></li>
<li class="chapter" data-level="28.3" data-path="working-with-dates.html"><a href="working-with-dates.html#coercing-date-times-to-dates"><i class="fa fa-check"></i><b>28.3</b> Coercing date-times to dates</a></li>
<li class="chapter" data-level="28.4" data-path="working-with-dates.html"><a href="working-with-dates.html#coercing-character-strings-to-dates"><i class="fa fa-check"></i><b>28.4</b> Coercing character strings to dates</a></li>
<li class="chapter" data-level="28.5" data-path="working-with-dates.html"><a href="working-with-dates.html#change-the-appearance-of-dates-with-format"><i class="fa fa-check"></i><b>28.5</b> Change the appearance of dates with format()</a></li>
<li class="chapter" data-level="28.6" data-path="working-with-dates.html"><a href="working-with-dates.html#some-useful-built-in-dates"><i class="fa fa-check"></i><b>28.6</b> Some useful built-in dates</a>
<ul>
<li class="chapter" data-level="28.6.1" data-path="working-with-dates.html"><a href="working-with-dates.html#todays-date"><i class="fa fa-check"></i><b>28.6.1</b> Today’s date</a></li>
<li class="chapter" data-level="28.6.2" data-path="working-with-dates.html"><a href="working-with-dates.html#todays-date-time"><i class="fa fa-check"></i><b>28.6.2</b> Today’s date-time</a></li>
<li class="chapter" data-level="28.6.3" data-path="working-with-dates.html"><a href="working-with-dates.html#character-vector-of-full-month-names"><i class="fa fa-check"></i><b>28.6.3</b> Character vector of full month names</a></li>
<li class="chapter" data-level="28.6.4" data-path="working-with-dates.html"><a href="working-with-dates.html#character-vector-of-abbreviated-month-names"><i class="fa fa-check"></i><b>28.6.4</b> Character vector of abbreviated month names</a></li>
<li class="chapter" data-level="28.6.5" data-path="working-with-dates.html"><a href="working-with-dates.html#creating-a-vector-containing-a-sequence-of-dates"><i class="fa fa-check"></i><b>28.6.5</b> Creating a vector containing a sequence of dates</a></li>
</ul></li>
<li class="chapter" data-level="28.7" data-path="working-with-dates.html"><a href="working-with-dates.html#calculating-date-intervals"><i class="fa fa-check"></i><b>28.7</b> Calculating date intervals</a>
<ul>
<li class="chapter" data-level="28.7.1" data-path="working-with-dates.html"><a href="working-with-dates.html#calculate-age-as-the-difference-in-time-between-dob-and-today"><i class="fa fa-check"></i><b>28.7.1</b> Calculate age as the difference in time between dob and today</a></li>
<li class="chapter" data-level="28.7.2" data-path="working-with-dates.html"><a href="working-with-dates.html#rounding-time-intervals"><i class="fa fa-check"></i><b>28.7.2</b> Rounding time intervals</a></li>
</ul></li>
<li class="chapter" data-level="28.8" data-path="working-with-dates.html"><a href="working-with-dates.html#extracting-out-date-parts"><i class="fa fa-check"></i><b>28.8</b> Extracting out date parts</a></li>
<li class="chapter" data-level="28.9" data-path="working-with-dates.html"><a href="working-with-dates.html#sorting-dates"><i class="fa fa-check"></i><b>28.9</b> Sorting dates</a></li>
</ul></li>
<li class="chapter" data-level="29" data-path="working-with-character-strings.html"><a href="working-with-character-strings.html"><i class="fa fa-check"></i><b>29</b> Working with Character Strings</a>
<ul>
<li class="chapter" data-level="29.1" data-path="working-with-character-strings.html"><a href="working-with-character-strings.html#coerce-to-lowercase"><i class="fa fa-check"></i><b>29.1</b> Coerce to lowercase</a>
<ul>
<li class="chapter" data-level="29.1.1" data-path="working-with-character-strings.html"><a href="working-with-character-strings.html#lowercase"><i class="fa fa-check"></i><b>29.1.1</b> Lowercase</a></li>
<li class="chapter" data-level="29.1.2" data-path="working-with-character-strings.html"><a href="working-with-character-strings.html#upper-case"><i class="fa fa-check"></i><b>29.1.2</b> Upper case</a></li>
<li class="chapter" data-level="29.1.3" data-path="working-with-character-strings.html"><a href="working-with-character-strings.html#title-case"><i class="fa fa-check"></i><b>29.1.3</b> Title case</a></li>
<li class="chapter" data-level="29.1.4" data-path="working-with-character-strings.html"><a href="working-with-character-strings.html#sentence-case"><i class="fa fa-check"></i><b>29.1.4</b> Sentence case</a></li>
</ul></li>
<li class="chapter" data-level="29.2" data-path="working-with-character-strings.html"><a href="working-with-character-strings.html#trim-white-space"><i class="fa fa-check"></i><b>29.2</b> Trim white space</a></li>
<li class="chapter" data-level="29.3" data-path="working-with-character-strings.html"><a href="working-with-character-strings.html#regular-expressions"><i class="fa fa-check"></i><b>29.3</b> Regular expressions</a>
<ul>
<li class="chapter" data-level="29.3.1" data-path="working-with-character-strings.html"><a href="working-with-character-strings.html#remove-the-comma"><i class="fa fa-check"></i><b>29.3.1</b> Remove the comma</a></li>
<li class="chapter" data-level="29.3.2" data-path="working-with-character-strings.html"><a href="working-with-character-strings.html#remove-middle-initial"><i class="fa fa-check"></i><b>29.3.2</b> Remove middle initial</a></li>
<li class="chapter" data-level="29.3.3" data-path="working-with-character-strings.html"><a href="working-with-character-strings.html#remove-double-spaces"><i class="fa fa-check"></i><b>29.3.3</b> Remove double spaces</a></li>
</ul></li>
<li class="chapter" data-level="29.4" data-path="working-with-character-strings.html"><a href="working-with-character-strings.html#separate-values-into-component-parts"><i class="fa fa-check"></i><b>29.4</b> Separate values into component parts</a></li>
<li class="chapter" data-level="29.5" data-path="working-with-character-strings.html"><a href="working-with-character-strings.html#dummy-variables"><i class="fa fa-check"></i><b>29.5</b> Dummy variables</a></li>
</ul></li>
<li class="chapter" data-level="30" data-path="conditional-operations.html"><a href="conditional-operations.html"><i class="fa fa-check"></i><b>30</b> Conditional Operations</a>
<ul>
<li class="chapter" data-level="30.1" data-path="conditional-operations.html"><a href="conditional-operations.html#operands-and-operators"><i class="fa fa-check"></i><b>30.1</b> Operands and operators</a></li>
<li class="chapter" data-level="30.2" data-path="conditional-operations.html"><a href="conditional-operations.html#testing-multiple-conditions-simultaneously"><i class="fa fa-check"></i><b>30.2</b> Testing multiple conditions simultaneously</a></li>
<li class="chapter" data-level="30.3" data-path="conditional-operations.html"><a href="conditional-operations.html#testing-a-sequence-of-conditions"><i class="fa fa-check"></i><b>30.3</b> Testing a sequence of conditions</a></li>
<li class="chapter" data-level="30.4" data-path="conditional-operations.html"><a href="conditional-operations.html#recoding-variables"><i class="fa fa-check"></i><b>30.4</b> Recoding variables</a></li>
<li class="chapter" data-level="30.5" data-path="conditional-operations.html"><a href="conditional-operations.html#case_when-is-lazy"><i class="fa fa-check"></i><b>30.5</b> case_when() is lazy</a></li>
<li class="chapter" data-level="30.6" data-path="conditional-operations.html"><a href="conditional-operations.html#recode-missing"><i class="fa fa-check"></i><b>30.6</b> Recode missing</a></li>
</ul></li>
<li class="chapter" data-level="31" data-path="working-with-multiple-data-frames.html"><a href="working-with-multiple-data-frames.html"><i class="fa fa-check"></i><b>31</b> Working with Multiple Data Frames</a>
<ul>
<li class="chapter" data-level="31.1" data-path="working-with-multiple-data-frames.html"><a href="working-with-multiple-data-frames.html#combining-data-frames-vertically-adding-rows"><i class="fa fa-check"></i><b>31.1</b> Combining data frames vertically: Adding rows</a>
<ul>
<li class="chapter" data-level="31.1.1" data-path="working-with-multiple-data-frames.html"><a href="working-with-multiple-data-frames.html#combining-more-than-2-data-frames"><i class="fa fa-check"></i><b>31.1.1</b> Combining more than 2 data frames</a></li>
<li class="chapter" data-level="31.1.2" data-path="working-with-multiple-data-frames.html"><a href="working-with-multiple-data-frames.html#adding-rows-with-differing-columns"><i class="fa fa-check"></i><b>31.1.2</b> Adding rows with differing columns</a></li>
<li class="chapter" data-level="31.1.3" data-path="working-with-multiple-data-frames.html"><a href="working-with-multiple-data-frames.html#differing-column-positions"><i class="fa fa-check"></i><b>31.1.3</b> Differing column positions</a></li>
<li class="chapter" data-level="31.1.4" data-path="working-with-multiple-data-frames.html"><a href="working-with-multiple-data-frames.html#differing-column-names"><i class="fa fa-check"></i><b>31.1.4</b> Differing column names</a></li>
</ul></li>
<li class="chapter" data-level="31.2" data-path="working-with-multiple-data-frames.html"><a href="working-with-multiple-data-frames.html#combining-data-frames-horizontally-adding-columns"><i class="fa fa-check"></i><b>31.2</b> Combining data frames horizontally: Adding columns</a>
<ul>
<li class="chapter" data-level="31.2.1" data-path="working-with-multiple-data-frames.html"><a href="working-with-multiple-data-frames.html#combining-data-frames-horizontally-by-position"><i class="fa fa-check"></i><b>31.2.1</b> Combining data frames horizontally by position</a></li>
<li class="chapter" data-level="31.2.2" data-path="working-with-multiple-data-frames.html"><a href="working-with-multiple-data-frames.html#combining-data-frames-horizontally-by-key-values"><i class="fa fa-check"></i><b>31.2.2</b> Combining data frames horizontally by key values</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="32" data-path="restructuring-data-frames.html"><a href="restructuring-data-frames.html"><i class="fa fa-check"></i><b>32</b> Restructuring Data frames</a>
<ul>
<li class="chapter" data-level="32.1" data-path="restructuring-data-frames.html"><a href="restructuring-data-frames.html#the-tidyr-package"><i class="fa fa-check"></i><b>32.1</b> The tidyr package</a></li>
<li class="chapter" data-level="32.2" data-path="restructuring-data-frames.html"><a href="restructuring-data-frames.html#pivoting-longer"><i class="fa fa-check"></i><b>32.2</b> Pivoting longer</a>
<ul>
<li class="chapter" data-level="32.2.1" data-path="restructuring-data-frames.html"><a href="restructuring-data-frames.html#the-names_to-argument"><i class="fa fa-check"></i><b>32.2.1</b> The names_to argument</a></li>
<li class="chapter" data-level="32.2.2" data-path="restructuring-data-frames.html"><a href="restructuring-data-frames.html#the-names_prefix-argument"><i class="fa fa-check"></i><b>32.2.2</b> The names_prefix argument</a></li>
<li class="chapter" data-level="32.2.3" data-path="restructuring-data-frames.html"><a href="restructuring-data-frames.html#the-values_to-argument"><i class="fa fa-check"></i><b>32.2.3</b> The values_to argument</a></li>
<li class="chapter" data-level="32.2.4" data-path="restructuring-data-frames.html"><a href="restructuring-data-frames.html#the-names_transform-argument"><i class="fa fa-check"></i><b>32.2.4</b> The names_transform argument</a></li>
<li class="chapter" data-level="32.2.5" data-path="restructuring-data-frames.html"><a href="restructuring-data-frames.html#pivoting-multiple-sets-of-columns"><i class="fa fa-check"></i><b>32.2.5</b> Pivoting multiple sets of columns</a></li>
<li class="chapter" data-level="32.2.6" data-path="restructuring-data-frames.html"><a href="restructuring-data-frames.html#the-names_sep-argument"><i class="fa fa-check"></i><b>32.2.6</b> The names_sep argument</a></li>
<li class="chapter" data-level="32.2.7" data-path="restructuring-data-frames.html"><a href="restructuring-data-frames.html#the-.value-special-value"><i class="fa fa-check"></i><b>32.2.7</b> The .value special value</a></li>
<li class="chapter" data-level="32.2.8" data-path="restructuring-data-frames.html"><a href="restructuring-data-frames.html#why-person-period"><i class="fa fa-check"></i><b>32.2.8</b> Why person-period?</a></li>
</ul></li>
<li class="chapter" data-level="32.3" data-path="restructuring-data-frames.html"><a href="restructuring-data-frames.html#pivoting-wider"><i class="fa fa-check"></i><b>32.3</b> Pivoting wider</a>
<ul>
<li class="chapter" data-level="32.3.1" data-path="restructuring-data-frames.html"><a href="restructuring-data-frames.html#why-person-level"><i class="fa fa-check"></i><b>32.3.1</b> Why person-level?</a></li>
</ul></li>
<li class="chapter" data-level="32.4" data-path="restructuring-data-frames.html"><a href="restructuring-data-frames.html#pivoting-summary-statistics"><i class="fa fa-check"></i><b>32.4</b> Pivoting summary statistics</a>
<ul>
<li class="chapter" data-level="32.4.1" data-path="restructuring-data-frames.html"><a href="restructuring-data-frames.html#pivoting-summary-statistics-wide-to-long"><i class="fa fa-check"></i><b>32.4.1</b> Pivoting summary statistics wide to long</a></li>
<li class="chapter" data-level="32.4.2" data-path="restructuring-data-frames.html"><a href="restructuring-data-frames.html#pivoting-summary-statistics-long-to-wide"><i class="fa fa-check"></i><b>32.4.2</b> Pivoting summary statistics long to wide</a></li>
</ul></li>
<li class="chapter" data-level="32.5" data-path="restructuring-data-frames.html"><a href="restructuring-data-frames.html#tidy-data"><i class="fa fa-check"></i><b>32.5</b> Tidy data</a>
<ul>
<li class="chapter" data-level="32.5.1" data-path="restructuring-data-frames.html"><a href="restructuring-data-frames.html#each-variable-must-have-its-own-column"><i class="fa fa-check"></i><b>32.5.1</b> Each variable must have its own column</a></li>
<li class="chapter" data-level="32.5.2" data-path="restructuring-data-frames.html"><a href="restructuring-data-frames.html#each-observation-must-have-its-own-row"><i class="fa fa-check"></i><b>32.5.2</b> Each observation must have its own row</a></li>
<li class="chapter" data-level="32.5.3" data-path="restructuring-data-frames.html"><a href="restructuring-data-frames.html#each-value-must-have-its-own-cell"><i class="fa fa-check"></i><b>32.5.3</b> Each value must have its own cell</a></li>
</ul></li>
<li class="chapter" data-level="32.6" data-path="restructuring-data-frames.html"><a href="restructuring-data-frames.html#the-complete-function"><i class="fa fa-check"></i><b>32.6</b> The complete() function</a></li>
</ul></li>
<li class="part"><span><b>VI Repeated Operations</b></span></li>
<li class="chapter" data-level="33" data-path="introduction-to-repeated-operations.html"><a href="introduction-to-repeated-operations.html"><i class="fa fa-check"></i><b>33</b> Introduction to Repeated Operations</a>
<ul>
<li class="chapter" data-level="33.1" data-path="introduction-to-repeated-operations.html"><a href="introduction-to-repeated-operations.html#multiple-methods-for-repeated-operations-in-r"><i class="fa fa-check"></i><b>33.1</b> Multiple methods for repeated operations in R</a></li>
<li class="chapter" data-level="33.2" data-path="introduction-to-repeated-operations.html"><a href="introduction-to-repeated-operations.html#tidy-evaluation"><i class="fa fa-check"></i><b>33.2</b> Tidy evaluation</a></li>
</ul></li>
<li class="chapter" data-level="34" data-path="writing-functions.html"><a href="writing-functions.html"><i class="fa fa-check"></i><b>34</b> Writing Functions</a>
<ul>
<li class="chapter" data-level="34.1" data-path="writing-functions.html"><a href="writing-functions.html#when-to-write-functions"><i class="fa fa-check"></i><b>34.1</b> When to write functions</a></li>
<li class="chapter" data-level="34.2" data-path="writing-functions.html"><a href="writing-functions.html#how-to-write-functions"><i class="fa fa-check"></i><b>34.2</b> How to write functions</a>
<ul>
<li class="chapter" data-level="34.2.1" data-path="writing-functions.html"><a href="writing-functions.html#the-function-function"><i class="fa fa-check"></i><b>34.2.1</b> The function() function</a></li>
<li class="chapter" data-level="34.2.2" data-path="writing-functions.html"><a href="writing-functions.html#the-function-writing-process"><i class="fa fa-check"></i><b>34.2.2</b> The function writing process</a></li>
</ul></li>
<li class="chapter" data-level="34.3" data-path="writing-functions.html"><a href="writing-functions.html#giving-your-function-arguments-default-values"><i class="fa fa-check"></i><b>34.3</b> Giving your function arguments default values</a></li>
<li class="chapter" data-level="34.4" data-path="writing-functions.html"><a href="writing-functions.html#the-values-your-functions-return"><i class="fa fa-check"></i><b>34.4</b> The values your functions return</a></li>
<li class="chapter" data-level="34.5" data-path="writing-functions.html"><a href="writing-functions.html#lexical-scoping-and-functions"><i class="fa fa-check"></i><b>34.5</b> Lexical scoping and functions</a></li>
<li class="chapter" data-level="34.6" data-path="writing-functions.html"><a href="writing-functions.html#tidy-evaluation-1"><i class="fa fa-check"></i><b>34.6</b> Tidy evaluation</a></li>
</ul></li>
<li class="chapter" data-level="35" data-path="column-wise-operations-in-dplyr.html"><a href="column-wise-operations-in-dplyr.html"><i class="fa fa-check"></i><b>35</b> Column-wise Operations in dplyr</a>
<ul>
<li class="chapter" data-level="35.1" data-path="column-wise-operations-in-dplyr.html"><a href="column-wise-operations-in-dplyr.html#the-across-function"><i class="fa fa-check"></i><b>35.1</b> The across() function</a></li>
<li class="chapter" data-level="35.2" data-path="column-wise-operations-in-dplyr.html"><a href="column-wise-operations-in-dplyr.html#across-with-mutate"><i class="fa fa-check"></i><b>35.2</b> Across with mutate</a></li>
<li class="chapter" data-level="35.3" data-path="column-wise-operations-in-dplyr.html"><a href="column-wise-operations-in-dplyr.html#across-with-summarise"><i class="fa fa-check"></i><b>35.3</b> Across with summarise</a></li>
<li class="chapter" data-level="35.4" data-path="column-wise-operations-in-dplyr.html"><a href="column-wise-operations-in-dplyr.html#across-with-filter"><i class="fa fa-check"></i><b>35.4</b> Across with filter</a></li>
<li class="chapter" data-level="35.5" data-path="column-wise-operations-in-dplyr.html"><a href="column-wise-operations-in-dplyr.html#summary-3"><i class="fa fa-check"></i><b>35.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="36" data-path="writing-for-loops.html"><a href="writing-for-loops.html"><i class="fa fa-check"></i><b>36</b> Writing For Loops</a>
<ul>
<li class="chapter" data-level="36.1" data-path="writing-for-loops.html"><a href="writing-for-loops.html#how-to-write-for-loops"><i class="fa fa-check"></i><b>36.1</b> How to write for loops</a>
<ul>
<li class="chapter" data-level="36.1.1" data-path="writing-for-loops.html"><a href="writing-for-loops.html#the-for-loop-body"><i class="fa fa-check"></i><b>36.1.1</b> The for loop body</a></li>
<li class="chapter" data-level="36.1.2" data-path="writing-for-loops.html"><a href="writing-for-loops.html#the-for-function"><i class="fa fa-check"></i><b>36.1.2</b> The for() function</a></li>
</ul></li>
<li class="chapter" data-level="36.2" data-path="writing-for-loops.html"><a href="writing-for-loops.html#using-for-loops-for-data-transfer"><i class="fa fa-check"></i><b>36.2</b> Using for loops for data transfer</a></li>
<li class="chapter" data-level="36.3" data-path="writing-for-loops.html"><a href="writing-for-loops.html#using-for-loops-for-data-management"><i class="fa fa-check"></i><b>36.3</b> Using for loops for data management</a></li>
<li class="chapter" data-level="36.4" data-path="writing-for-loops.html"><a href="writing-for-loops.html#using-for-loops-for-analysis"><i class="fa fa-check"></i><b>36.4</b> Using for loops for analysis</a></li>
</ul></li>
<li class="chapter" data-level="37" data-path="using-the-purrr-package.html"><a href="using-the-purrr-package.html"><i class="fa fa-check"></i><b>37</b> Using the purrr Package</a>
<ul>
<li class="chapter" data-level="37.1" data-path="using-the-purrr-package.html"><a href="using-the-purrr-package.html#comparing-for-loops-and-the-map-functions"><i class="fa fa-check"></i><b>37.1</b> Comparing for loops and the map functions</a></li>
<li class="chapter" data-level="37.2" data-path="using-the-purrr-package.html"><a href="using-the-purrr-package.html#using-purrr-for-data-transfer"><i class="fa fa-check"></i><b>37.2</b> Using purrr for data transfer</a>
<ul>
<li class="chapter" data-level="37.2.1" data-path="using-the-purrr-package.html"><a href="using-the-purrr-package.html#example-1-importing-multiple-sheets-from-an-excel-workbook"><i class="fa fa-check"></i><b>37.2.1</b> Example 1: Importing multiple sheets from an Excel workbook</a></li>
<li class="chapter" data-level="37.2.2" data-path="using-the-purrr-package.html"><a href="using-the-purrr-package.html#why-walk-instead-of-map"><i class="fa fa-check"></i><b>37.2.2</b> Why walk instead of map?</a></li>
<li class="chapter" data-level="37.2.3" data-path="using-the-purrr-package.html"><a href="using-the-purrr-package.html#why-we-didnt-assign-the-return-value-of-walk-to-an-object"><i class="fa fa-check"></i><b>37.2.3</b> why we didn’t assign the return value of <code>walk()</code> to an object?</a></li>
</ul></li>
<li class="chapter" data-level="37.3" data-path="using-the-purrr-package.html"><a href="using-the-purrr-package.html#using-purrr-for-data-management"><i class="fa fa-check"></i><b>37.3</b> Using purrr for data management</a>
<ul>
<li class="chapter" data-level="37.3.1" data-path="using-the-purrr-package.html"><a href="using-the-purrr-package.html#example-1-adding-na-at-multiple-positions"><i class="fa fa-check"></i><b>37.3.1</b> Example 1: Adding NA at multiple positions</a></li>
<li class="chapter" data-level="37.3.2" data-path="using-the-purrr-package.html"><a href="using-the-purrr-package.html#example-2.-detecting-matching-values-by-position"><i class="fa fa-check"></i><b>37.3.2</b> Example 2. Detecting matching values by position</a></li>
</ul></li>
<li class="chapter" data-level="37.4" data-path="using-the-purrr-package.html"><a href="using-the-purrr-package.html#using-purrr-for-analysis"><i class="fa fa-check"></i><b>37.4</b> Using purrr for analysis</a>
<ul>
<li class="chapter" data-level="37.4.1" data-path="using-the-purrr-package.html"><a href="using-the-purrr-package.html#example-1-continuous-statistics"><i class="fa fa-check"></i><b>37.4.1</b> Example 1: Continuous statistics</a></li>
<li class="chapter" data-level="37.4.2" data-path="using-the-purrr-package.html"><a href="using-the-purrr-package.html#example-2-categorical-statistics"><i class="fa fa-check"></i><b>37.4.2</b> Example 2: Categorical statistics</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>VII Collaboration</b></span></li>
<li class="chapter" data-level="38" data-path="introduction-to-git-and-github.html"><a href="introduction-to-git-and-github.html"><i class="fa fa-check"></i><b>38</b> Introduction to git and GitHub</a>
<ul>
<li class="chapter" data-level="38.1" data-path="introduction-to-git-and-github.html"><a href="introduction-to-git-and-github.html#versioning"><i class="fa fa-check"></i><b>38.1</b> Versioning</a></li>
<li class="chapter" data-level="38.2" data-path="introduction-to-git-and-github.html"><a href="introduction-to-git-and-github.html#preservation"><i class="fa fa-check"></i><b>38.2</b> Preservation</a></li>
<li class="chapter" data-level="38.3" data-path="introduction-to-git-and-github.html"><a href="introduction-to-git-and-github.html#reproducibility"><i class="fa fa-check"></i><b>38.3</b> Reproducibility</a></li>
<li class="chapter" data-level="38.4" data-path="introduction-to-git-and-github.html"><a href="introduction-to-git-and-github.html#collaboration"><i class="fa fa-check"></i><b>38.4</b> Collaboration</a></li>
<li class="chapter" data-level="38.5" data-path="introduction-to-git-and-github.html"><a href="introduction-to-git-and-github.html#summary-4"><i class="fa fa-check"></i><b>38.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="39" data-path="using-git-and-github.html"><a href="using-git-and-github.html"><i class="fa fa-check"></i><b>39</b> Using git and GitHub</a>
<ul>
<li class="chapter" data-level="39.1" data-path="using-git-and-github.html"><a href="using-git-and-github.html#install-git"><i class="fa fa-check"></i><b>39.1</b> Install git</a></li>
<li class="chapter" data-level="39.2" data-path="using-git-and-github.html"><a href="using-git-and-github.html#sign-up-for-a-github-account"><i class="fa fa-check"></i><b>39.2</b> Sign up for a GitHub account</a></li>
<li class="chapter" data-level="39.3" data-path="using-git-and-github.html"><a href="using-git-and-github.html#install-gitkraken"><i class="fa fa-check"></i><b>39.3</b> Install GitKraken</a></li>
<li class="chapter" data-level="39.4" data-path="using-git-and-github.html"><a href="using-git-and-github.html#example-1-contribute-to-r4epi"><i class="fa fa-check"></i><b>39.4</b> Example 1: Contribute to R4Epi</a></li>
<li class="chapter" data-level="39.5" data-path="using-git-and-github.html"><a href="using-git-and-github.html#example-2-create-a-repository-for-a-research-project"><i class="fa fa-check"></i><b>39.5</b> Example 2: Create a repository for a research project</a>
<ul>
<li class="chapter" data-level="" data-path="using-git-and-github.html"><a href="using-git-and-github.html#step-1-create-a-repository-on-github"><i class="fa fa-check"></i>Step 1: Create a repository on GitHub</a></li>
<li class="chapter" data-level="" data-path="using-git-and-github.html"><a href="using-git-and-github.html#step-2-clone-the-repository-to-your-computer"><i class="fa fa-check"></i>Step 2: Clone the repository to your computer</a></li>
<li class="chapter" data-level="" data-path="using-git-and-github.html"><a href="using-git-and-github.html#step-3-add-an-r-project-file-to-the-repository"><i class="fa fa-check"></i>Step 3: Add an R project file to the repository</a></li>
<li class="chapter" data-level="" data-path="using-git-and-github.html"><a href="using-git-and-github.html#step-4-update-and-commit-gitignore"><i class="fa fa-check"></i>Step 4: Update and commit gitignore</a></li>
<li class="chapter" data-level="" data-path="using-git-and-github.html"><a href="using-git-and-github.html#step-5-keep-adding-and-committing-files"><i class="fa fa-check"></i>Step 5: Keep adding and committing files</a></li>
</ul></li>
<li class="chapter" data-level="39.6" data-path="using-git-and-github.html"><a href="using-git-and-github.html#committing-and-pushing"><i class="fa fa-check"></i><b>39.6</b> Committing and pushing</a></li>
<li class="chapter" data-level="39.7" data-path="using-git-and-github.html"><a href="using-git-and-github.html#example-3-contribute-to-a-research-project"><i class="fa fa-check"></i><b>39.7</b> Example 3: Contribute to a research project</a>
<ul>
<li class="chapter" data-level="39.7.1" data-path="using-git-and-github.html"><a href="using-git-and-github.html#forking-a-repository"><i class="fa fa-check"></i><b>39.7.1</b> Forking a repository</a></li>
<li class="chapter" data-level="39.7.2" data-path="using-git-and-github.html"><a href="using-git-and-github.html#creating-a-pull-request"><i class="fa fa-check"></i><b>39.7.2</b> Creating a pull request</a></li>
</ul></li>
<li class="chapter" data-level="39.8" data-path="using-git-and-github.html"><a href="using-git-and-github.html#summary-5"><i class="fa fa-check"></i><b>39.8</b> Summary</a></li>
</ul></li>
<li class="part"><span><b>VIII Presenting Results</b></span></li>
<li class="chapter" data-level="40" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html"><i class="fa fa-check"></i><b>40</b> Creating tables with R and Microsoft Word</a>
<ul>
<li class="chapter" data-level="40.1" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#table-1"><i class="fa fa-check"></i><b>40.1</b> Table 1</a></li>
<li class="chapter" data-level="40.2" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#opioid-drug-use"><i class="fa fa-check"></i><b>40.2</b> Opioid drug use</a></li>
<li class="chapter" data-level="40.3" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#table-columns"><i class="fa fa-check"></i><b>40.3</b> Table columns</a></li>
<li class="chapter" data-level="40.4" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#table-rows"><i class="fa fa-check"></i><b>40.4</b> Table rows</a></li>
<li class="chapter" data-level="40.5" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#make-the-table-skeleton"><i class="fa fa-check"></i><b>40.5</b> Make the table skeleton</a></li>
<li class="chapter" data-level="40.6" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#fill-in-column-headers"><i class="fa fa-check"></i><b>40.6</b> Fill in column headers</a>
<ul>
<li class="chapter" data-level="40.6.1" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#group-sample-sizes"><i class="fa fa-check"></i><b>40.6.1</b> Group sample sizes</a></li>
<li class="chapter" data-level="40.6.2" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#formatting-column-headers"><i class="fa fa-check"></i><b>40.6.2</b> Formatting column headers</a></li>
</ul></li>
<li class="chapter" data-level="40.7" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#fill-in-row-headers"><i class="fa fa-check"></i><b>40.7</b> Fill in row headers</a>
<ul>
<li class="chapter" data-level="40.7.1" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#label-statistics"><i class="fa fa-check"></i><b>40.7.1</b> Label statistics</a></li>
<li class="chapter" data-level="40.7.2" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#formatting-row-headers"><i class="fa fa-check"></i><b>40.7.2</b> Formatting row headers</a></li>
</ul></li>
<li class="chapter" data-level="40.8" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#fill-in-data-values"><i class="fa fa-check"></i><b>40.8</b> Fill in data values</a>
<ul>
<li class="chapter" data-level="40.8.1" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#manually-type-values"><i class="fa fa-check"></i><b>40.8.1</b> Manually type values</a></li>
<li class="chapter" data-level="40.8.2" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#copy-and-paste-values"><i class="fa fa-check"></i><b>40.8.2</b> Copy and paste values</a></li>
<li class="chapter" data-level="40.8.3" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#knit-a-word-document"><i class="fa fa-check"></i><b>40.8.3</b> Knit a Word document</a></li>
<li class="chapter" data-level="40.8.4" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#flextable-and-officer"><i class="fa fa-check"></i><b>40.8.4</b> flextable and officer</a></li>
<li class="chapter" data-level="40.8.5" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#significant-digits"><i class="fa fa-check"></i><b>40.8.5</b> Significant digits</a></li>
<li class="chapter" data-level="40.8.6" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#formatting-data-values"><i class="fa fa-check"></i><b>40.8.6</b> Formatting data values</a></li>
</ul></li>
<li class="chapter" data-level="40.9" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#fill-in-title"><i class="fa fa-check"></i><b>40.9</b> Fill in title</a></li>
<li class="chapter" data-level="40.10" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#fill-in-footnotes"><i class="fa fa-check"></i><b>40.10</b> Fill in footnotes</a>
<ul>
<li class="chapter" data-level="40.10.1" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#formatting-footnotes"><i class="fa fa-check"></i><b>40.10.1</b> Formatting footnotes</a></li>
</ul></li>
<li class="chapter" data-level="40.11" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#final-formatting"><i class="fa fa-check"></i><b>40.11</b> Final formatting</a>
<ul>
<li class="chapter" data-level="40.11.1" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#adjust-column-widths"><i class="fa fa-check"></i><b>40.11.1</b> Adjust column widths</a></li>
<li class="chapter" data-level="40.11.2" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#merge-cells"><i class="fa fa-check"></i><b>40.11.2</b> Merge cells</a></li>
<li class="chapter" data-level="40.11.3" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#remove-cell-borders"><i class="fa fa-check"></i><b>40.11.3</b> Remove cell borders</a></li>
</ul></li>
<li class="chapter" data-level="40.12" data-path="creating-tables-with-r-and-microsoft-word.html"><a href="creating-tables-with-r-and-microsoft-word.html#summary-6"><i class="fa fa-check"></i><b>40.12</b> Summary</a></li>
</ul></li>
<li class="part"><span><b>IX Introduction to Epidemiology</b></span></li>
<li class="chapter" data-level="41" data-path="introduction-to-epidemiology.html"><a href="introduction-to-epidemiology.html"><i class="fa fa-check"></i><b>41</b> Introduction to Epidemiology</a>
<ul>
<li class="chapter" data-level="41.1" data-path="introduction-to-epidemiology.html"><a href="introduction-to-epidemiology.html#measurement"><i class="fa fa-check"></i><b>41.1</b> Measurement</a>
<ul>
<li class="chapter" data-level="41.1.1" data-path="introduction-to-epidemiology.html"><a href="introduction-to-epidemiology.html#descriptive-measures"><i class="fa fa-check"></i><b>41.1.1</b> Descriptive measures</a></li>
</ul></li>
<li class="chapter" data-level="41.2" data-path="introduction-to-epidemiology.html"><a href="introduction-to-epidemiology.html#uncertainty"><i class="fa fa-check"></i><b>41.2</b> Uncertainty</a>
<ul>
<li class="chapter" data-level="41.2.1" data-path="introduction-to-epidemiology.html"><a href="introduction-to-epidemiology.html#statistical-uncertainty"><i class="fa fa-check"></i><b>41.2.1</b> Statistical uncertainty</a></li>
<li class="chapter" data-level="41.2.2" data-path="introduction-to-epidemiology.html"><a href="introduction-to-epidemiology.html#uncertainty-in-the-research-process"><i class="fa fa-check"></i><b>41.2.2</b> Uncertainty in the research process</a></li>
<li class="chapter" data-level="41.2.3" data-path="introduction-to-epidemiology.html"><a href="introduction-to-epidemiology.html#epistemological-uncertainty"><i class="fa fa-check"></i><b>41.2.3</b> Epistemological uncertainty</a></li>
</ul></li>
<li class="chapter" data-level="41.3" data-path="introduction-to-epidemiology.html"><a href="introduction-to-epidemiology.html#study-design"><i class="fa fa-check"></i><b>41.3</b> Study design</a></li>
<li class="chapter" data-level="41.4" data-path="introduction-to-epidemiology.html"><a href="introduction-to-epidemiology.html#summary-7"><i class="fa fa-check"></i><b>41.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="42" data-path="populations.html"><a href="populations.html"><i class="fa fa-check"></i><b>42</b> Populations</a>
<ul>
<li class="chapter" data-level="42.1" data-path="populations.html"><a href="populations.html#open-and-closed-populations"><i class="fa fa-check"></i><b>42.1</b> Open and closed populations</a></li>
<li class="chapter" data-level="42.2" data-path="populations.html"><a href="populations.html#other-ways-to-define-populations"><i class="fa fa-check"></i><b>42.2</b> Other ways to define populations</a></li>
<li class="chapter" data-level="42.3" data-path="populations.html"><a href="populations.html#samples"><i class="fa fa-check"></i><b>42.3</b> Samples</a></li>
<li class="chapter" data-level="42.4" data-path="populations.html"><a href="populations.html#cohorts"><i class="fa fa-check"></i><b>42.4</b> Cohorts</a></li>
<li class="chapter" data-level="42.5" data-path="populations.html"><a href="populations.html#summary-8"><i class="fa fa-check"></i><b>42.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="43" data-path="measures-of-occurrence.html"><a href="measures-of-occurrence.html"><i class="fa fa-check"></i><b>43</b> Measures of Occurrence</a>
<ul>
<li class="chapter" data-level="43.1" data-path="measures-of-occurrence.html"><a href="measures-of-occurrence.html#terminology"><i class="fa fa-check"></i><b>43.1</b> Terminology</a>
<ul>
<li class="chapter" data-level="43.1.1" data-path="measures-of-occurrence.html"><a href="measures-of-occurrence.html#prevalence-and-incidence"><i class="fa fa-check"></i><b>43.1.1</b> Prevalence and incidence</a></li>
<li class="chapter" data-level="43.1.2" data-path="measures-of-occurrence.html"><a href="measures-of-occurrence.html#point-prevalence-and-period-prevalence"><i class="fa fa-check"></i><b>43.1.2</b> Point prevalence and period prevalence</a></li>
</ul></li>
<li class="chapter" data-level="43.2" data-path="measures-of-occurrence.html"><a href="measures-of-occurrence.html#quantifying-prevalence"><i class="fa fa-check"></i><b>43.2</b> Quantifying prevalence</a>
<ul>
<li class="chapter" data-level="43.2.1" data-path="measures-of-occurrence.html"><a href="measures-of-occurrence.html#prevalence-counts"><i class="fa fa-check"></i><b>43.2.1</b> Prevalence counts</a></li>
<li class="chapter" data-level="43.2.2" data-path="measures-of-occurrence.html"><a href="measures-of-occurrence.html#prevalence-proportion"><i class="fa fa-check"></i><b>43.2.2</b> Prevalence proportion</a></li>
<li class="chapter" data-level="43.2.3" data-path="measures-of-occurrence.html"><a href="measures-of-occurrence.html#prevalence-odds"><i class="fa fa-check"></i><b>43.2.3</b> Prevalence Odds</a></li>
</ul></li>
<li class="chapter" data-level="43.3" data-path="measures-of-occurrence.html"><a href="measures-of-occurrence.html#quantifying-incidence"><i class="fa fa-check"></i><b>43.3</b> Quantifying incidence</a>
<ul>
<li class="chapter" data-level="43.3.1" data-path="measures-of-occurrence.html"><a href="measures-of-occurrence.html#incidence-count"><i class="fa fa-check"></i><b>43.3.1</b> Incidence Count</a></li>
<li class="chapter" data-level="43.3.2" data-path="measures-of-occurrence.html"><a href="measures-of-occurrence.html#incidence-proportion"><i class="fa fa-check"></i><b>43.3.2</b> Incidence proportion</a></li>
<li class="chapter" data-level="43.3.3" data-path="measures-of-occurrence.html"><a href="measures-of-occurrence.html#incidence-odds"><i class="fa fa-check"></i><b>43.3.3</b> Incidence Odds</a></li>
<li class="chapter" data-level="43.3.4" data-path="measures-of-occurrence.html"><a href="measures-of-occurrence.html#incidence-rate"><i class="fa fa-check"></i><b>43.3.4</b> Incidence Rate</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>X Appendix</b></span></li>
<li class="chapter" data-level="" data-path="appendix-a-glossary.html"><a href="appendix-a-glossary.html"><i class="fa fa-check"></i>Appendix A: Glossary</a></li>
<li class="chapter" data-level="" data-path="appendix-alternative-table-formats.html"><a href="appendix-alternative-table-formats.html"><i class="fa fa-check"></i>Appendix: Alternative table formats</a>
<ul>
<li class="chapter" data-level="43.4" data-path="appendix-alternative-table-formats.html"><a href="appendix-alternative-table-formats.html#smaller-data-frame"><i class="fa fa-check"></i><b>43.4</b> Smaller data frame</a>
<ul>
<li class="chapter" data-level="43.4.1" data-path="appendix-alternative-table-formats.html"><a href="appendix-alternative-table-formats.html#default-method-for-printing-the-data-frame-to-the-screen"><i class="fa fa-check"></i><b>43.4.1</b> Default method for printing the data frame to the screen</a></li>
<li class="chapter" data-level="43.4.2" data-path="appendix-alternative-table-formats.html"><a href="appendix-alternative-table-formats.html#using-the-kable-function"><i class="fa fa-check"></i><b>43.4.2</b> Using the kable function</a></li>
<li class="chapter" data-level="43.4.3" data-path="appendix-alternative-table-formats.html"><a href="appendix-alternative-table-formats.html#using-the-datatable-function"><i class="fa fa-check"></i><b>43.4.3</b> Using the datatable function</a></li>
</ul></li>
<li class="chapter" data-level="43.5" data-path="appendix-alternative-table-formats.html"><a href="appendix-alternative-table-formats.html#larger-data-frame"><i class="fa fa-check"></i><b>43.5</b> Larger data frame</a>
<ul>
<li class="chapter" data-level="43.5.1" data-path="appendix-alternative-table-formats.html"><a href="appendix-alternative-table-formats.html#default-method-for-printing-the-data-frame-to-the-screen-1"><i class="fa fa-check"></i><b>43.5.1</b> Default method for printing the data frame to the screen</a></li>
<li class="chapter" data-level="43.5.2" data-path="appendix-alternative-table-formats.html"><a href="appendix-alternative-table-formats.html#using-the-kable-function-1"><i class="fa fa-check"></i><b>43.5.2</b> Using the kable function</a></li>
<li class="chapter" data-level="43.5.3" data-path="appendix-alternative-table-formats.html"><a href="appendix-alternative-table-formats.html#using-the-datatable-function-1"><i class="fa fa-check"></i><b>43.5.3</b> Using the datatable function</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R for Epidemiology</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="measures-of-occurrence" class="section level1 hasAnchor" number="43">
<h1><span class="header-section-number">43</span> Measures of Occurrence<a href="measures-of-occurrence.html#measures-of-occurrence" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<!-- 
Hidden comments placeholder
---------------------------

For more population plot code see: 
- Dropbox/Teaching/epi_3_public/modules/graphics/population_plots.Rmd
- Dropbox/Teaching/epi_3_public/modules/graphics/epi_3_graphics.Rmd

To preview:
bookdown::preview_chapter("chapters/10_part_intro_epi/03_measures_of_occurrence.Rmd")

Copy and paste:
👆**Here's what we did above:**

-->
<div class="under-construction">
<p><svg aria-hidden="true" role="img" viewBox="0 0 576 512" style="height:1em;width:1.12em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:#000000;overflow:visible;position:relative;"><path d="M413.5 237.5c-28.2 4.8-58.2-3.6-80-25.4l-38.1-38.1C280.4 159 272 138.8 272 117.6V105.5L192.3 62c-5.3-2.9-8.6-8.6-8.3-14.7s3.9-11.5 9.5-14l47.2-21C259.1 4.2 279 0 299.2 0h18.1c36.7 0 72 14 98.7 39.1l44.6 42c24.2 22.8 33.2 55.7 26.6 86L503 183l8-8c9.4-9.4 24.6-9.4 33.9 0l24 24c9.4 9.4 9.4 24.6 0 33.9l-88 88c-9.4 9.4-24.6 9.4-33.9 0l-24-24c-9.4-9.4-9.4-24.6 0-33.9l8-8-17.5-17.5zM27.4 377.1L260.9 182.6c3.5 4.9 7.5 9.6 11.8 14l38.1 38.1c6 6 12.4 11.2 19.2 15.7L134.9 484.6c-14.5 17.4-36 27.4-58.6 27.4C34.1 512 0 477.8 0 435.7c0-22.6 10.1-44.1 27.4-58.6z"/></svg> This chapter is under heavy development and may still undergo significant changes.</p>
</div>
<!-- Add a banner -->
<p>In the <a href="introduction-to-epidemiology.html#introduction-to-epidemiology">Introduction to Epidemiology</a> chapter, we said that epidemiology is usually defined as something like, “the study of the <em>occurrence</em> and distribution of health-related states or events in specified populations, including the study of the determinants influencing such states, and the application of this knowledge to control the health problems.”<span class="citation"><sup><a href="#ref-Porta2008-ij">16</a></sup></span> In this chapter, we begin to explore <em>how</em> we study the occurrence and distribution of these health-related states.</p>
<div class="note">
<p>🗒<strong>Side Note:</strong> Writing (and reading) “health-related states or events” over and over starts to get cumbersome after a while. Therefore, we will often just use “conditions” or “events” in the text below instead. Further, the methods we discuss below can just as easily be applied to better understanding characteristics of populations that would not typically be described as a “condition” or “event”. For example, sex assigned at birth or ethnicity.</p>
</div>
<p>We already learned some basic descriptive analysis techniques in the <a href="introduction-to-descriptive-analysis.html#introduction-to-descriptive-analysis">descriptive analysis</a> part of the book. If you haven’t read that part of the book yet, you may want to go back and do so now. Specifically, we already discussed:</p>
<ul>
<li>Methods for calculating the frequency with which each level (or category) of our categorical variables appears in our data.</li>
<li>Methods for calculating the percentage of observations in our data for which each level (or category) of our categorical variables appears.</li>
<li>Methods for calculating the center of our numerical variables.</li>
<li>Methods for calculating the dispersion of our numerical variables.</li>
</ul>
<p>In this chapter, and the chapters that follow, we will build on these basic descriptive measures, practice applying them to plausible public health scenarios, and pick up some new methods and terminology along the way. It may also be important to acknowledge up front that this chapter is heavily skewed towards methods for working with categorical outcomes (e.g., diabetes - yes or no) rather than numerical outcomes (e.g., blood sugar levels). This isn’t meant to imply that epidemiologists are never interested in investigating numerical outcomes – they are; however, many of the tools, methods, and theories used in epidemiology are geared towards working with categorical data.</p>
<div id="terminology" class="section level2 hasAnchor" number="43.1">
<h2><span class="header-section-number">43.1</span> Terminology<a href="measures-of-occurrence.html#terminology" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Before we get into calculating measures of occurrence, it may be a good idea to make sure that we are all on the same page with regard to some terms that will be used in this chapter.</p>
<!-- Add:
https://github.com/orgs/brad-cannell/projects/3/views/6?pane=issue&itemId=37768119
-->
<div id="prevalence-and-incidence" class="section level3 hasAnchor" number="43.1.1">
<h3><span class="header-section-number">43.1.1</span> Prevalence and incidence<a href="measures-of-occurrence.html#prevalence-and-incidence" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In our experience, if we walk up to a stranger on the street and ask them what they know about epidemiology, the most common response we will get is a blank stare. However, if that stranger does happen to know a little something about epidemiology, there is a good chance they will mention the words “incidence” or “prevalence”.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a> These two categories of occurrence measures have become really closely associated with the field of epidemiology for good reason. At some level, the vast majority of stories we tell as epidemiologists have to do with how many people currently have a particular health-related state (i.e., prevalence) or how frequently people are moving into a particular health-related state (i.e., incidence).</p>
<p>Notice that in the paragraph above we referred to prevalence and incidence as <em>categories</em> of occurrence measures. We did so because neither prevalence nor incidence are technically measures in and of themselves – they are more like concepts – and there are multiple different specific ways we can measure them both.</p>
<p>At a high-level, <strong>prevalence</strong> is our attempt to quantify how often a particular health-related state <em>exists</em> in our population of interest during a specified period of time. Sometimes we want to quantify how many people have <em>ever</em> had a particular health-related state, and sometimes we want to quantify how many people <em>currently</em> have a particular health-related state. For example, we might want to know the quantity of people in the United States who have ever had a measles infection at some point in their life, or we might want to know the quantity of people in the United States who currently have a measles infection right now. We can report those quantities as a counts, proportions, or odds.</p>
<p><strong>Incidence</strong>, on the other hand, is our attempt to quantify how frequently <em>new incidents</em> of a particular health-related state occur in our population of interest during a specified period of time. We may want to quantify the incidence of events that happen one time (e.g., diagnosis of Alzheimer’s disease or death), or we may want to quantify the incidence of events that can happen more than once (e.g., number of hip fractures), which are called <strong>recurrent events</strong>. For example, we might want to know the quantity of people in the United States who developed a new measles infection during the previous year. We can report that quantity as a count, a proportion, an odds, or a rate. In the sections that follow, we will we discuss the differences between these measures in greater detail and show you how to use R to calculate them.</p>
<p>The key difference between incidence and prevalence is that incidence is a measure of <em>new</em>, as opposed to <em>existing</em>, occurrences of the condition we are attempting to quantify. Said another way, incidence quantifies the <em>transition</em> from the absence of the condition to the presence of the condition <em>over a specified period of time</em>.<span class="citation"><sup><a href="#ref-Westreich2019-lg">18</a></sup></span></p>
</div>
<div id="point-prevalence-and-period-prevalence" class="section level3 hasAnchor" number="43.1.2">
<h3><span class="header-section-number">43.1.2</span> Point prevalence and period prevalence<a href="measures-of-occurrence.html#point-prevalence-and-period-prevalence" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Some readers who have already had an introduction to epidemiology may be aware that the concept of prevalence is sometimes broken down further into the complimentary concepts of <strong>point prevalence</strong> and <strong>period prevalence</strong>. As the names imply, point prevalence is supposed to quantify the prevalence of a health-related state at a particular point in time, and period prevalence is supposed to quantify the prevalence of a health-related state over a longer period of time. However, we find these terms to be somewhat ambiguous.</p>
<p>For example, if we want to estimate the point prevalence of heart disease in the United States, does that mean that we need to figure out if every single person in the United States has heart disease at the exact same moment in time, or even? If so, that hardly seems possible. Even if we only wanted to collect this information from a nationally representative sample of people, it still seems like a tall order. But, what if we ascertain everyone’s status at some point during a single day? Is that a point or a period? What if we do so at some point during a single month? What about a year? Well, we are unaware of any rule about what duration of time is short enough to be considered a “point” in time. Therefore, we don’t find the distinction between point prevalence and period prevalence to generally be particularly useful in practice. What <em>is</em> useful, actually <em>critical</em>, in practice is to make the time frame our results apply to perfectly clear whenever we interpret and report them.</p>
</div>
</div>
<div id="quantifying-prevalence" class="section level2 hasAnchor" number="43.2">
<h2><span class="header-section-number">43.2</span> Quantifying prevalence<a href="measures-of-occurrence.html#quantifying-prevalence" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="prevalence-counts" class="section level3 hasAnchor" number="43.2.1">
<h3><span class="header-section-number">43.2.1</span> Prevalence counts<a href="measures-of-occurrence.html#prevalence-counts" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Prevalence counts (or just “counts”) are perhaps the most basic measure of occurrence we can use. Prevalence counts tell us the number of people who are living with the condition that we are interested in. As the name implies, we simply count the number of people in our population of interest who have the characteristic we are interested in or who have experienced the event we are interested in. Like all counts, the prevalence count must be an integer value and ranges between 0 and the total number of people in the population who could potentially be living with the condition of interest. For example, let’s simulate a hypothetical population of 100 people.</p>
<div class="sourceCode" id="cb1680"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1680-1"><a href="measures-of-occurrence.html#cb1680-1" tabindex="-1"></a><span class="co"># Load the packages we will need below</span></span>
<span id="cb1680-2"><a href="measures-of-occurrence.html#cb1680-2" tabindex="-1"></a><span class="fu">library</span>(dplyr, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1680-3"><a href="measures-of-occurrence.html#cb1680-3" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code></pre></div>
<div class="sourceCode" id="cb1681"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1681-1"><a href="measures-of-occurrence.html#cb1681-1" tabindex="-1"></a><span class="co"># Set the seed for the random number generator so that we can reproduce our results</span></span>
<span id="cb1681-2"><a href="measures-of-occurrence.html#cb1681-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb1681-3"><a href="measures-of-occurrence.html#cb1681-3" tabindex="-1"></a></span>
<span id="cb1681-4"><a href="measures-of-occurrence.html#cb1681-4" tabindex="-1"></a><span class="co"># Create a 10x10 group of 100 people</span></span>
<span id="cb1681-5"><a href="measures-of-occurrence.html#cb1681-5" tabindex="-1"></a>pop_100 <span class="ot">&lt;-</span> tidyr<span class="sc">::</span><span class="fu">expand_grid</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="at">y =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>) <span class="sc">|&gt;</span> </span>
<span id="cb1681-6"><a href="measures-of-occurrence.html#cb1681-6" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">outcome =</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">&quot;No&quot;</span>, <span class="st">&quot;Yes&quot;</span>), <span class="dv">100</span>, <span class="cn">TRUE</span>, <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.5</span>)))</span></code></pre></div>
<p>All of the the people represented by a orange dot below experienced the event of interest. All of the people represented by a blue dot did not. We can simply count the number of people who experienced the event of interest and report it.</p>
<div class="sourceCode" id="cb1682"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1682-1"><a href="measures-of-occurrence.html#cb1682-1" tabindex="-1"></a><span class="co"># Plot the population as colored dots</span></span>
<span id="cb1682-2"><a href="measures-of-occurrence.html#cb1682-2" tabindex="-1"></a><span class="fu">ggplot</span>(pop_100, <span class="fu">aes</span>(x, y)) <span class="sc">+</span> </span>
<span id="cb1682-3"><a href="measures-of-occurrence.html#cb1682-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">10</span>, <span class="fu">aes</span>(<span class="at">color =</span> outcome)) <span class="sc">+</span></span>
<span id="cb1682-4"><a href="measures-of-occurrence.html#cb1682-4" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="st">&quot;Event&quot;</span>, <span class="at">values =</span> <span class="fu">c</span>(u_blue, u_orange)) <span class="sc">+</span></span>
<span id="cb1682-5"><a href="measures-of-occurrence.html#cb1682-5" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb1682-6"><a href="measures-of-occurrence.html#cb1682-6" tabindex="-1"></a>    <span class="at">panel.background =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb1682-7"><a href="measures-of-occurrence.html#cb1682-7" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb1682-8"><a href="measures-of-occurrence.html#cb1682-8" tabindex="-1"></a>    <span class="at">axis.text =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb1682-9"><a href="measures-of-occurrence.html#cb1682-9" tabindex="-1"></a>    <span class="at">axis.ticks =</span> <span class="fu">element_blank</span>()</span>
<span id="cb1682-10"><a href="measures-of-occurrence.html#cb1682-10" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="R-4-Epidemiology_files/figure-html/measures_of_occurrence_count_plot_01-1.png" width="672" /></p>
<p>To make our task a little easier, we will visually organize our figure by event. That is, we will arrange the population so that all of the people who did not experience the event of interest are located next to each other, and all of the people who did experience the event of interest are located next to each other.</p>
<p><img src="R-4-Epidemiology_files/figure-html/measures_of_occurrence_count_plot_02-1.png" width="672" /></p>
<p>After doing so, we can simply count the number of people who did and did not experience the event of interest. In this case, 53 and 47 respectively. However, we won’t typically want to calculate prevalence counts by plotting people and counting them as we did above. It makes a lot more sense for us to ask R to tell us how many people did and did not experience the event of interest. We learned a few different methods for asking R to do this in the chapter about <a href="numerical-descriptions-of-categorical-variables.html#numerical-descriptions-of-categorical-variables">numerical descriptions of categorical variables</a>. We will use one of those methods – the <code>table()</code> function – below to ask R to calculate the count of people in our population who did and did not experience the event of interest.</p>
<div class="sourceCode" id="cb1683"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1683-1"><a href="measures-of-occurrence.html#cb1683-1" tabindex="-1"></a><span class="fu">table</span>(pop_100<span class="sc">$</span>outcome)</span></code></pre></div>
<pre><code>## 
##  No Yes 
##  47  53</code></pre>
<p>Is that enough information? Well, it depends. What is our question? For example, let’s say that any person living with the event needs a ventilator, and we want to know if we have enough ventilators. In that case, simply knowing the count of people who are living with the event of interest may be all the information we need. On the other hand, if we want to know if “a lot” of people are living with the event of interest, then knowing the prevalence count alone may or may not be enough information. Said another way, prevalence counts tend to be most useful in communicating the public health importance of a condition or when we just want to get a sense of numbers of health-related events occurring in our population of interest. Regrettably, prevalence counts can also be used to exaggerate the public health importance of a condition. This can occur when we report prevalence counts that sound large without providing the information needed to put the numbers into context. Therefore, it is important for us to responsibly provide context to our audience when reporting prevalence counts (or any other measure of occurrence). Alternatively, we may want to consider reporting the prevalence proportion instead of (or in addition to) the prevalence count.</p>
</div>
<div id="prevalence-proportion" class="section level3 hasAnchor" number="43.2.2">
<h3><span class="header-section-number">43.2.2</span> Prevalence proportion<a href="measures-of-occurrence.html#prevalence-proportion" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As discussed above, prevalence counts can be useful in some circumstances. However, when epidemiologists think about prevalence, they are typically thinking about a prevalence proportion (or percentage). That is, the number of people who have the condition of interest divided by the total number of people in the population of interest.</p>
<!-- For Testing -->
<!-- $$\frac{Count\, of\, condition}{Total\, members\, of\, the\, population}$$ -->
<p><span class="math display" id="eq:prevalence-proportion">\[\begin{equation}
  \frac{Count\, of\, condition}{Total\, members\, of\, the\, population}
   \tag{43.1}
\end{equation}\]</span></p>
<p>Because no fewer than zero people in our population of interest can be living with the condition of interest, and no more than all of the people in our population of interest can be living with the condition of interest, the prevalence proportion will range between 0 and 1.</p>
<p>Let’s simulate some more data we can use to illustrate prevalence proportions and the other measures that will follow. In this simulated data, we are following 10 people over a 12-month period. Each month, we ascertain and record whether they have some disease or not.</p>
<div class="sourceCode" id="cb1685"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1685-1"><a href="measures-of-occurrence.html#cb1685-1" tabindex="-1"></a><span class="co"># Simulate data for 10 hypothetical people</span></span>
<span id="cb1685-2"><a href="measures-of-occurrence.html#cb1685-2" tabindex="-1"></a><span class="co"># From Lash TL, VanderWeel TJ, Haneuse S, Rothman KJ. Modern Epidemiology. fourth. Wolters Kluwer; 2021.</span></span>
<span id="cb1685-3"><a href="measures-of-occurrence.html#cb1685-3" tabindex="-1"></a>people <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span></span>
<span id="cb1685-4"><a href="measures-of-occurrence.html#cb1685-4" tabindex="-1"></a>months <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">1</span><span class="sc">:</span><span class="dv">12</span></span>
<span id="cb1685-5"><a href="measures-of-occurrence.html#cb1685-5" tabindex="-1"></a>pop_10 <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(<span class="at">person =</span> people, <span class="at">month =</span> months)</span>
<span id="cb1685-6"><a href="measures-of-occurrence.html#cb1685-6" tabindex="-1"></a>rows_per_person <span class="ot">&lt;-</span> <span class="fu">length</span>(months)</span>
<span id="cb1685-7"><a href="measures-of-occurrence.html#cb1685-7" tabindex="-1"></a></span>
<span id="cb1685-8"><a href="measures-of-occurrence.html#cb1685-8" tabindex="-1"></a><span class="co"># Count from the beginning of each month.</span></span>
<span id="cb1685-9"><a href="measures-of-occurrence.html#cb1685-9" tabindex="-1"></a><span class="co"># So, person 2 is pre-follow-up at the beginning of time 1 (month -01), at risk </span></span>
<span id="cb1685-10"><a href="measures-of-occurrence.html#cb1685-10" tabindex="-1"></a><span class="co"># at the beginning of time 2 (month 00), at risk at the beginning of time 3 </span></span>
<span id="cb1685-11"><a href="measures-of-occurrence.html#cb1685-11" tabindex="-1"></a><span class="co"># (month 01), diseased at the beginning of time 4 (month 02), etc.</span></span>
<span id="cb1685-12"><a href="measures-of-occurrence.html#cb1685-12" tabindex="-1"></a>p01 <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="st">&quot;Diseased&quot;</span>, rows_per_person)</span>
<span id="cb1685-13"><a href="measures-of-occurrence.html#cb1685-13" tabindex="-1"></a>p02 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;Pre-follow-up&quot;</span>, <span class="dv">1</span>), <span class="fu">rep</span>(<span class="st">&quot;At Risk&quot;</span>, <span class="dv">2</span>), <span class="fu">rep</span>(<span class="st">&quot;Diseased&quot;</span>, <span class="dv">3</span>), <span class="fu">rep</span>(<span class="st">&quot;Deceased&quot;</span>, <span class="dv">8</span>))</span>
<span id="cb1685-14"><a href="measures-of-occurrence.html#cb1685-14" tabindex="-1"></a>p03 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;Pre-follow-up&quot;</span>, <span class="dv">1</span>), <span class="fu">rep</span>(<span class="st">&quot;At Risk&quot;</span>, <span class="dv">4</span>), <span class="fu">rep</span>(<span class="st">&quot;Diseased&quot;</span>, <span class="dv">9</span>), <span class="fu">rep</span>(<span class="st">&quot;Deceased&quot;</span>, <span class="dv">0</span>))</span>
<span id="cb1685-15"><a href="measures-of-occurrence.html#cb1685-15" tabindex="-1"></a>p04 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;Pre-follow-up&quot;</span>, <span class="dv">1</span>), <span class="fu">rep</span>(<span class="st">&quot;At Risk&quot;</span>, <span class="dv">5</span>), <span class="fu">rep</span>(<span class="st">&quot;Diseased&quot;</span>, <span class="dv">8</span>), <span class="fu">rep</span>(<span class="st">&quot;Deceased&quot;</span>, <span class="dv">0</span>))</span>
<span id="cb1685-16"><a href="measures-of-occurrence.html#cb1685-16" tabindex="-1"></a>p05 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;Pre-follow-up&quot;</span>, <span class="dv">1</span>), <span class="fu">rep</span>(<span class="st">&quot;At Risk&quot;</span>, <span class="dv">7</span>), <span class="fu">rep</span>(<span class="st">&quot;Diseased&quot;</span>, <span class="dv">6</span>), <span class="fu">rep</span>(<span class="st">&quot;Deceased&quot;</span>, <span class="dv">0</span>))</span>
<span id="cb1685-17"><a href="measures-of-occurrence.html#cb1685-17" tabindex="-1"></a>p06 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;Pre-follow-up&quot;</span>, <span class="dv">1</span>), <span class="fu">rep</span>(<span class="st">&quot;At Risk&quot;</span>, <span class="dv">8</span>), <span class="fu">rep</span>(<span class="st">&quot;Diseased&quot;</span>, <span class="dv">3</span>), <span class="fu">rep</span>(<span class="st">&quot;Deceased&quot;</span>, <span class="dv">2</span>))</span>
<span id="cb1685-18"><a href="measures-of-occurrence.html#cb1685-18" tabindex="-1"></a>p07 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;Pre-follow-up&quot;</span>, <span class="dv">1</span>), <span class="fu">rep</span>(<span class="st">&quot;At Risk&quot;</span>, <span class="dv">9</span>), <span class="fu">rep</span>(<span class="st">&quot;Diseased&quot;</span>, <span class="dv">0</span>), <span class="fu">rep</span>(<span class="st">&quot;Deceased&quot;</span>, <span class="dv">4</span>))</span>
<span id="cb1685-19"><a href="measures-of-occurrence.html#cb1685-19" tabindex="-1"></a>p08 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;Pre-follow-up&quot;</span>, <span class="dv">1</span>), <span class="fu">rep</span>(<span class="st">&quot;At Risk&quot;</span>, <span class="dv">5</span>), <span class="fu">rep</span>(<span class="st">&quot;Diseased&quot;</span>, <span class="dv">0</span>), <span class="fu">rep</span>(<span class="st">&quot;Deceased&quot;</span>, <span class="dv">8</span>))</span>
<span id="cb1685-20"><a href="measures-of-occurrence.html#cb1685-20" tabindex="-1"></a>p09 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;Pre-follow-up&quot;</span>, <span class="dv">1</span>), <span class="fu">rep</span>(<span class="st">&quot;At Risk&quot;</span>, <span class="dv">13</span>), <span class="fu">rep</span>(<span class="st">&quot;Diseased&quot;</span>, <span class="dv">0</span>), <span class="fu">rep</span>(<span class="st">&quot;Deceased&quot;</span>, <span class="dv">0</span>))</span>
<span id="cb1685-21"><a href="measures-of-occurrence.html#cb1685-21" tabindex="-1"></a>p10 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;Pre-follow-up&quot;</span>, <span class="dv">1</span>), <span class="fu">rep</span>(<span class="st">&quot;At Risk&quot;</span>, <span class="dv">13</span>), <span class="fu">rep</span>(<span class="st">&quot;Diseased&quot;</span>, <span class="dv">0</span>), <span class="fu">rep</span>(<span class="st">&quot;Deceased&quot;</span>, <span class="dv">0</span>))</span>
<span id="cb1685-22"><a href="measures-of-occurrence.html#cb1685-22" tabindex="-1"></a>status <span class="ot">&lt;-</span> <span class="fu">c</span>(p01, p02, p03, p04, p05, p06, p07, p08, p09, p10)</span>
<span id="cb1685-23"><a href="measures-of-occurrence.html#cb1685-23" tabindex="-1"></a></span>
<span id="cb1685-24"><a href="measures-of-occurrence.html#cb1685-24" tabindex="-1"></a><span class="co"># Add status to pop_10</span></span>
<span id="cb1685-25"><a href="measures-of-occurrence.html#cb1685-25" tabindex="-1"></a>pop_10<span class="sc">$</span>status <span class="ot">&lt;-</span> status</span>
<span id="cb1685-26"><a href="measures-of-occurrence.html#cb1685-26" tabindex="-1"></a></span>
<span id="cb1685-27"><a href="measures-of-occurrence.html#cb1685-27" tabindex="-1"></a><span class="co"># Create factor versions of person and status</span></span>
<span id="cb1685-28"><a href="measures-of-occurrence.html#cb1685-28" tabindex="-1"></a>pop_10 <span class="ot">&lt;-</span> pop_10 <span class="sc">|&gt;</span> </span>
<span id="cb1685-29"><a href="measures-of-occurrence.html#cb1685-29" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1685-30"><a href="measures-of-occurrence.html#cb1685-30" tabindex="-1"></a>    <span class="at">person_f =</span> <span class="fu">factor</span>(person, <span class="at">labels =</span> <span class="fu">c</span>(<span class="fu">paste0</span>(<span class="dv">0</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>), <span class="st">&quot;10&quot;</span>)),</span>
<span id="cb1685-31"><a href="measures-of-occurrence.html#cb1685-31" tabindex="-1"></a>    <span class="at">status_f =</span> <span class="fu">factor</span>(status, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;Pre-follow-up&quot;</span>, <span class="st">&quot;At Risk&quot;</span>, <span class="st">&quot;Diseased&quot;</span>, <span class="st">&quot;Deceased&quot;</span>))</span>
<span id="cb1685-32"><a href="measures-of-occurrence.html#cb1685-32" tabindex="-1"></a>  )</span>
<span id="cb1685-33"><a href="measures-of-occurrence.html#cb1685-33" tabindex="-1"></a></span>
<span id="cb1685-34"><a href="measures-of-occurrence.html#cb1685-34" tabindex="-1"></a><span class="co"># Add coordinates for line segments in the plot</span></span>
<span id="cb1685-35"><a href="measures-of-occurrence.html#cb1685-35" tabindex="-1"></a>pop_10_wide <span class="ot">&lt;-</span> pop_10 <span class="sc">|&gt;</span> </span>
<span id="cb1685-36"><a href="measures-of-occurrence.html#cb1685-36" tabindex="-1"></a>  <span class="fu">group_by</span>(person_f, status_f) <span class="sc">|&gt;</span> </span>
<span id="cb1685-37"><a href="measures-of-occurrence.html#cb1685-37" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1685-38"><a href="measures-of-occurrence.html#cb1685-38" tabindex="-1"></a>    <span class="at">x    =</span> <span class="fu">min</span>(month),</span>
<span id="cb1685-39"><a href="measures-of-occurrence.html#cb1685-39" tabindex="-1"></a>    <span class="at">xend =</span> <span class="fu">max</span>(month)</span>
<span id="cb1685-40"><a href="measures-of-occurrence.html#cb1685-40" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb1685-41"><a href="measures-of-occurrence.html#cb1685-41" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span> </span>
<span id="cb1685-42"><a href="measures-of-occurrence.html#cb1685-42" tabindex="-1"></a>  <span class="co"># Keep distinct values only</span></span>
<span id="cb1685-43"><a href="measures-of-occurrence.html#cb1685-43" tabindex="-1"></a>  <span class="fu">distinct</span>(person, status, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> </span>
<span id="cb1685-44"><a href="measures-of-occurrence.html#cb1685-44" tabindex="-1"></a>  <span class="co"># Make the line ends touch</span></span>
<span id="cb1685-45"><a href="measures-of-occurrence.html#cb1685-45" tabindex="-1"></a>  <span class="fu">group_by</span>(person) <span class="sc">|&gt;</span> </span>
<span id="cb1685-46"><a href="measures-of-occurrence.html#cb1685-46" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1685-47"><a href="measures-of-occurrence.html#cb1685-47" tabindex="-1"></a>    <span class="at">xend_adjusted =</span> <span class="fu">lead</span>(x),</span>
<span id="cb1685-48"><a href="measures-of-occurrence.html#cb1685-48" tabindex="-1"></a>    <span class="at">xend_adjusted =</span> <span class="fu">if_else</span>(<span class="fu">is.na</span>(xend_adjusted), xend, xend_adjusted)</span>
<span id="cb1685-49"><a href="measures-of-occurrence.html#cb1685-49" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb1685-50"><a href="measures-of-occurrence.html#cb1685-50" tabindex="-1"></a>  <span class="fu">relocate</span>(xend_adjusted, <span class="at">.after =</span> xend) <span class="sc">|&gt;</span> </span>
<span id="cb1685-51"><a href="measures-of-occurrence.html#cb1685-51" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb1685-52"><a href="measures-of-occurrence.html#cb1685-52" tabindex="-1"></a></span>
<span id="cb1685-53"><a href="measures-of-occurrence.html#cb1685-53" tabindex="-1"></a><span class="co"># Print pop_10 to the screen</span></span>
<span id="cb1685-54"><a href="measures-of-occurrence.html#cb1685-54" tabindex="-1"></a>pop_10</span></code></pre></div>
<pre><code>## # A tibble: 140 × 5
##    person month status   person_f status_f
##     &lt;int&gt; &lt;int&gt; &lt;chr&gt;    &lt;fct&gt;    &lt;fct&gt;   
##  1      1    -1 Diseased 01       Diseased
##  2      1     0 Diseased 01       Diseased
##  3      1     1 Diseased 01       Diseased
##  4      1     2 Diseased 01       Diseased
##  5      1     3 Diseased 01       Diseased
##  6      1     4 Diseased 01       Diseased
##  7      1     5 Diseased 01       Diseased
##  8      1     6 Diseased 01       Diseased
##  9      1     7 Diseased 01       Diseased
## 10      1     8 Diseased 01       Diseased
## # ℹ 130 more rows</code></pre>
<p>Next, let’s create a figure from our simulated data to make it easier to visualize. Time is represented on the x-axis of the figure as months from each person’s baseline visit, shown as month 0. Each bar running parallel to the x-axis represents one person’s health status during the 12 months of follow-up.</p>
<div class="sourceCode" id="cb1687"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1687-1"><a href="measures-of-occurrence.html#cb1687-1" tabindex="-1"></a><span class="co"># Create the figure</span></span>
<span id="cb1687-2"><a href="measures-of-occurrence.html#cb1687-2" tabindex="-1"></a>pop_10_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(pop_10_wide) <span class="sc">+</span></span>
<span id="cb1687-3"><a href="measures-of-occurrence.html#cb1687-3" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">xend =</span> xend_adjusted, <span class="at">y =</span> <span class="dv">1</span>, <span class="at">yend =</span> <span class="dv">1</span>, <span class="at">color =</span> status_f), <span class="at">size =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb1687-4"><a href="measures-of-occurrence.html#cb1687-4" tabindex="-1"></a>  <span class="co"># Show all months</span></span>
<span id="cb1687-5"><a href="measures-of-occurrence.html#cb1687-5" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="st">&quot;Month Follow-up&quot;</span>, <span class="at">breaks =</span> <span class="sc">-</span><span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb1687-6"><a href="measures-of-occurrence.html#cb1687-6" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="fu">vars</span>(person_f), <span class="at">nrow =</span> <span class="dv">10</span>, <span class="at">strip.position =</span> <span class="st">&quot;left&quot;</span>) <span class="sc">+</span></span>
<span id="cb1687-7"><a href="measures-of-occurrence.html#cb1687-7" tabindex="-1"></a>  <span class="co"># Add a line marking the start of follow up</span></span>
<span id="cb1687-8"><a href="measures-of-occurrence.html#cb1687-8" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb1687-9"><a href="measures-of-occurrence.html#cb1687-9" tabindex="-1"></a>  <span class="co"># Add vertical lines to mark the start of each month</span></span>
<span id="cb1687-10"><a href="measures-of-occurrence.html#cb1687-10" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>, <span class="at">color =</span> <span class="st">&quot;#f9f9f9&quot;</span>) <span class="sc">+</span></span>
<span id="cb1687-11"><a href="measures-of-occurrence.html#cb1687-11" tabindex="-1"></a>  <span class="co"># Change fill colors</span></span>
<span id="cb1687-12"><a href="measures-of-occurrence.html#cb1687-12" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="st">&quot;Status&quot;</span>, <span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;gray&quot;</span>, <span class="st">&quot;orange&quot;</span>, <span class="st">&quot;red&quot;</span>, <span class="st">&quot;black&quot;</span>, <span class="st">&quot;#4682B4&quot;</span>)) <span class="sc">+</span></span>
<span id="cb1687-13"><a href="measures-of-occurrence.html#cb1687-13" tabindex="-1"></a>  <span class="co"># Change y-axis label</span></span>
<span id="cb1687-14"><a href="measures-of-occurrence.html#cb1687-14" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Person&quot;</span>) <span class="sc">+</span></span>
<span id="cb1687-15"><a href="measures-of-occurrence.html#cb1687-15" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb1687-16"><a href="measures-of-occurrence.html#cb1687-16" tabindex="-1"></a>    <span class="co"># Remove gray background</span></span>
<span id="cb1687-17"><a href="measures-of-occurrence.html#cb1687-17" tabindex="-1"></a>    <span class="at">panel.background =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb1687-18"><a href="measures-of-occurrence.html#cb1687-18" tabindex="-1"></a>    <span class="co"># Remove the &quot;p&quot; from the x axis</span></span>
<span id="cb1687-19"><a href="measures-of-occurrence.html#cb1687-19" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb1687-20"><a href="measures-of-occurrence.html#cb1687-20" tabindex="-1"></a>    <span class="at">axis.ticks.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb1687-21"><a href="measures-of-occurrence.html#cb1687-21" tabindex="-1"></a>    <span class="co"># Move legend</span></span>
<span id="cb1687-22"><a href="measures-of-occurrence.html#cb1687-22" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>,</span>
<span id="cb1687-23"><a href="measures-of-occurrence.html#cb1687-23" tabindex="-1"></a>    <span class="co"># Change the color and style of the &quot;months&quot; axis </span></span>
<span id="cb1687-24"><a href="measures-of-occurrence.html#cb1687-24" tabindex="-1"></a>    <span class="at">axis.line.x =</span> <span class="fu">element_line</span>(</span>
<span id="cb1687-25"><a href="measures-of-occurrence.html#cb1687-25" tabindex="-1"></a>      <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">arrow =</span> grid<span class="sc">::</span><span class="fu">arrow</span>(<span class="at">length =</span> <span class="fu">unit</span>(<span class="fl">0.1</span>, <span class="st">&quot;inches&quot;</span>), <span class="at">type =</span> <span class="st">&quot;closed&quot;</span>)</span>
<span id="cb1687-26"><a href="measures-of-occurrence.html#cb1687-26" tabindex="-1"></a>    ),</span>
<span id="cb1687-27"><a href="measures-of-occurrence.html#cb1687-27" tabindex="-1"></a>    <span class="co"># Rotate the facet label to the right</span></span>
<span id="cb1687-28"><a href="measures-of-occurrence.html#cb1687-28" tabindex="-1"></a>    <span class="at">strip.text.y.left =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">0</span>)</span>
<span id="cb1687-29"><a href="measures-of-occurrence.html#cb1687-29" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="img/10_part_intro_epi/03_measures_of_occurrence/pop_10_plot.png" width="1094" /></p>
<p>Now, let’s say that we come along and decide to do a study with the people in our simulated population of interest. Using equation <a href="measures-of-occurrence.html#eq:prevalence-proportion">(43.1)</a>, what is the prevalence proportion of disease over the 12 months of follow-up?</p>
<p>The prevalence proportion of disease is equal to the number of people with disease divided by the number of people in the sample. In this case, that would be 6 people (persons 01 through 06) divided by 10.</p>
<p><span class="math display">\[\frac{6}{10} = 0.6 \hspace{1.5mm} or \hspace{1.5mm} 60\%\]</span></p>
<p>Among the members of our population, the prevalence of disease during the 12-month follow-up period was 0.6. Said another way, 60% of our population had the disease during the 12-month follow-up period.</p>
<div id="calculating-prevalence-proportions-with-r" class="section level4 hasAnchor" number="43.2.2.1">
<h4><span class="header-section-number">43.2.2.1</span> Calculating prevalence proportions with R<a href="measures-of-occurrence.html#calculating-prevalence-proportions-with-r" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Now, let’s look at some ways we can calculate a prevalence proportion with R.</p>
<p>One way (of many) to calculate prevalence proportions is to create objects matching the elements of our equation above and then assign the relevant values to those objects. An advantage of using this method is that the objects are reusable later if we need them. For example:</p>
<div class="sourceCode" id="cb1688"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1688-1"><a href="measures-of-occurrence.html#cb1688-1" tabindex="-1"></a><span class="co"># Create a vector containing the number of people with the condition of interest</span></span>
<span id="cb1688-2"><a href="measures-of-occurrence.html#cb1688-2" tabindex="-1"></a>n_condition <span class="ot">&lt;-</span> <span class="dv">6</span></span>
<span id="cb1688-3"><a href="measures-of-occurrence.html#cb1688-3" tabindex="-1"></a><span class="co"># Create a vector containing the number of people in the population of interest</span></span>
<span id="cb1688-4"><a href="measures-of-occurrence.html#cb1688-4" tabindex="-1"></a>n_population <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb1688-5"><a href="measures-of-occurrence.html#cb1688-5" tabindex="-1"></a><span class="co"># Calculate the prevalence proportion and assign it to an object called </span></span>
<span id="cb1688-6"><a href="measures-of-occurrence.html#cb1688-6" tabindex="-1"></a><span class="co"># prevalence_prop</span></span>
<span id="cb1688-7"><a href="measures-of-occurrence.html#cb1688-7" tabindex="-1"></a>prevalence_prop <span class="ot">&lt;-</span> n_condition <span class="sc">/</span> n_population</span>
<span id="cb1688-8"><a href="measures-of-occurrence.html#cb1688-8" tabindex="-1"></a><span class="co"># Print the value stored in prevalence_prop to the screen</span></span>
<span id="cb1688-9"><a href="measures-of-occurrence.html#cb1688-9" tabindex="-1"></a>prevalence_prop</span></code></pre></div>
<pre><code>## [1] 0.6</code></pre>
<p>We can also simply use R like a fancy calculator. An advantage of this method is that it is quick and easy to understand.</p>
<div class="sourceCode" id="cb1690"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1690-1"><a href="measures-of-occurrence.html#cb1690-1" tabindex="-1"></a><span class="dv">6</span> <span class="sc">/</span> <span class="dv">10</span></span></code></pre></div>
<pre><code>## [1] 0.6</code></pre>
<p>Additionally, we can simply multiply proportions by 100 to convert them to percentages.</p>
<div class="sourceCode" id="cb1692"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1692-1"><a href="measures-of-occurrence.html#cb1692-1" tabindex="-1"></a>(<span class="dv">6</span> <span class="sc">/</span> <span class="dv">10</span>) <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div>
<pre><code>## [1] 60</code></pre>
<p>And converting the value stored in the <code>prevalence_prop</code> object works exactly the same way.</p>
<div class="sourceCode" id="cb1694"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1694-1"><a href="measures-of-occurrence.html#cb1694-1" tabindex="-1"></a><span class="co"># Convert the value in prevalence_prop to a percentage and assign it to a new</span></span>
<span id="cb1694-2"><a href="measures-of-occurrence.html#cb1694-2" tabindex="-1"></a><span class="co"># object called prevalence_percent</span></span>
<span id="cb1694-3"><a href="measures-of-occurrence.html#cb1694-3" tabindex="-1"></a>prevalence_percent <span class="ot">&lt;-</span> prevalence_prop <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb1694-4"><a href="measures-of-occurrence.html#cb1694-4" tabindex="-1"></a><span class="co"># Print the value stored in prevalence_percent to the screen</span></span>
<span id="cb1694-5"><a href="measures-of-occurrence.html#cb1694-5" tabindex="-1"></a>prevalence_percent</span></code></pre></div>
<pre><code>## [1] 60</code></pre>
<p>Sometime, it can be useful to add a percent sign to the value for reporting purposes. We can add a percent sign using the <code>paste0()</code> function as shown below. Just keep in mind adding the percent sign turns our value into a <em>character string</em>. It will no longer have a numeric value to R.</p>
<div class="sourceCode" id="cb1696"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1696-1"><a href="measures-of-occurrence.html#cb1696-1" tabindex="-1"></a><span class="co"># Add percent sign to the value in prevalence_percent</span></span>
<span id="cb1696-2"><a href="measures-of-occurrence.html#cb1696-2" tabindex="-1"></a>prevalence_percent <span class="ot">&lt;-</span> <span class="fu">paste0</span>(prevalence_percent, <span class="st">&quot;%&quot;</span>)</span>
<span id="cb1696-3"><a href="measures-of-occurrence.html#cb1696-3" tabindex="-1"></a><span class="co"># Print the value stored in prevalence_percent_formatted to the screen</span></span>
<span id="cb1696-4"><a href="measures-of-occurrence.html#cb1696-4" tabindex="-1"></a>prevalence_percent</span></code></pre></div>
<pre><code>## [1] &quot;60%&quot;</code></pre>
<p>Sometimes, it can be useful simulate and analyze a little data frame with the characteristics of interest.</p>
<div class="sourceCode" id="cb1698"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1698-1"><a href="measures-of-occurrence.html#cb1698-1" tabindex="-1"></a><span class="co"># Simulate a small data frame that has the characteristics we are interested in.</span></span>
<span id="cb1698-2"><a href="measures-of-occurrence.html#cb1698-2" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb1698-3"><a href="measures-of-occurrence.html#cb1698-3" tabindex="-1"></a>  <span class="at">id =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>,</span>
<span id="cb1698-4"><a href="measures-of-occurrence.html#cb1698-4" tabindex="-1"></a>  <span class="at">disease =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">6</span>), <span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">4</span>))</span>
<span id="cb1698-5"><a href="measures-of-occurrence.html#cb1698-5" tabindex="-1"></a>)</span>
<span id="cb1698-6"><a href="measures-of-occurrence.html#cb1698-6" tabindex="-1"></a></span>
<span id="cb1698-7"><a href="measures-of-occurrence.html#cb1698-7" tabindex="-1"></a><span class="co"># Print the simulated data to the screen</span></span>
<span id="cb1698-8"><a href="measures-of-occurrence.html#cb1698-8" tabindex="-1"></a>df</span></code></pre></div>
<pre><code>## # A tibble: 10 × 2
##       id disease
##    &lt;int&gt;   &lt;dbl&gt;
##  1     1       1
##  2     2       1
##  3     3       1
##  4     4       1
##  5     5       1
##  6     6       1
##  7     7       0
##  8     8       0
##  9     9       0
## 10    10       0</code></pre>
<p>We can then analyze the data using the methods we learned in the <a href="introduction-to-descriptive-analysis.html#introduction-to-descriptive-analysis">descriptive analysis</a> part of the book.</p>
<div class="sourceCode" id="cb1700"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1700-1"><a href="measures-of-occurrence.html#cb1700-1" tabindex="-1"></a><span class="co"># Load the freqtables package</span></span>
<span id="cb1700-2"><a href="measures-of-occurrence.html#cb1700-2" tabindex="-1"></a><span class="fu">library</span>(freqtables)</span></code></pre></div>
<div class="sourceCode" id="cb1701"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1701-1"><a href="measures-of-occurrence.html#cb1701-1" tabindex="-1"></a><span class="co"># Calculate the prevalence proportion (and other measures) and assign them to a </span></span>
<span id="cb1701-2"><a href="measures-of-occurrence.html#cb1701-2" tabindex="-1"></a><span class="co"># new object called results</span></span>
<span id="cb1701-3"><a href="measures-of-occurrence.html#cb1701-3" tabindex="-1"></a>results <span class="ot">&lt;-</span> df <span class="sc">|&gt;</span> </span>
<span id="cb1701-4"><a href="measures-of-occurrence.html#cb1701-4" tabindex="-1"></a>  <span class="fu">freq_table</span>(disease)</span>
<span id="cb1701-5"><a href="measures-of-occurrence.html#cb1701-5" tabindex="-1"></a></span>
<span id="cb1701-6"><a href="measures-of-occurrence.html#cb1701-6" tabindex="-1"></a><span class="co"># Print the value stored in results to the screen</span></span>
<span id="cb1701-7"><a href="measures-of-occurrence.html#cb1701-7" tabindex="-1"></a>results</span></code></pre></div>
<pre><code>## # A tibble: 2 × 9
##   var     cat       n n_total percent    se t_crit   lcl   ucl
##   &lt;chr&gt;   &lt;chr&gt; &lt;int&gt;   &lt;int&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 disease 0         4      10      40  16.3   2.26  12.5  75.7
## 2 disease 1         6      10      60  16.3   2.26  24.3  87.5</code></pre>
<p>We can even grab specific values from our results that we can reuse later. For example, let’s grab the prevalence percent from our results and store them as an object in our global environment.</p>
<div class="sourceCode" id="cb1703"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1703-1"><a href="measures-of-occurrence.html#cb1703-1" tabindex="-1"></a><span class="co"># Assign the percent values from the results object to a new object called</span></span>
<span id="cb1703-2"><a href="measures-of-occurrence.html#cb1703-2" tabindex="-1"></a><span class="co"># prevalence_percent</span></span>
<span id="cb1703-3"><a href="measures-of-occurrence.html#cb1703-3" tabindex="-1"></a>prevalence_percent <span class="ot">&lt;-</span> results <span class="sc">|&gt;</span> </span>
<span id="cb1703-4"><a href="measures-of-occurrence.html#cb1703-4" tabindex="-1"></a>  <span class="fu">filter</span>(cat <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">|&gt;</span>  <span class="co"># Keep only the row with cat == 1</span></span>
<span id="cb1703-5"><a href="measures-of-occurrence.html#cb1703-5" tabindex="-1"></a>  <span class="fu">pull</span>(percent)        <span class="co"># Keep only the value of percent from that row</span></span>
<span id="cb1703-6"><a href="measures-of-occurrence.html#cb1703-6" tabindex="-1"></a></span>
<span id="cb1703-7"><a href="measures-of-occurrence.html#cb1703-7" tabindex="-1"></a><span class="co"># Print the value stored in prevalence_percent to the screen</span></span>
<span id="cb1703-8"><a href="measures-of-occurrence.html#cb1703-8" tabindex="-1"></a>prevalence_percent</span></code></pre></div>
<pre><code>## [1] 60</code></pre>
<p>We can also use base R’s <a href="lets-get-programming.html#bracket-notation">bracket notation</a> if we prefer.</p>
<div class="sourceCode" id="cb1705"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1705-1"><a href="measures-of-occurrence.html#cb1705-1" tabindex="-1"></a>prevalence_percent <span class="ot">&lt;-</span> results<span class="sc">$</span>percent[<span class="dv">2</span>]</span>
<span id="cb1705-2"><a href="measures-of-occurrence.html#cb1705-2" tabindex="-1"></a>prevalence_percent</span></code></pre></div>
<pre><code>## [1] 60</code></pre>
</div>
<div id="interpretation" class="section level4 hasAnchor" number="43.2.2.2">
<h4><span class="header-section-number">43.2.2.2</span> Interpretation<a href="measures-of-occurrence.html#interpretation" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>And here are some ways that we can interpret the prevalence proportion we calculated above.</p>
<ol style="list-style-type: decimal">
<li><p>Among the members of our population, the prevalence of disease over the 12-month follow-up period was 0.6.</p></li>
<li><p>Among the members of our population, 60% had disease over the 12-month follow-up period.</p></li>
<li><p>Sixty percent of the members of our population had disease over the 12-month follow-up period.</p></li>
<li><p>The prevalence of disease in our population over the 12-month follow-up period was 0.60 (or 60%).</p></li>
</ol>
</div>
</div>
<div id="prevalence-odds" class="section level3 hasAnchor" number="43.2.3">
<h3><span class="header-section-number">43.2.3</span> Prevalence Odds<a href="measures-of-occurrence.html#prevalence-odds" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The prevalence odds are less familiar to many people and may feel more awkward to use. However, the prevalence odds are simply a function of the prevalence proportion. Specifically, the prevalence odds are equal to the prevalence proportion divided by 1 minus the prevalence proportion. Why do we calculate the prevalence odds? Well, we generally don’t calculate the prevalence odds manually as we will do below; however, sometimes the prevalence odds are conveniently returned from regression models we will learn to use later in the book. Therefore, a gentle introduction to prevalence odds here may come in handy later.</p>
<!-- For Testing -->
<!-- $$\frac{Prevalence\, proportion}{1 - Prevalence\, proportion}$$ -->
<p><span class="math display" id="eq:prevalence-odds">\[\begin{equation}
  \frac{Prevalence\, proportion}{1 - Prevalence\, proportion}
   \tag{43.2}
\end{equation}\]</span></p>
<p>Like all odds, the prevalence odds can range from 0 to infinity. Let’s once again use our simulated data to walk through an applied example of calculating prevalence odds.</p>
<div id="calculating-prevalence-odds-with-r" class="section level4 hasAnchor" number="43.2.3.1">
<h4><span class="header-section-number">43.2.3.1</span> Calculating prevalence odds with R<a href="measures-of-occurrence.html#calculating-prevalence-odds-with-r" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><img src="img/10_part_intro_epi/03_measures_of_occurrence/pop_10_plot.png" width="1094" /></p>
<p>We can calculate the prevalence odds similarly to the way we calculated prevalence proportion above. Notice that we are able to reuse the <code>prevalence_prop</code> object we created above. However, we have to make sure to use <code>prevalence_prop</code> instead of <code>prevalence_percent</code> and we can’t forget to place parentheses around <code>1 - prevalence_prop</code>.</p>
<div class="sourceCode" id="cb1707"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1707-1"><a href="measures-of-occurrence.html#cb1707-1" tabindex="-1"></a><span class="co"># Calculate the prevalence odds and assign it to an object called </span></span>
<span id="cb1707-2"><a href="measures-of-occurrence.html#cb1707-2" tabindex="-1"></a><span class="co"># prevalence_odds</span></span>
<span id="cb1707-3"><a href="measures-of-occurrence.html#cb1707-3" tabindex="-1"></a>prevalence_odds <span class="ot">&lt;-</span> prevalence_prop <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> prevalence_prop) <span class="co"># Don&#39;t forget parentheses</span></span>
<span id="cb1707-4"><a href="measures-of-occurrence.html#cb1707-4" tabindex="-1"></a><span class="co"># Print the value stored in prevalence_odds to the screen</span></span>
<span id="cb1707-5"><a href="measures-of-occurrence.html#cb1707-5" tabindex="-1"></a>prevalence_odds</span></code></pre></div>
<pre><code>## [1] 1.5</code></pre>
<p>Of course, we could still use R as a calculator as we did above for prevalence proportion.</p>
<div class="sourceCode" id="cb1709"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1709-1"><a href="measures-of-occurrence.html#cb1709-1" tabindex="-1"></a><span class="fl">0.6</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.6</span>)</span></code></pre></div>
<pre><code>## [1] 1.5</code></pre>
<p>And we can also calculate this estimate directly from our simulated data.</p>
<div class="sourceCode" id="cb1711"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1711-1"><a href="measures-of-occurrence.html#cb1711-1" tabindex="-1"></a>df <span class="sc">|&gt;</span> </span>
<span id="cb1711-2"><a href="measures-of-occurrence.html#cb1711-2" tabindex="-1"></a>  <span class="fu">freq_table</span>(disease) <span class="sc">|&gt;</span> </span>
<span id="cb1711-3"><a href="measures-of-occurrence.html#cb1711-3" tabindex="-1"></a>  <span class="co"># Convert percent back to a proportion by dividing by 100</span></span>
<span id="cb1711-4"><a href="measures-of-occurrence.html#cb1711-4" tabindex="-1"></a>  <span class="co"># Use mutate to do this: https://www.r4epi.com/creating-and-modifying-columns.html</span></span>
<span id="cb1711-5"><a href="measures-of-occurrence.html#cb1711-5" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop =</span> percent <span class="sc">/</span> <span class="dv">100</span>) <span class="sc">|&gt;</span> </span>
<span id="cb1711-6"><a href="measures-of-occurrence.html#cb1711-6" tabindex="-1"></a>  <span class="co"># Keep only the row of results that contains the proportion of people who </span></span>
<span id="cb1711-7"><a href="measures-of-occurrence.html#cb1711-7" tabindex="-1"></a>  <span class="co"># with disease (event)</span></span>
<span id="cb1711-8"><a href="measures-of-occurrence.html#cb1711-8" tabindex="-1"></a>  <span class="fu">filter</span>(cat <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb1711-9"><a href="measures-of-occurrence.html#cb1711-9" tabindex="-1"></a>  <span class="co"># Distill our results into a summary table (with one row and column)</span></span>
<span id="cb1711-10"><a href="measures-of-occurrence.html#cb1711-10" tabindex="-1"></a>  <span class="co"># Use summarise to do this: https://www.r4epi.com/numerical-descriptions-of-categorical-variables.html#the-tidyverse-way</span></span>
<span id="cb1711-11"><a href="measures-of-occurrence.html#cb1711-11" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">prevalence_odds =</span> prop <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> prop)) </span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   prevalence_odds
##             &lt;dbl&gt;
## 1             1.5</code></pre>
</div>
<div id="interpretation-1" class="section level4 hasAnchor" number="43.2.3.2">
<h4><span class="header-section-number">43.2.3.2</span> Interpretation<a href="measures-of-occurrence.html#interpretation-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>And here are some ways that we can interpret the prevalence odds we calculated above.</p>
<ol style="list-style-type: decimal">
<li><p>Among the members of our population, the odds of disease during the 12-month follow-up period were 1.5.</p></li>
<li><p>Among the members of our population, the odds of disease during the 12-month follow-up period were 1.5:1.</p></li>
<li><p>We can also multiply both sides of the ratio above by 10 and interpret our results this as: Among the members of our population, the odds of disease during the 12-month follow-up period were 15:10.</p></li>
<li><p>Among the members of our population, for every 1.5 people who had disease during the 12-month follow-up period there was one person who did not.</p></li>
<li><p>Among the members of our population, for every 15 people who had disease during the 12-month follow-up period there were ten people who did not.</p></li>
</ol>
</div>
<div id="interpretation-of-odds-less-than-one" class="section level4 hasAnchor" number="43.2.3.3">
<h4><span class="header-section-number">43.2.3.3</span> Interpretation of odds less than one<a href="measures-of-occurrence.html#interpretation-of-odds-less-than-one" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>When odds are less than 1, they can be especially tricky to interpret. To help illustrate this point, let’s assume that we only followed our population for two months instead of 12 months. Only 2 of the 10 people in our population had developed disease at month 2. What would the prevalence odds be in that case?</p>
<p>Well, the prevalence proportion would be:</p>
<p><span class="math display">\[\frac{2}{10} = 0.2\]</span></p>
<p>So, the prevalence odds would be:</p>
<p><span class="math display">\[\frac{Prevalence\, proportion}{1 - Prevalence\, proportion} = \frac{0.2}{1-0.2} = 0.25\]</span></p>
<p>And we can interpret those odds in any of the following ways:</p>
<ol style="list-style-type: decimal">
<li><p>Among the members of our population, the odds of disease during the 2-month follow-up period were 0.25.</p></li>
<li><p>Among the members of our population, the odds of disease during the 2-month follow-up period were 0.25:1.</p></li>
</ol>
<div class="sourceCode" id="cb1713"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1713-1"><a href="measures-of-occurrence.html#cb1713-1" tabindex="-1"></a><span class="co"># Make 0.25:1 more intuitive by dividing the the second number by the first</span></span>
<span id="cb1713-2"><a href="measures-of-occurrence.html#cb1713-2" tabindex="-1"></a><span class="dv">1</span> <span class="sc">/</span> <span class="fl">0.25</span></span></code></pre></div>
<pre><code>## [1] 4</code></pre>
<ol start="3" style="list-style-type: decimal">
<li><p>Among the members of our population, the odds of disease during the 2-month follow-up period were 1:4.</p></li>
<li><p>Among the members of our population, for every person who had disease during the 2-month follow-up period there were four people who did not.</p></li>
</ol>
<p>In our opinion, interpretation 4, while not necessarily the most commonly used, is probably the easiest for most people to understand in a meaningful way. If we go back and look at our simulated population, we can see interpretation 4 visually. For every one person who had disease at month two there were four people who did not. Two people had disease at month 2 (person 01 and person 02). Therefore, we expect that 8 people did not have disease at month 2. And that’s exactly what we see – persons 03 through 10 did not have disease in month 2.</p>
</div>
</div>
</div>
<div id="quantifying-incidence" class="section level2 hasAnchor" number="43.3">
<h2><span class="header-section-number">43.3</span> Quantifying incidence<a href="measures-of-occurrence.html#quantifying-incidence" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As discussed at the beginning of the chapter, incidence is our attempt to quantify how frequently <em>new incidents</em> of a particular health-related state occur in our population of interest during a specified period of time. Therefore, it doesn’t make logical sense to include people who <em>already</em> have the condition of interest in our calculations. How can we measure their <em>transition</em> from not having the condition to having the condition if they already have the condition? This idea is commonly captured in the concept of a population “at risk”. Below, we will quantify incidence in many of the same ways as we quantified prevalence – as incidence counts, incidence proportions, and incidence odds. In addition, we will also introduce the concept of person-time and incidence rates.</p>
<div id="incidence-count" class="section level3 hasAnchor" number="43.3.1">
<h3><span class="header-section-number">43.3.1</span> Incidence Count<a href="measures-of-occurrence.html#incidence-count" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Incidence counts are identical to prevalence counts except that we count the number of <em>new</em> occurrences of the disease or condition of interest during a specified period of time.</p>
<p><img src="img/10_part_intro_epi/03_measures_of_occurrence/pop_10_plot.png" width="1094" /></p>
<p>To solidify the concept in our minds, let’s look take another look at our simulated population of 10 people. At the start of follow-up, which is month 0 in the figure above, there are 10 people alive in our population. How many of those 10 people have the disease we are interested in?</p>
<p>At the start of follow-up, person 01 has the disease of interest.</p>
<p>How many of the 10 people in our simulated population are “at risk” of newly getting the disease we are interested in (assume that this disease cannot reoccur)?</p>
<p>At the start of follow-up, 9 people (every person except person 01) are at risk of getting the disease. Person 01 is not at risk of getting the disease because they already developed the disease at some point prior to month 0. Let’s pause here and note a couple of key points.</p>
<ol style="list-style-type: decimal">
<li><p>We can count person 01 as a <em>prevalent</em> case at month 0, but we cannot count person 01 as an <em>incident</em> case at month 0. This is a concrete example of the difference between prevalence and incidence.</p></li>
<li><p>Assuming they weren’t born with this disease, person 01 <em>did</em> newly acquire it at <em>some point</em> in the past. In other words, they were an “incident” case at some time in the past; however, they didn’t newly acquire the disease during our <em>specified period of time</em>. This is a concrete example of the importance of being explicit about the timing and duration of our period of study.</p></li>
</ol>
<p>Now, let’s move down to follow-up month 1. We check up on our population of 10 people. Who many people have the disease of interest?</p>
<p>At follow-up month 1, two people have the disease of interest – person 01 and person 02.</p>
<p>What is the incident count at month 1?</p>
<p>At follow-up month 1, the incident count of the disease of interest is 1. Person 01 and person 02 both have the disease of interest, but only person 02 has a <em>new</em> case of the disease.</p>
<p>Let’s do this one more time. Take a look at follow-up month 6. When we do our 6-month checkup, how many people have the disease of interest?</p>
<p>At follow-up month 6, five people have the disease of interest – person 01, person 03, person 04, and person 05.</p>
<p>What is the incident count at month 6?</p>
<p>Well, we need to be really careful about our language here because we could answer this question in a couple of different ways.</p>
<ul>
<li><p>If we are interested in knowing the count of incident cases <em>at</em> month 6 (relative to month 5), then the answer is 1. Only person 05 developed disease specifically at month 6.</p></li>
<li><p>If we are interested in knowing the count of incident cases during our period of study at month 6 (relative to month 0), then the answer is 4. Person 01, person 03, person 04, and person 05 are alive and have the disease of interest at month 6, but only person 02, person 03, person 04, and person 05 <em>newly acquired</em> the disease during our period of study (month 0 to month 6). You may have been tempted to leave out person 02 because they were deceased at month 6, but that would be incorrect. They were dead at month 5, but we observed them develop a new case of disease during our study period before they died.</p></li>
</ul>
</div>
<div id="incidence-proportion" class="section level3 hasAnchor" number="43.3.2">
<h3><span class="header-section-number">43.3.2</span> Incidence proportion<a href="measures-of-occurrence.html#incidence-proportion" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When people use the word “incidence” without a qualifier, they are typically, though not always, talking about the incidence proportion. Other terms that are commonly used to refer to an incidence proportion are “risk” and “cumulative incidence”. We prefer to use incidence proportion because we find it to be less ambiguous than risk or cumulative incidence.</p>
<p>The numerator we use to calculate the incidence proportion is the incident count we learned about above. The denominator we use to calculate the incidence proportion is the count of people in the population of interest who were <em>at risk</em> experiencing a <em>new</em> occurrence of the disease or condition of interest during the specified period of time.</p>
<p><span class="math display">\[\frac{Count\, of\, new\, occurences}{Population\, at\, risk}\]</span></p>
<p><img src="img/10_part_intro_epi/03_measures_of_occurrence/pop_10_plot.png" width="1094" /></p>
<p>Let’s look take another look at our simulated population of 10 people. We already determined that nine of those people were at risk of getting the disease of interest. Person 01 was not at risk because they acquired the disease at some point prior to the start of our study period. Therefore, what is the incidence proportion over the 12 months of follow-up?</p>
<p>The incidence proportion during over the 12 months of follow-up was 5/9 or 0.56. Our numerator included the 5 people who developed the disease during the study period – person 02, person 03, person 04, person 05, and person 06 – and our denominator included the 9 people who were at risk of disease at the start of the study period.</p>
<div id="calculating-incidence-proportions-with-r" class="section level4 hasAnchor" number="43.3.2.1">
<h4><span class="header-section-number">43.3.2.1</span> Calculating incidence proportions with R<a href="measures-of-occurrence.html#calculating-incidence-proportions-with-r" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Now, let’s look at some ways we can calculate an incidence proportion with R.</p>
<div class="sourceCode" id="cb1715"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1715-1"><a href="measures-of-occurrence.html#cb1715-1" tabindex="-1"></a><span class="co"># Create a vector containing the number of people with incident disease</span></span>
<span id="cb1715-2"><a href="measures-of-occurrence.html#cb1715-2" tabindex="-1"></a>incidence_count <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb1715-3"><a href="measures-of-occurrence.html#cb1715-3" tabindex="-1"></a><span class="co"># Create a vector containing the number of people in the population of interest</span></span>
<span id="cb1715-4"><a href="measures-of-occurrence.html#cb1715-4" tabindex="-1"></a><span class="co"># who were at risk at the start of follow-up</span></span>
<span id="cb1715-5"><a href="measures-of-occurrence.html#cb1715-5" tabindex="-1"></a>population_at_risk <span class="ot">&lt;-</span> <span class="dv">9</span></span>
<span id="cb1715-6"><a href="measures-of-occurrence.html#cb1715-6" tabindex="-1"></a><span class="co"># Calculate the incidence proportion and assign it to an object called </span></span>
<span id="cb1715-7"><a href="measures-of-occurrence.html#cb1715-7" tabindex="-1"></a><span class="co"># incidence_prop</span></span>
<span id="cb1715-8"><a href="measures-of-occurrence.html#cb1715-8" tabindex="-1"></a>incidence_prop <span class="ot">&lt;-</span> incidence_count <span class="sc">/</span> population_at_risk</span>
<span id="cb1715-9"><a href="measures-of-occurrence.html#cb1715-9" tabindex="-1"></a><span class="co"># Print the value stored in prevalence_prop to the screen</span></span>
<span id="cb1715-10"><a href="measures-of-occurrence.html#cb1715-10" tabindex="-1"></a>incidence_prop</span></code></pre></div>
<pre><code>## [1] 0.5555556</code></pre>
<p>Let’s round to the hundredths place (2 decimal places).</p>
<div class="sourceCode" id="cb1717"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1717-1"><a href="measures-of-occurrence.html#cb1717-1" tabindex="-1"></a><span class="co"># Round the value stored in incidence_prop to the hundredths place and assign</span></span>
<span id="cb1717-2"><a href="measures-of-occurrence.html#cb1717-2" tabindex="-1"></a><span class="co"># that value back to the incidence_prop vector</span></span>
<span id="cb1717-3"><a href="measures-of-occurrence.html#cb1717-3" tabindex="-1"></a>incidence_prop <span class="ot">&lt;-</span> <span class="fu">round</span>(incidence_prop, <span class="dv">2</span>)</span>
<span id="cb1717-4"><a href="measures-of-occurrence.html#cb1717-4" tabindex="-1"></a><span class="co"># Print the value stored in prevalence_prop to the screen</span></span>
<span id="cb1717-5"><a href="measures-of-occurrence.html#cb1717-5" tabindex="-1"></a>incidence_prop</span></code></pre></div>
<pre><code>## [1] 0.56</code></pre>
</div>
<div id="interpretation-2" class="section level4 hasAnchor" number="43.3.2.2">
<h4><span class="header-section-number">43.3.2.2</span> Interpretation<a href="measures-of-occurrence.html#interpretation-2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>And here are some ways that we can interpret the incidence proportion we calculated above.</p>
<ol style="list-style-type: decimal">
<li><p>Among the members of our population, the incidence of disease over 12 months of follow-up was 0.56.</p></li>
<li><p>Fifty six percent of the members of our population developed disease over 12 months of follow-up.</p></li>
</ol>
<p>We would like to once again remind you how important it explicitly report information about the period of study along with the incidence proportion. Let’s consider death as an outcome for a moment in order to further illustrate this point. All humans eventually die; therefore, over a sufficiently long duration of follow-up, the incidence proportion of death will be 1.0. So, if we report that the incidence proportion of death in our study was 0.2, that isn’t particularly meaningful. Did 20% of the population die in a day? A week? A year? Over a 10-year period? It would be far more useful for us to report that 20% of the population died <em>during the 3 years of follow-up</em> (or whatever the study period was).</p>
</div>
</div>
<div id="incidence-odds" class="section level3 hasAnchor" number="43.3.3">
<h3><span class="header-section-number">43.3.3</span> Incidence Odds<a href="measures-of-occurrence.html#incidence-odds" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Like prevalence odds, incidence odds are not commonly used as a measure of occurrence in epidemiology. However, we will demonstrate how to calculate them here for the sake of completeness. The incidence odds are equal to the incidence proportion divided by 1 minus the incidence proportion.</p>
<p><span class="math display">\[\frac{Incidence\, proportion}{1 - Incidence\, proportion}\]</span></p>
<div id="calculating-incidence-odds-with-r" class="section level4 hasAnchor" number="43.3.3.1">
<h4><span class="header-section-number">43.3.3.1</span> Calculating incidence odds with R<a href="measures-of-occurrence.html#calculating-incidence-odds-with-r" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We can calculate the incidence odds similarly to the way we calculated prevalence odds above.</p>
<div class="sourceCode" id="cb1719"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1719-1"><a href="measures-of-occurrence.html#cb1719-1" tabindex="-1"></a><span class="co"># Calculate the incidence odds and assign it to an object called </span></span>
<span id="cb1719-2"><a href="measures-of-occurrence.html#cb1719-2" tabindex="-1"></a><span class="co"># incidence_odds</span></span>
<span id="cb1719-3"><a href="measures-of-occurrence.html#cb1719-3" tabindex="-1"></a>incidence_odds <span class="ot">&lt;-</span> incidence_prop <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> incidence_prop) <span class="co"># Don&#39;t forget parentheses</span></span>
<span id="cb1719-4"><a href="measures-of-occurrence.html#cb1719-4" tabindex="-1"></a><span class="co"># Print the value stored in incidence_odds to the screen</span></span>
<span id="cb1719-5"><a href="measures-of-occurrence.html#cb1719-5" tabindex="-1"></a>incidence_odds</span></code></pre></div>
<pre><code>## [1] 1.272727</code></pre>
<p>Again, we can round the value of <code>incidence_odds</code> to make it easier to read.</p>
<div class="sourceCode" id="cb1721"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1721-1"><a href="measures-of-occurrence.html#cb1721-1" tabindex="-1"></a><span class="co"># Round the value stored in incidence_odds to the hundredths place and assign</span></span>
<span id="cb1721-2"><a href="measures-of-occurrence.html#cb1721-2" tabindex="-1"></a><span class="co"># that value back to the incidence_odds vector</span></span>
<span id="cb1721-3"><a href="measures-of-occurrence.html#cb1721-3" tabindex="-1"></a><span class="fu">round</span>(incidence_odds, <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 1.27</code></pre>
</div>
<div id="interpretation-3" class="section level4 hasAnchor" number="43.3.3.2">
<h4><span class="header-section-number">43.3.3.2</span> Interpretation<a href="measures-of-occurrence.html#interpretation-3" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>And here are some ways that we can interpret the incidence odds we calculated above.</p>
<ol style="list-style-type: decimal">
<li><p>Among the members of our population, the odds of incident disease over 12 months of follow-up were 1.27.</p></li>
<li><p>Among the members of our population, the odds of incident disease over 12 months of follow-up were 1.27:1.</p></li>
<li><p>Among the members of our population, the odds of incident disease over 12 months of follow-up were 127:100.</p></li>
<li><p>Among the members of our population, for every 127 people develop incident disease over 12 months of follow-up there were 100 people who did not.</p></li>
</ol>
</div>
</div>
<div id="incidence-rate" class="section level3 hasAnchor" number="43.3.4">
<h3><span class="header-section-number">43.3.4</span> Incidence Rate<a href="measures-of-occurrence.html#incidence-rate" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To calculate an accurate incidence proportion using the methods we learned above, our population of interest must be a closed population and we we must have complete follow-up all of the population members. In other words, new people can’t enter the population during the study period, nobody can leave the population (except through death), and we have to be able to collect data from everyone throughout the entire duration of the study. Why are these conditions important? Let’s take another look at our simulated population to help us understand.</p>
<p><img src="img/10_part_intro_epi/03_measures_of_occurrence/pop_10_plot.png" width="1094" /></p>
<p>Let’s assume that our population of interest is geographically defined. It is an incredibly small town that we are interested in. We know that 10 people are members of the population, but we don’t actually know them by name. Perhaps this town is on the other side of the world, or existed at some time in the past, and we only have access to written records.</p>
<p>Next, let’s say that two new people moved to the little town at some point during the 12 month study period (shown as person 11 and person 12 below). Additionally, person 02 and person 03 moved out of the little town during the 12 month study period. The figure below illustrates these changes.</p>
<p><img src="img/10_part_intro_epi/03_measures_of_occurrence/pop_12_plot.png" width="1094" /></p>
<p>Under these conditions, we still observe that 9 people were at risk of disease at the start of follow-up (persons 02 - 10). At some point during the 12 months of follow-up, persons 02 and 03 move out and persons 11 and 12 move in. When we go to analyze our study data at the end of follow-up, we observe that 3 people developed the disease (person 04, person 05, and person 06). <em>We</em> know that person 02 and person 03 also developed disease because we are simulating this scenario. Additionally, <em>we</em> know that person 11 and person 12 weren’t in the population at the start of the study because we are simulating this scenario. But, if we weren’t simulating this scenario, all we would know is that we started with 10 people, 9 of whom were at risk, and that 3 of them had disease at the end of 12 months of follow-up. Therefore, we would calculate the incidence proportion as 3/9 or 0.33, which underestimates the true population incidence proportion of 0.56.</p>
<p>As another example, let’s return to our original population of 10 people. This time, let’s imagine that person 06 and person 07 decide that they don’t want to participate in our study anymore and stop showing up for their follow-up appointments at month 6. This change doesn’t have any affect on our denominator. We still observe that 9 people were at risk of disease at the start of follow-up (persons 02 - 10). However, we no longer know the status of person 06 and person 07 at the end of the study period (month 12). So, what value are we to use for our numerator?</p>
<p><img src="img/10_part_intro_epi/03_measures_of_occurrence/pop_10_censored_plot.png" width="1094" /></p>
<p>Well, we may be tempted to say that neither of them developed the disease because they were disease free at the last follow-up visit they <em>did</em> attend (month 5). Using that logic, we would calculate our incidence proportion as 4/9 or 0.44 – counting persons 02, 03, and 04 only in our numerator. Of course, because this is a simulated population, we know that 0.44 once again underestimates the true population incidence proportion of 0.56. This approach is clearly not ideal. Unfortunately, this kind of loss to follow-up is an incredibly common occurrence in the real world. So, what are we to do?</p>
<p>One option is to quantify incidence using methods that take the length of time each member of the population is under observation into account. However, we need to introduce another key concept – <strong>person-time</strong> – before diving into time-to-event methods.</p>
<div id="person-time" class="section level4 hasAnchor" number="43.3.4.1">
<h4><span class="header-section-number">43.3.4.1</span> Person-time<a href="measures-of-occurrence.html#person-time" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<blockquote>
<p>“Person-time is the amount of time observed for all people under study while at risk of experiencing an incident outcome.”<span class="citation"><sup><a href="#ref-Westreich2019-lg">18</a></sup></span></p>
</blockquote>
<p>The definition above can also be written in a more formulaic way like this.</p>
<p><span class="math display">\[\sum_{people} Time\, spent\, at\, risk\]</span></p>
<p>Some readers may never have seen the symbol above that kind of looks like a backward 3. It is the Greek letter sigma, and it is shorthand for “add up everything to the right”. The word “people” written below the sigma means “for all people.” So, taken together, the formula means, for all people in the population, add up each of their individual times spent at risk of disease.</p>
<p>Let’s once again use our simulated population to 10 people to dig into this definition a little bit.</p>
<p><img src="img/10_part_intro_epi/03_measures_of_occurrence/pop_10_plot.png" width="1094" /></p>
<p>How many people were at risk of experiencing a new occurrence of disease during the period of observation? We already decided that the answer to this question is 9.</p>
<p>For how many months were these 9 people under observation and at risk of developing a new occurrence of disease? To answer that question, we need to determine each individual person’s observed time at risk.</p>
<div class="sourceCode" id="cb1723"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1723-1"><a href="measures-of-occurrence.html#cb1723-1" tabindex="-1"></a><span class="co"># Have R calculate the total person-months at risk</span></span>
<span id="cb1723-2"><a href="measures-of-occurrence.html#cb1723-2" tabindex="-1"></a>pop_10_wide <span class="sc">|&gt;</span> </span>
<span id="cb1723-3"><a href="measures-of-occurrence.html#cb1723-3" tabindex="-1"></a>  <span class="co"># Keep only the rows with a status of At Risk</span></span>
<span id="cb1723-4"><a href="measures-of-occurrence.html#cb1723-4" tabindex="-1"></a>  <span class="fu">filter</span>(status <span class="sc">==</span> <span class="st">&quot;At Risk&quot;</span>) <span class="sc">|&gt;</span> </span>
<span id="cb1723-5"><a href="measures-of-occurrence.html#cb1723-5" tabindex="-1"></a>  <span class="co"># Calculate the time between follow-up months for each person</span></span>
<span id="cb1723-6"><a href="measures-of-occurrence.html#cb1723-6" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">time_at_risk =</span> xend_adjusted <span class="sc">-</span> x) <span class="sc">|&gt;</span> </span>
<span id="cb1723-7"><a href="measures-of-occurrence.html#cb1723-7" tabindex="-1"></a>  <span class="co"># Keep only the person and time_at_risk columns to make the results easier to</span></span>
<span id="cb1723-8"><a href="measures-of-occurrence.html#cb1723-8" tabindex="-1"></a>  <span class="co"># read</span></span>
<span id="cb1723-9"><a href="measures-of-occurrence.html#cb1723-9" tabindex="-1"></a>  <span class="fu">select</span>(person_f, time_at_risk)</span></code></pre></div>
<pre><code>## # A tibble: 9 × 2
##   person_f time_at_risk
##   &lt;fct&gt;           &lt;int&gt;
## 1 02                  2
## 2 03                  4
## 3 04                  5
## 4 05                  7
## 5 06                  8
## 6 07                  9
## 7 08                  5
## 8 09                 12
## 9 10                 12</code></pre>
<ul>
<li>Person 02: 2 month</li>
<li>Person 03: 4 months</li>
<li>Person 04: 5 months</li>
<li>Person 05: 7 months</li>
<li>Person 06: 8 months</li>
<li>Person 07: 9 months</li>
<li>Person 08: 5 months</li>
<li>Person 09: 12 months</li>
<li>Person 10: 12 months</li>
</ul>
<p>After we determine each person’s individual time spent at risk, we add them up to the population time at risk.</p>
<div class="sourceCode" id="cb1725"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1725-1"><a href="measures-of-occurrence.html#cb1725-1" tabindex="-1"></a><span class="co"># Calculate the population time at risk and assign it to an object called </span></span>
<span id="cb1725-2"><a href="measures-of-occurrence.html#cb1725-2" tabindex="-1"></a><span class="co"># pop_time_at_risk</span></span>
<span id="cb1725-3"><a href="measures-of-occurrence.html#cb1725-3" tabindex="-1"></a>pop_time_at_risk <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">+</span> <span class="dv">4</span> <span class="sc">+</span> <span class="dv">5</span> <span class="sc">+</span> <span class="dv">7</span> <span class="sc">+</span> <span class="dv">8</span> <span class="sc">+</span> <span class="dv">9</span> <span class="sc">+</span> <span class="dv">5</span> <span class="sc">+</span> <span class="dv">12</span> <span class="sc">+</span> <span class="dv">12</span></span>
<span id="cb1725-4"><a href="measures-of-occurrence.html#cb1725-4" tabindex="-1"></a><span class="co"># Print the value stored in pop_time_at_risk to the screen</span></span>
<span id="cb1725-5"><a href="measures-of-occurrence.html#cb1725-5" tabindex="-1"></a>pop_time_at_risk</span></code></pre></div>
<pre><code>## [1] 64</code></pre>
<p>But, instead of doing this calculation manually, let’s ask R to do it for us using the simulated data directly.</p>
<div class="sourceCode" id="cb1727"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1727-1"><a href="measures-of-occurrence.html#cb1727-1" tabindex="-1"></a><span class="co"># Have R calculate the total person-months at risk</span></span>
<span id="cb1727-2"><a href="measures-of-occurrence.html#cb1727-2" tabindex="-1"></a>pop_10_wide <span class="sc">|&gt;</span> </span>
<span id="cb1727-3"><a href="measures-of-occurrence.html#cb1727-3" tabindex="-1"></a>  <span class="co"># Keep only the rows with a status of At Risk</span></span>
<span id="cb1727-4"><a href="measures-of-occurrence.html#cb1727-4" tabindex="-1"></a>  <span class="fu">filter</span>(status <span class="sc">==</span> <span class="st">&quot;At Risk&quot;</span>) <span class="sc">|&gt;</span> </span>
<span id="cb1727-5"><a href="measures-of-occurrence.html#cb1727-5" tabindex="-1"></a>  <span class="co"># Calculate the time between follow-up months for each person</span></span>
<span id="cb1727-6"><a href="measures-of-occurrence.html#cb1727-6" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">time_at_risk =</span> xend_adjusted <span class="sc">-</span> x) <span class="sc">|&gt;</span> </span>
<span id="cb1727-7"><a href="measures-of-occurrence.html#cb1727-7" tabindex="-1"></a>  <span class="co"># Total all of the individual person-months at risk</span></span>
<span id="cb1727-8"><a href="measures-of-occurrence.html#cb1727-8" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">time_at_risk =</span> <span class="fu">sum</span>(time_at_risk))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   time_at_risk
##          &lt;int&gt;
## 1           64</code></pre>
<p>So, these people were under observation and at risk of developing a new occurrence of disease for a combined total of 64 months. However, it might be a little confusing if we simply say that we observed our population for 64 months. That can easily be interpreted to mean that our study was 64 months long. In reality, it was only 12 months long. So, we typically say that we observed our population for 64 <em>person-months</em>, or that we had 64 <em>person-months</em> of follow-up data, or something along those lines.</p>
<p>Why do we say person- <em>months</em> instead of, for example, person- <em>years</em>? Well, it is probably the most natural why to describe the amount of person-time our population was under observation because our study was less than a year long and we collected data every month. Having said that, we are not <em>required</em> to report the person-time under observation as person-months. We can easily convert person-months to person-years by dividing the person-months by 12.</p>
<div class="sourceCode" id="cb1729"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1729-1"><a href="measures-of-occurrence.html#cb1729-1" tabindex="-1"></a><span class="co"># Convert person-months to person-years by dividing by 12</span></span>
<span id="cb1729-2"><a href="measures-of-occurrence.html#cb1729-2" tabindex="-1"></a><span class="dv">64</span><span class="sc">/</span><span class="dv">12</span></span></code></pre></div>
<pre><code>## [1] 5.333333</code></pre>
<div class="note">
<p>🗒<strong>Side Note:</strong> Why divide person-months by 12 to convert them to person-years? Because there are 12 months in a year. Think about it this way: If we followed one person for 12 months, we would have observed them for 12 person-months, right? We would have also observed them for 1 year, right? And how can we convert 12 to 1? We can convert 12 to 1 by dividing it by 12 (12 / 12 = 1). More generally, to convert a shorter unit of person-time into a longer unit of person-time, we divide the shorter unit by the number of times it will goes into the longer. The opposite is true when converting a longer unit of person-time into a shorter unit of person-time.</p>
</div>
<p>So, saying that we have 64 person-months of data, and saying that we have 5.33 person-years of data, are saying the exact same thing. We are just saying it in 2 different ways. Actually, we could convert person-months to person-weeks, person-days, or a number of other different versions of person-time. So, which one do we choose? Well, there are some areas of study that tend to use a particular person-time measure more often than others by convention. However, our ultimate goal should typically be to choose measures that communicate our findings in the most honest and useful way possible. This may require us to do a little experimenting at times.</p>
</div>
<div id="calculating-incidence-rates-with-r" class="section level4 hasAnchor" number="43.3.4.2">
<h4><span class="header-section-number">43.3.4.2</span> Calculating incidence rates with R<a href="measures-of-occurrence.html#calculating-incidence-rates-with-r" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>In the sections above, we discussed some reasons why incidence proportions can be difficult to accurately calculate in practice. We also learned to calculate the person-time experience for our population of interest. In this section, we will build on those two concepts and learn how to calculate incidence rates.</p>
<blockquote>
<p>Incidence rates are “a measure of the average intensity at which an event occurs in the experience of people over time, and, for a population followed from baseline, it is calculated as the number of cases in that population divided by the amount of person-time at risk accumulated by that population.”<span class="citation"><sup><a href="#ref-Westreich2019-lg">18</a></sup></span></p>
</blockquote>
<p>The definition above can also be written in a more formulaic way like this.</p>
<p><span class="math display">\[\frac{Count\, of\, new\, occurences}{Person\, time\, at\, risk}\]</span></p>
<p>With this definition in mind, what is the incidence rate of disease in our simulated population of 10 people? Well we already determined that 5 people at risk (person 02, person 03, person 04, person 05, person 06) developed a new occurrence of disease during the 12 months of follow-up. Additionally, we already determined that we observed 64 person-months of time at risk during the 12 months of follow-up. Let’s use that information to calculate the incidence rate with R.</p>
<div class="sourceCode" id="cb1731"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1731-1"><a href="measures-of-occurrence.html#cb1731-1" tabindex="-1"></a><span class="co"># Create a vector containing the incident count</span></span>
<span id="cb1731-2"><a href="measures-of-occurrence.html#cb1731-2" tabindex="-1"></a>n_occurrences <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb1731-3"><a href="measures-of-occurrence.html#cb1731-3" tabindex="-1"></a><span class="co"># Create a vector containing the person months at risk</span></span>
<span id="cb1731-4"><a href="measures-of-occurrence.html#cb1731-4" tabindex="-1"></a>person_months_at_risk <span class="ot">&lt;-</span> <span class="dv">64</span></span>
<span id="cb1731-5"><a href="measures-of-occurrence.html#cb1731-5" tabindex="-1"></a><span class="co"># Calculate the incidence rate and assign it to an object called </span></span>
<span id="cb1731-6"><a href="measures-of-occurrence.html#cb1731-6" tabindex="-1"></a><span class="co"># incidence_rate</span></span>
<span id="cb1731-7"><a href="measures-of-occurrence.html#cb1731-7" tabindex="-1"></a>incidence_rate <span class="ot">&lt;-</span> n_occurrences <span class="sc">/</span> person_months_at_risk</span>
<span id="cb1731-8"><a href="measures-of-occurrence.html#cb1731-8" tabindex="-1"></a><span class="co"># Print the value stored in incidence_rate to the screen</span></span>
<span id="cb1731-9"><a href="measures-of-occurrence.html#cb1731-9" tabindex="-1"></a>incidence_rate</span></code></pre></div>
<pre><code>## [1] 0.078125</code></pre>
</div>
<div id="interpretation-4" class="section level4 hasAnchor" number="43.3.4.3">
<h4><span class="header-section-number">43.3.4.3</span> Interpretation<a href="measures-of-occurrence.html#interpretation-4" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>And here are just a few (of many) ways that we can interpret the incidence rates we calculated above.</p>
<ol style="list-style-type: decimal">
<li>The incidence rate of disease among the members of our population was 5 cases per 64 person-months during 12 months of follow-up.</li>
</ol>
<div class="sourceCode" id="cb1733"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1733-1"><a href="measures-of-occurrence.html#cb1733-1" tabindex="-1"></a><span class="co"># Calculate the person-month rate</span></span>
<span id="cb1733-2"><a href="measures-of-occurrence.html#cb1733-2" tabindex="-1"></a>incidence_rate</span></code></pre></div>
<pre><code>## [1] 0.078125</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>The incidence rate of disease among the members of our population was 0.078 cases per person-month during 12 months of follow-up.</li>
</ol>
<div class="sourceCode" id="cb1735"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1735-1"><a href="measures-of-occurrence.html#cb1735-1" tabindex="-1"></a><span class="co"># Calculate the 100 person-month rate</span></span>
<span id="cb1735-2"><a href="measures-of-occurrence.html#cb1735-2" tabindex="-1"></a>incidence_rate <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div>
<pre><code>## [1] 7.8125</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>The incidence rate of disease among the members of our population was 7.8 cases per 100 person-months during 12 months of follow-up.</li>
</ol>
<div class="sourceCode" id="cb1737"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1737-1"><a href="measures-of-occurrence.html#cb1737-1" tabindex="-1"></a><span class="co"># Calculate the person-year rate</span></span>
<span id="cb1737-2"><a href="measures-of-occurrence.html#cb1737-2" tabindex="-1"></a><span class="co"># First, convert person-time to years</span></span>
<span id="cb1737-3"><a href="measures-of-occurrence.html#cb1737-3" tabindex="-1"></a>person_years_at_risk <span class="ot">&lt;-</span> person_months_at_risk <span class="sc">/</span> <span class="dv">12</span></span>
<span id="cb1737-4"><a href="measures-of-occurrence.html#cb1737-4" tabindex="-1"></a><span class="co"># Divide the incidence count by person-years at risk</span></span>
<span id="cb1737-5"><a href="measures-of-occurrence.html#cb1737-5" tabindex="-1"></a>n_occurrences <span class="sc">/</span> person_years_at_risk</span></code></pre></div>
<pre><code>## [1] 0.9375</code></pre>
<ol start="4" style="list-style-type: decimal">
<li>The incidence rate of disease among the members of our population was 0.94 cases per person-year during 12 months of follow-up.</li>
</ol>
<p>Notice that we can’t simply divide the person-month incidence rate by 12 to get the person-year incidence rate.</p>
<div class="sourceCode" id="cb1739"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1739-1"><a href="measures-of-occurrence.html#cb1739-1" tabindex="-1"></a>incidence_rate <span class="sc">/</span> <span class="dv">12</span></span></code></pre></div>
<pre><code>## [1] 0.006510417</code></pre>
<p>If you need to do a little sanity check to convince yourself that 0.94 cases per person-year is correct, then think about the following. We aleady said that there were 0.078 per person-month in our population. We also know that we followed everyone for 12 months. Therefore, we would expect the person-year incidence rate to be roughly 0.078 * 12, which is:</p>
<div class="sourceCode" id="cb1741"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1741-1"><a href="measures-of-occurrence.html#cb1741-1" tabindex="-1"></a><span class="fl">0.078</span> <span class="sc">*</span> <span class="dv">12</span></span></code></pre></div>
<pre><code>## [1] 0.936</code></pre>

</div>
</div>
</div>
</div>




</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body">
<div id="ref-Porta2008-ij" class="csl-entry">
<div class="csl-left-margin">16. </div><div class="csl-right-inline">Porta M, ed. <em>A Dictionary of Epidemiology</em>. Oxford University Press; 2008.</div>
</div>
<div id="ref-Westreich2019-lg" class="csl-entry">
<div class="csl-left-margin">18. </div><div class="csl-right-inline">Westreich D. <em>Epidemiology by Design</em>. Oxford University Press; 2019.</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>These statements are based on anecdotal experience. They are not based on any empirical evidence that we are aware of. Believe them at your own risk.😂<a href="measures-of-occurrence.html#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="populations.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="appendix-a-glossary.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/brad-cannell/r4epi/edit/master/chapters/10_part_intro_epi/03_measures_of_occurrence.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
