{
  "hash": "af77434008a0c9f223f47972bdb54808",
  "result": {
    "engine": "knitr",
    "markdown": "# Describing the Relationship Between a Continuous Outcome and a Categorical Predictor\n\nUp until now, we have only ever looked at the overall mean of a continuous variable. For example, the mean height for the entire class. However, we often want to estimate the means within levels, or categories, of another variable. For example, we may want to look at the mean height within gender. Said another way, we want to know the mean height for men and separately the mean height for women.\n\nMore generally, in this lesson you will learn to perform bivariate analysis when the outcome is continuous and the predictor is categorical.\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Continuous outcome and categorical predictor](cont_cat_01.png){width=1080}\n:::\n:::\n\n\n\n\n\n\nTypically in a situation such as this, all we need to do is apply the analytic methods we’ve already learned for a single continuous outcome, but apply them separately within levels of our categorical predictor variable. Below, we'll walk through doing so with R. To start with, we will again use our previously collected class survey data.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nclass <- tibble(\n  age       = c(32, 30, 32, 29, 24, 38, 25, 24, 48, 29, 22, 29, 24, 28, 24, 25, \n                25, 22, 25, 24, 25, 24, 23, 24, 31, 24, 29, 24, 22, 23, 26, 23, \n                24, 25, 24, 33, 27, 25, 26, 26, 26, 26, 26, 27, 24, 43, 25, 24, \n                27, 28, 29, 24, 26, 28, 25, 24, 26, 24, 26, 31, 24, 26, 31, 34, \n                26, 25, 27, NA),\n  age_group = c(2, 2, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, \n                1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, \n                1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, \n                2, 1, 1, 1, NA),\n  gender    = c(2, 1, 1, 2, 1, 1, 1, 2, 2, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, \n                1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, \n                1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 2, 1, \n                1, 1, 2, 1, NA),\n  ht_in     = c(70, 63, 62, 67, 67, 58, 64, 69, 65, 68, 63, 68, 69, 66, 67, 65, \n                64, 75, 67, 63, 60, 67, 64, 73, 62, 69, 67, 62, 68, 66, 66, 62, \n                64, 68, NA, 68, 70, 68, 68, 66, 71, 61, 62, 64, 64, 63, 67, 66, \n                69, 76, NA, 63, 64, 65, 65, 71, 66, 65, 65, 71, 64, 71, 60, 62, \n                61, 69, 66, NA),\n  wt_lbs    = c(216, 106, 145, 195, 143, 125, 138, 140, 158, 167, 145, 297, 146, \n                125, 111, 125, 130, 182, 170, 121, 98, 150, 132, 250, 137, 124, \n                186, 148, 134, 155, 122, 142, 110, 132, 188, 176, 188, 166, 136, \n                147, 178, 125, 102, 140, 139, 60, 147, 147, 141, 232, 186, 212, \n                110, 110, 115, 154, 140, 150, 130, NA, 171, 156, 92, 122, 102, \n                163, 141, NA),\n  bmi       = c(30.99, 18.78, 26.52, 30.54, 22.39, 26.12, 23.69, 20.67, 26.29, \n                25.39, 25.68, 45.15, 21.56, 20.17, 17.38, 20.8, 22.31, 22.75, \n                26.62, 21.43, 19.14, 23.49, 22.66, 32.98, 25.05, 18.31, 29.13, \n                27.07, 20.37, 25.01, 19.69, 25.97, 18.88, 20.07, NA, 26.76, \n                26.97, 25.24, 20.68, 23.72, 24.82, 23.62, 18.65, 24.03, 23.86, \n                10.63, 23.02, 23.72, 20.82, 28.24, NA, 37.55, 18.88, 18.3, \n                19.13, 21.48, 22.59, 24.96, 21.63, NA, 29.35, 21.76, 17.97, \n                22.31, 19.27, 24.07, 22.76, NA),\n  bmi_3cat  = c(3, 1, 2, 3, 1, 2, 1, 1, 2, 2, 2, 3, 1, 1, 1, 1, 1, 1, 2, 1, 1, \n                1, 1, 3, 2, 1, 2, 2, 1, 2, 1, 2, 1, 1, NA, 2, 2, 2, 1, 1, 1, 1, \n                1, 1, 1, 1, 1, 1, 1, 2, NA, 3, 1, 1, 1, 1, 1, 1, 1, NA, 2, 1, \n                1, 1, 1, 1, 1, NA)\n) %>% \n  mutate(\n    age_group = factor(age_group, labels = c(\"Younger than 30\", \"30 and Older\")),\n    gender = factor(gender, labels = c(\"Female\", \"Male\")),\n    bmi_3cat = factor(bmi_3cat, labels = c(\"Normal\", \"Overweight\", \"Obese\"))\n  ) %>% \n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 68 × 7\n     age age_group       gender ht_in wt_lbs   bmi bmi_3cat  \n   <dbl> <fct>           <fct>  <dbl>  <dbl> <dbl> <fct>     \n 1    32 30 and Older    Male      70    216  31.0 Obese     \n 2    30 30 and Older    Female    63    106  18.8 Normal    \n 3    32 30 and Older    Female    62    145  26.5 Overweight\n 4    29 Younger than 30 Male      67    195  30.5 Obese     \n 5    24 Younger than 30 Female    67    143  22.4 Normal    \n 6    38 30 and Older    Female    58    125  26.1 Overweight\n 7    25 Younger than 30 Female    64    138  23.7 Normal    \n 8    24 Younger than 30 Male      69    140  20.7 Normal    \n 9    48 30 and Older    Male      65    158  26.3 Overweight\n10    29 Younger than 30 Male      68    167  25.4 Overweight\n# ℹ 58 more rows\n```\n\n\n:::\n:::\n\n\n\n\n\n\n## Single predictor and single outcome\n\nWe can describe our continuous outcome variables using the same methods we learned in previous lessons. However, this time we will use `dplyr's` `group_by()` function to calculate these statistics within subgroups of interests. For example:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass_summary <- class %>% \n  filter(!is.na(ht_in)) %>% \n  group_by(gender) %>% \n  summarise(\n    n                    = n(),\n    mean                 = mean(ht_in),\n    `standard deviation` = sd(ht_in),\n    min                  = min(ht_in),\n    max                  = max(ht_in)\n  ) %>% \n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 6\n  gender     n  mean `standard deviation`   min   max\n  <fct>  <int> <dbl>                <dbl> <dbl> <dbl>\n1 Female    43  64.3                 2.59    58    69\n2 Male      22  69.2                 2.89    65    76\n```\n\n\n:::\n:::\n\n\n\n\n\n\n👆 **Here's what we did above:**\n\n* We used base R's statistical functions inside `dplyr's` `summarise()` function to calculate the number of observations, mean, standard deviation, minimum value and maximum value of height within levels of gender.\n\n* We used `filter(!is.na(ht_in))` to remove all rows from the data that have a missing value for \"ht_in\". If we had not done so, R would have returned a value of \"NA\" for mean, standard deviation, min, and max. Alternatively, we could have added the `na.rm = TRUE` option to each of the `mean()`, `sd()`, `min()`, and `max()` functions. \n\n* We used `group_by(gender)` to calculate our statistics of interest separately within each category of the variable \"gender.\" In this case, \"Female\" and \"Male.\" \n\n* You may notice that we used back ticks around the variable name \"standard deviation\" -- NOT single quotes. If you want to include a space in a variable name in R, you must surround it with back ticks. In general, it's a **really** bad idea to create variable names with spaces in them. It is recommend that you only do so in situations where you are using a data frame to display summary information, as we did above.\n\n* Notice too that we saved our summary statistics table as data frame named \"class_summary.\" Doing so is sometimes useful, especially for plotting as we will see below.\n\nAs you look over this table, you should have an idea of whether male or female students in the class appear to be taller on average, and whether male or female students in the class appear to have more dispersion around the mean value.\n\nFinally, let's plot this data to get a feel for the relationship between gender and height graphically.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass %>% \n  filter(!is.na(ht_in)) %>% \n  ggplot(aes(x = gender, y = ht_in)) +\n    geom_jitter(aes(col = gender), width = 0.20) +\n    geom_segment(\n      aes(x = c(0.75, 1.75), y = mean, xend = c(1.25, 2.25), yend = mean, col = gender), \n      size = 1.5, data = class_summary\n    ) +\n    scale_x_discrete(\"Gender\") +\n    scale_y_continuous(\"Height (Inches)\") +\n    scale_color_manual(values = c(\"#BC581A\", \"#00519B\")) +\n    theme_classic() +\n    theme(legend.position = \"none\", axis.text.x = element_text(size = 12))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](cont_out_cat_pred_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n👆 **Here's what we did above:** \n\n* We used `ggplot2` to plot each student's height as well as the mean heights of female and male students respectively.\n\n* The `geom_jitter()` function plots a point for each student's height, and then makes slight random adjustments to the location of the points so that they are less likely to overlap. One of the great things about plotting our data like this is that we can quickly see if there are many more observations in one category than another. That information would be obscured if we were to use a box plot.\n\n* The `geom_segment()` function creates the two horizontal lines at the mean values of height. Notice we used a different data frame -- class_summary -- using the `data = class_summary` argument to plot the mean values.\n\n* We changed the x and y axis titles using the `scale_x_discrete()` and `scale_y_continuous()` functions.\n\n* We changed the default ggplot colors to orange and blue (Go Gators! 🐊) using the `scale_color_manual()` function.\n\n* We simplified the plot using the `theme_classic()` function.\n\n* `theme(legend.position = \"none\", axis.text.x = element_text(size = 12))` removed the legend and increased the size of the x-axis labels a little bit.\n\nAfter checking both numerical and graphical descriptions of the relationship between gender and height we may conclude that male students were taller, on average, than female students.\n\n## Multiple predictors\n\nAt times we may be interested in comparing continuous outcomes across levels of two or more categorical variables. As an example, perhaps we want to describe BMI by gender _and_ age group. All we have to do is add age group to the `group_by()` function. \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass_summary <- class %>% \n  filter(!is.na(bmi)) %>% \n  group_by(gender, age_group) %>% \n  summarise(\n    n                    = n(),\n    mean                 = mean(bmi),\n    `standard deviation` = sd(bmi),\n    min                  = min(bmi),\n    max                  = max(bmi)\n  ) %>% \n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 7\n# Groups:   gender [2]\n  gender age_group           n  mean `standard deviation`   min   max\n  <fct>  <fct>           <int> <dbl>                <dbl> <dbl> <dbl>\n1 Female Younger than 30    35  23.1                 5.41  17.4  45.2\n2 Female 30 and Older        8  21.8                 5.67  10.6  26.8\n3 Male   Younger than 30    19  24.6                 3.69  19.7  33.0\n4 Male   30 and Older        2  28.6                 3.32  26.3  31.0\n```\n\n\n:::\n:::\n\n\n\n\n\n\nAnd we can see these statistics for BMI within levels of gender separately for younger and older students. Males that are 30 and older report, on average, the highest BMI (28.6). Females age 30 and older report, on average, the lowest BMI (21.8). This is good information, but often when comparing groups a picture really is worth a thousand words. Let's wrap up this chapter with one final plot.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass %>% \n  filter(!is.na(bmi)) %>% \n  ggplot(aes(x = age_group, y = bmi)) +\n    facet_wrap(vars(gender)) +\n    geom_jitter(aes(col = age_group), width = 0.20) +\n    geom_segment(\n      aes(x = rep(c(0.75, 1.75), 2), y = mean, xend = rep(c(1.25, 2.25), 2), yend = mean, \n          col = age_group),\n      size = 1.5, data = class_summary\n    ) +\n    scale_x_discrete(\"Age Group\") +\n    scale_y_continuous(\"BMI\") +\n    scale_color_manual(values = c(\"#BC581A\", \"#00519B\")) +\n    theme_classic() +\n    theme(legend.position = \"none\", axis.text.x = element_text(size = 10))\n```\n\n::: {.cell-output-display}\n![](cont_out_cat_pred_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n👆 **Here's what we did above:** \n\n* We used the same code for this plot that we used for the first height by gender plot. The only difference is that we added `facet_wrap(vars(gender))` to plot males and females on separate plot panels. \n\n\n",
    "supporting": [
      "cont_out_cat_pred_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}